// lint-fixtures.generated.ts — AUTO-GENERATED by
// scripts/vendor-lint-fixtures.mjs from the nika-spec conformance core
// corpus (conformance/tests/core · input.yaml + expected.json pairs).
// DO NOT EDIT · regenerate: node scripts/vendor-lint-fixtures.mjs
// TEST-ONLY module: imported by nika-lint-conformance.test.ts alone —
// never by app code (the corpus must not enter any bundle).
// Drift gate: the test recompiles and byte-diffs; the resync cron
// re-vendors from its fresh spec clone.

export interface LintFixture {
  /** area/case (the spec's own tree) */
  id: string
  /** the spec's static verdict for this input */
  valid: boolean
  /** expected EXACT codes when invalid (sorted) */
  codes: string[]
  /** expected bare namespaces (the spec's latitude: any code within) */
  namespaces: string[]
  yaml: string
}

export const LINT_FIXTURES: LintFixture[] = [
  {
    "id": "dag-topology/001-cycle",
    "valid": false,
    "codes": [
      "NIKA-DAG-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    after: { b: success }\n    infer: { prompt: \"a\" }\n  b:\n    after: { a: success }\n    infer: { prompt: \"b\" }\n"
  },
  {
    "id": "dag-topology/002-unresolved-after-target",
    "valid": false,
    "codes": [
      "NIKA-DAG-002"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    after: { ghost: success }\n    infer: { prompt: \"a\" }\n"
  },
  {
    "id": "dag-topology/003-when-task-ref-illegal",
    "valid": false,
    "codes": [
      "NIKA-VAR-021"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  test:\n    exec: { command: [\"cargo\", \"test\"] }\n  deploy:\n    after: { test: success }\n    when: ${{ tasks.test.duration_ms < 60000 }}\n    exec: { command: [\"./deploy.sh\"] }\n"
  },
  {
    "id": "dag-topology/004-self-dependency",
    "valid": false,
    "codes": [
      "NIKA-DAG-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    after: { a: success }\n    infer: { prompt: \"a\" }\n"
  },
  {
    "id": "dag-topology/005-with-binding-is-the-edge",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  research:\n    infer: { prompt: \"Research\" }\n  summarize:\n    with:\n      content: ${{ tasks.research.output }}\n    infer: { prompt: \"Summarize ${{ with.content }}\" }\n"
  },
  {
    "id": "dag-topology/006-verb-body-reference-illegal",
    "valid": false,
    "codes": [
      "NIKA-VAR-021"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  research:\n    infer: { prompt: \"Research\" }\n  summarize:\n    infer: { prompt: \"Summarize ${{ tasks.research.output }}\" }\n"
  },
  {
    "id": "dag-topology/007-for-each-reference-illegal",
    "valid": false,
    "codes": [
      "NIKA-VAR-021"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  discover:\n    invoke:\n      tool: nika:glob\n      args: { pattern: \"*.md\" }\n  process:\n    for_each: ${{ tasks.discover.output }}\n    exec: { command: [\"process\", \"${{ item }}\"] }\n"
  },
  {
    "id": "dag-topology/008-valid-diamond",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: diamond\ntasks:\n  a:\n    exec: { command: [\"./prepare.sh\"] }\n  b:\n    after: { a: success }\n    infer: { prompt: \"Analyze branch B\" }\n  c:\n    after: { a: success }\n    infer: { prompt: \"Analyze branch C\" }\n  d:\n    with:\n      b: ${{ tasks.b.output }}\n      c: ${{ tasks.c.output }}\n    infer: { prompt: \"Merge · ${{ with.b }} · ${{ with.c }}\" }\n"
  },
  {
    "id": "dag-topology/009-valid-tightened-value-edge",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: chain\ntasks:\n  fetch:\n    invoke:\n      tool: nika:fetch\n      args: { url: \"https://example.com\", mode: article }\n  summarize:\n    after: { fetch: success }\n    with:\n      content: ${{ tasks.fetch.output }}\n    infer:\n      prompt: \"Summarize · ${{ with.content }}\"\n"
  },
  {
    "id": "dag-topology/010-after-malformed-shape",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# Adversarial shape · an after: that is not a map (a sequence). The schema\n# layer flags it · every later layer must SURVIVE it and still produce a\n# collected verdict (oracle crash = conformance bug).\nnika: v1\nworkflow:\n  id: malformed-after\n  description: \"a sequence-shaped after: must not crash the oracle\"\n\ntasks:\n  gather:\n    invoke:\n      tool: \"nika:read\"\n      args: { path: \"./input.txt\" }\n\n  think:\n    after:\n      - gather\n    with:\n      notes: ${{ tasks.gather.output }}\n    infer:\n      prompt: \"Summarize · ${{ with.notes }}\"\n"
  },
  {
    "id": "dag-topology/011-when-boolean-literal",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: core-when-true\ntasks:\n  build:\n    exec: { command: [\"./build.sh\"] }\n  notify:\n    after: { build: terminal }\n    when: true\n    invoke: { tool: \"nika:notify\", args: { message: \"done either way\" } }\n"
  },
  {
    "id": "dag-topology/012-recover-downstream-deadlock",
    "valid": false,
    "codes": [
      "NIKA-DAG-004"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: dag-recover-deadlock\ntasks:\n  fetch:\n    invoke: { tool: \"nika:fetch\", args: { url: \"https://api.example.com\" } }\n    on_error:\n      recover: ${{ tasks.fallback.output }}\n  fallback:\n    after: { fetch: success }\n    infer: { prompt: \"depends on the task it would rescue\" }\n"
  },
  {
    "id": "dag-topology/013-recover-independent-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: dag-recover-independent\ntasks:\n  cached:\n    invoke: { tool: \"nika:read\", args: { path: \"./fixtures/cached.json\" } }\n  fetch:\n    invoke: { tool: \"nika:fetch\", args: { url: \"https://api.example.com\" } }\n    on_error:\n      recover: ${{ tasks.cached.output }}\n"
  },
  {
    "id": "dag-topology/014-depends-on-dead",
    "valid": false,
    "codes": [
      "NIKA-PARSE-024"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    infer: { prompt: \"a\" }\n  b:\n    depends_on: [a]\n    infer: { prompt: \"b\" }\n"
  },
  {
    "id": "dag-topology/015-cycle-mixed-with-after",
    "valid": false,
    "codes": [
      "NIKA-DAG-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    with:\n      b_out: ${{ tasks.b.output }}\n    infer: { prompt: \"a · ${{ with.b_out }}\" }\n  b:\n    after: { a: success }\n    infer: { prompt: \"b\" }\n"
  },
  {
    "id": "dag-topology/016-after-unknown-predicate",
    "valid": false,
    "codes": [
      "NIKA-DAG-005"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  tests:\n    exec: { command: [\"cargo\", \"test\"] }\n  deploy:\n    after: { tests: passed }\n    exec: { command: [\"./deploy.sh\"] }\n"
  },
  {
    "id": "dag-topology/017-on-finally-sibling-ref",
    "valid": false,
    "codes": [
      "NIKA-VAR-021"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  slow:\n    exec: { command: [\"./slow.sh\"] }\n  fast:\n    exec: { command: [\"echo\", \"fast\"] }\n    on_finally:\n      - exec:\n          command: [\"echo\", \"cleanup saw ${{ tasks.slow.output }}\"]\n"
  },
  {
    "id": "envelope/001-valid-minimal",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  greet:\n    infer:\n      prompt: \"Say hi\"\n"
  },
  {
    "id": "envelope/002-valid-full-outputs",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: research-pipeline\nmodel: mock/echo\nvars:\n  topic:\n    type: string\n    required: true\ntasks:\n  research:\n    infer:\n      prompt: \"Research ${{ vars.topic }}\"\n  summarize:\n    with:\n      research: ${{ tasks.research.output }}\n    infer:\n      prompt: \"Summarize ${{ with.research }}\"\noutputs:\n  brief:\n    value: ${{ tasks.summarize.output }}\n    type: string\n"
  },
  {
    "id": "envelope/003-nika-version-bad",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1.0\nworkflow:\n  id: hello\ntasks:\n  greet:\n    infer:\n      prompt: \"hi\"\n"
  },
  {
    "id": "envelope/004-workflow-id-bad",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: Bad_Id\ntasks:\n  greet:\n    infer:\n      prompt: \"hi\"\n"
  },
  {
    "id": "envelope/005-unknown-top-level-key",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nfoo: bar\ntasks:\n  greet:\n    infer:\n      prompt: \"hi\"\n"
  },
  {
    "id": "envelope/006-empty-tasks-array",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks: []\n"
  },
  {
    "id": "envelope/007-missing-workflow",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\ntasks:\n  greet:\n    infer:\n      prompt: \"hi\"\n"
  },
  {
    "id": "envelope/008-secret-inline-literal",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nsecrets:\n  api_key: \"sk-live-12345\"\ntasks:\n  call:\n    exec: { command: [\"curl\", \"-H\", \"'Authorization:\", \"Bearer\", \"${{\", \"secrets.api_key\", \"}}'\", \"https://api.example.com\"] }\n"
  },
  {
    "id": "envelope/009-secret-source-bad-enum",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nsecrets:\n  api_key:\n    source: consul\n    key: prod/api-key\ntasks:\n  call:\n    exec: { command: [\"curl\", \"-H\", \"Authorization: Bearer ${{ secrets.api_key }}\", \"https://api.example.com\"] }\n"
  },
  {
    "id": "envelope/010-typed-var-bad-type",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nvars:\n  topic:\n    type: text\n    required: true\ntasks:\n  a:\n    infer: { prompt: \"Research ${{ vars.topic }}\" }\n"
  },
  {
    "id": "envelope/011-duplicate-task-id",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  build:\n    exec: { command: [\"make\"] }\n  build:\n    exec: { command: [\"make\", \"again\"] }\n"
  },
  {
    "id": "envelope/012-secret-file-source",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "nika: v1\nworkflow:\n  id: core-secret-file\nsecrets:\n  signing_pem:\n    source: file\n    path: ~/.keys/signing.pem\ntasks:\n  sign:\n    exec: { command: [\"./sign.sh\"], env: { PEM: \"${{ secrets.signing_pem }}\" } }\n"
  },
  {
    "id": "envelope/013-secret-missing-source",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: core-secret-bad\nsecrets:\n  api_key: {}\ntasks:\n  go:\n    infer: { prompt: \"x\" }\n"
  },
  {
    "id": "envelope/014-broken-modeline-bare-schema",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "$schema=https://nika.sh/schema/v1/workflow.schema.json\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    exec: { command: [\"true\"] }\n"
  },
  {
    "id": "envelope/015-broken-modeline-decommented-ls",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "yaml-language-server: $schema=https://nika.sh/schema/v1/workflow.schema.json\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    exec: { command: [\"true\"] }\n"
  },
  {
    "id": "envelope/016-workflow-object-ok",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "nika: v1\nworkflow:\n  id: w1-object-form\n  description: The W1 envelope · identity and metadata live in one object\ntasks:\n  hello:\n    exec:\n      command: [\"true\"]\n"
  },
  {
    "id": "envelope/017-workflow-scalar-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow: old-scalar-form\ntasks:\n  hello:\n    exec:\n      command: [\"true\"]\n"
  },
  {
    "id": "envelope/018-top-level-description-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: desc-misplaced\ndescription: I used to live at the top level\ntasks:\n  hello:\n    exec:\n      command: [\"true\"]\n"
  },
  {
    "id": "envelope/019-tasks-sequence-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: tasks-still-a-list\ntasks:\n  - id: hello\n    exec:\n      command: [\"true\"]\n"
  },
  {
    "id": "envelope/020-task-id-field-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: id-field-lingers\ntasks:\n  hello:\n    id: hello\n    exec:\n      command: [\"true\"]\n"
  },
  {
    "id": "envelope/021-duplicate-task-key-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: twin-keys\ntasks:\n  hello:\n    exec:\n      command: [\"true\"]\n  hello:\n    exec:\n      command: [\"false\"]\n"
  },
  {
    "id": "errors/001-timeout-bad-format",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    timeout: \"5w\"\n    exec: { command: [\"echo\", \"hi\"] }\n"
  },
  {
    "id": "errors/002-retry-max-attempts-zero",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  flaky:\n    retry:\n      max_attempts: 0\n    exec: { command: [\"curl\", \"https://flaky.example.com\"] }\n"
  },
  {
    "id": "errors/003-on-error-recover-and-skip-both",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  api_call:\n    invoke:\n      tool: nika:fetch\n      args: { url: \"https://api.example.com/data\" }\n    on_error:\n      recover: \"cached value\"\n      skip: true\n"
  },
  {
    "id": "errors/004-retry-on-codes-bad-pattern",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  flaky:\n    retry:\n      max_attempts: 3\n      on_codes:\n        - NOT-A-CODE\n    exec: { command: [\"curl\", \"https://flaky.example.com\"] }\n"
  },
  {
    "id": "errors/005-timeout-day-unit",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  long_task:\n    timeout: \"2d\"\n    exec: { command: [\"./long-running.sh\"] }\n"
  },
  {
    "id": "errors/006-valid-timeout-compound",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  long_task:\n    timeout: \"1h30m\"\n    exec: { command: [\"./long-running.sh\"] }\n"
  },
  {
    "id": "errors/007-on-error-legacy-fallback-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# The pre-merge on_error legacy forms (fallback:/value:) are NOT the language ·\n# spec/05-errors.md merged them into recover: · rejected at the structural layer.\nnika: v1\nworkflow:\n  id: legacy-fallback-rejected\nmodel: mock/echo\ntasks:\n  a:\n    invoke:\n      tool: \"nika:read\"\n      args: { path: \"./x.json\" }\n    on_error:\n      fallback: \"stale\"\n"
  },
  {
    "id": "errors/008-on-error-on-codes-recover",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "nika: v1\nworkflow:\n  id: core-on-codes\ntasks:\n  slow_fetch:\n    invoke: { tool: \"nika:fetch\", args: { url: \"https://slow.example.com\" } }\n    timeout: \"30s\"\n    on_error:\n      on_codes: [NIKA-TIMEOUT-001]\n      recover: { stale: true }\n"
  },
  {
    "id": "errors/009-on-codes-underscore-builtin",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "nika: v1\nworkflow:\n  id: core-on-codes-underscore\ntasks:\n  merge:\n    invoke: { tool: \"nika:json_merge_patch\", args: { target: {}, patch: {} } }\n    retry:\n      max_attempts: 3\n      on_codes: [NIKA-BUILTIN-JSON_MERGE_PATCH-001]\n"
  },
  {
    "id": "policy/001-human-gate-satisfied",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  require:\n    human_gate_before: [exec]\npermits:\n  exec: [\"echo\"]\n  tools: [\"nika:prompt\"]\ntasks:\n  human:\n    invoke:\n      tool: \"nika:prompt\"\n      args: { message: \"Proceed?\", default: false }\n  act:\n    with: { go: \"${{ tasks.human.output }}\" }\n    when: ${{ with.go == true }}\n    exec: { command: [\"echo\", \"shipped\"] }\n"
  },
  {
    "id": "policy/002-human-gate-missing",
    "valid": false,
    "codes": [
      "NIKA-POLICY-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  require:\n    human_gate_before: [exec]\npermits:\n  exec: [\"echo\"]\ntasks:\n  act:\n    exec: { command: [\"echo\", \"unattended\"] }\n"
  },
  {
    "id": "policy/003-exec-after-net-violation",
    "valid": false,
    "codes": [
      "NIKA-POLICY-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  forbid:\n    exec_after: [net]\npermits:\n  exec: [\"echo\"]\n  net: { http: [\"example.com\"] }\n  tools: [\"nika:fetch\"]\ntasks:\n  fetch_page:\n    invoke:\n      tool: \"nika:fetch\"\n      args: { url: \"https://example.com/data\" }\n  act:\n    with: { body: \"${{ tasks.fetch_page.output }}\" }\n    exec: { command: [\"echo\", \"${{ with.body }}\"] }\n"
  },
  {
    "id": "policy/004-exec-after-net-clean",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  forbid:\n    exec_after: [net]\npermits:\n  exec: [\"echo\"]\n  net: { http: [\"example.com\"] }\n  tools: [\"nika:fetch\"]\ntasks:\n  fetch_page:\n    invoke:\n      tool: \"nika:fetch\"\n      args: { url: \"https://example.com/data\" }\n  act:\n    exec: { command: [\"echo\", \"independent\"] }\n"
  },
  {
    "id": "policy/005-providers-allowlist-violation",
    "valid": false,
    "codes": [
      "NIKA-POLICY-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  allow:\n    providers: [ollama, mistral]\ntasks:\n  s:\n    infer: { prompt: \"summarize\", model: \"openai/gpt-4o\" }\n"
  },
  {
    "id": "policy/006-providers-allowlist-clean",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  allow:\n    providers: [ollama, mistral]\ntasks:\n  s:\n    infer: { prompt: \"summarize\", model: \"ollama/llama3.2\" }\n"
  },
  {
    "id": "policy/007-max-tasks-exceeded",
    "valid": false,
    "codes": [
      "NIKA-POLICY-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  limits:\n    max_tasks: 2\ntasks:\n  a:\n    infer: { prompt: \"one\" }\n  b:\n    infer: { prompt: \"two\" }\n  c:\n    infer: { prompt: \"three\" }\n"
  },
  {
    "id": "policy/008-soft-families-inert",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  prefer:\n    providers: [ollama]\n  optimize: cost\ntasks:\n  s:\n    infer: { prompt: \"summarize\", model: \"openai/gpt-4o\" }\n"
  },
  {
    "id": "policy/009-unknown-rule-refused",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\npolicy:\n  forbid:\n    write_after: [net]\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n"
  },
  {
    "id": "policy/010-provider-templated-fail-closed",
    "valid": false,
    "codes": [
      "NIKA-POLICY-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\nvars:\n  m: { default: \"ollama/llama3.2\" }\npolicy:\n  allow:\n    providers: [ollama]\ntasks:\n  s:\n    infer: { prompt: \"summarize\", model: \"${{ vars.m }}\" }\n"
  },
  {
    "id": "types/001-returns-named-type-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Summary:\n    object:\n      title: string\n      bullets: { array: string }\n      score: { integer: { min: 0, max: 100 } }\ntasks:\n  fetch:\n    exec: { command: [\"cat\", \"article.txt\"] }\n  summarize:\n    with: { article: \"${{ tasks.fetch.output }}\" }\n    infer:\n      prompt: \"Summarize · ${{ with.article }}\"\n    returns: Summary\n"
  },
  {
    "id": "types/002-unknown-type-name",
    "valid": false,
    "codes": [
      "NIKA-TYPE-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Summary: { object: { title: string } }\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: Sumary\n"
  },
  {
    "id": "types/003-recursive-type",
    "valid": false,
    "codes": [
      "NIKA-TYPE-002"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Node: { object: { next: Node } }\ntasks:\n  t:\n    infer: { prompt: \"x\" }\n    returns: Node\n"
  },
  {
    "id": "types/004-returns-and-schema-dup",
    "valid": false,
    "codes": [
      "NIKA-TYPE-003"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  s:\n    infer:\n      prompt: \"x\"\n      schema: { type: object, properties: { a: { type: string } } }\n    returns: { object: { a: string } }\n"
  },
  {
    "id": "types/005-returns-undecodable",
    "valid": false,
    "codes": [
      "NIKA-TYPE-004"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  stats:\n    exec:\n      command: [\"./stats.sh\"]\n    returns: { object: { count: integer } }\n"
  },
  {
    "id": "types/006-decode-json-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  stats:\n    exec:\n      command: [\"jq\", \"-c\", \".stats\", \"report.json\"]\n      decode: json\n    returns: { object: { count: integer, mean: number } }\n"
  },
  {
    "id": "types/007-decode-with-structured-capture",
    "valid": false,
    "codes": [
      "NIKA-PARSE-025"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  probe:\n    exec:\n      command: [\"./run.sh\"]\n      capture: structured\n      decode: json\n"
  },
  {
    "id": "types/008-composed-types-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Verdict: { enum: [\"low\", \"medium\", \"high\"] }\n  Reply:\n    object:\n      risk: Verdict\n      notes: { optional: { array: string } }\ntasks:\n  judge:\n    infer: { prompt: \"assess\" }\n    returns: Reply\n"
  },
  {
    "id": "types/009-reserved-constructor",
    "valid": false,
    "codes": [
      "NIKA-TYPE-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  t:\n    infer: { prompt: \"x\" }\n    returns: result\n"
  },
  {
    "id": "types/010-optional-outside-field",
    "valid": false,
    "codes": [
      "NIKA-TYPE-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: { optional: string }\n"
  },
  {
    "id": "types/011-presence-vs-null-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Story:\n    object:\n      headline: string\n      byline: { optional: string }\n      score: { union: [integer, null] }\n      note: { optional: { union: [string, null] } }\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: Story\n"
  },
  {
    "id": "types/012-regex-out-of-dialect",
    "valid": false,
    "codes": [
      "NIKA-TYPE-006"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Tag: { string: { pattern: \"(?=x)a\" } }\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: Tag\n"
  },
  {
    "id": "types/013-regex-in-dialect-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntypes:\n  Slug: { string: { pattern: \"^[a-z][a-z0-9-]{1,30}$\", max_len: 32 } }\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: Slug\n"
  },
  {
    "id": "types/014-money-reserved",
    "valid": false,
    "codes": [
      "NIKA-TYPE-001"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: t\ntasks:\n  s:\n    infer: { prompt: \"x\" }\n    returns: money\n"
  },
  {
    "id": "variables/001-outputs-reference-missing-task",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    infer: { prompt: \"hi\" }\noutputs:\n  result: ${{ tasks.ghost.output }}\n"
  },
  {
    "id": "variables/002-undefined-namespace",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    infer: { prompt: \"Get ${{ foo.bar }}\" }\n"
  },
  {
    "id": "variables/003-vars-undeclared",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nvars:\n  topic: \"Rust async runtimes\"\ntasks:\n  a:\n    infer: { prompt: \"Research ${{ vars.topik }}\" }\n"
  },
  {
    "id": "variables/004-with-undeclared",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    with:\n      style: \"concise\"\n    infer: { prompt: \"Summarize in ${{ with.style }} style · ${{ with.missing }}\" }\n"
  },
  {
    "id": "variables/005-env-undeclared",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    infer: { prompt: \"Running at ${{ env.MISSING }} verbosity\" }\n"
  },
  {
    "id": "variables/006-secrets-undeclared",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  a:\n    exec: { command: [\"curl\", \"-H\", \"Authorization: Bearer ${{ secrets.api_key }}\", \"https://api.example.com\"] }\n"
  },
  {
    "id": "variables/007-item-outside-for-each",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  process:\n    exec: { command: [\"process\", \"${{ item }}\"] }\n"
  },
  {
    "id": "variables/008-valid-item-index-in-for-each",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: translate\nvars:\n  source: \"Hello world\"\ntasks:\n  translate:\n    for_each: [\"fr\", \"de\", \"ja\"]\n    with:\n      locale: ${{ item }}\n      n: ${{ index }}\n    infer:\n      prompt: \"Translate to locale '${{ with.locale }}' (#${{ with.n }}) · ${{ vars.source }}\"\n"
  },
  {
    "id": "variables/009-output-binding-reserved-name",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  api_call:\n    invoke:\n      tool: nika:fetch\n      args: { url: \"https://api.example.com/data\" }\n    output:\n      status: \".status\"\n"
  },
  {
    "id": "variables/010-valid-escaped-literal",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: docs\ntasks:\n  explain:\n    infer:\n      prompt: 'The syntax \\${{ vars.x }} is how you reference variables in Nika.'\n"
  },
  {
    "id": "variables/011-unclosed-expression",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\nvars:\n  topic: \"Rust\"\ntasks:\n  a:\n    infer: { prompt: \"Research ${{ vars.topic\" }\n"
  },
  {
    "id": "variables/012-output-schema-path-provably-invalid",
    "valid": false,
    "codes": [
      "NIKA-VAR-003"
    ],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# Static binding validation (04 §Static binding validation) · the\n# producing task declares a CLOSED schema (additionalProperties: false) ·\n# the downstream reference path `entitties` is a misspelling the schema\n# provably forbids → NIKA-VAR-003 at parse time.\nnika: v1\nworkflow:\n  id: schema-path-invalid\ntasks:\n  extract:\n    infer:\n      prompt: \"Extract entities\"\n      schema:\n        type: object\n        additionalProperties: false\n        required: [entities]\n        properties:\n          entities:\n            type: array\n            items: { type: string }\n  report:\n    with:\n      extract_entitties: ${{ tasks.extract.output.entitties }}\n    exec:\n      command: [\"report\", \"${{ with.extract_entitties }}\"]\n"
  },
  {
    "id": "variables/013-valid-output-schema-open-path",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# Static binding validation soundness · OPEN levels are never rejected ·\n# (a) `meta` has no additionalProperties:false → unknown keys below stay\n# legal · (b) a schema-less producer (exec) is fully dynamic · (c) a\n# declared property path is of course valid. The engine MUST accept.\nnika: v1\nworkflow:\n  id: schema-path-open\ntasks:\n  extract:\n    infer:\n      prompt: \"Extract entities\"\n      schema:\n        type: object\n        required: [entities]\n        properties:\n          entities:\n            type: array\n            items: { type: string }\n          meta:\n            type: object\n  fetch_raw:\n    exec: { command: [\"./dump.sh\"] }\n  report:\n    with:\n      extract_entities: ${{ tasks.extract.output.entities }}\n      extract_meta_anything: ${{ tasks.extract.output.meta.anything }}\n      extract_maybe_extra: ${{ tasks.extract.output.maybe_extra }}\n      fetch_raw_whatever: ${{ tasks.fetch_raw.output.whatever }}\n    exec:\n      command: [\"report\", \"${{ with.extract_entities }}\", \"${{ with.extract_meta_anything }}\", \"${{ with.extract_maybe_extra }}\", \"${{ with.fetch_raw_whatever }}\"]\n"
  },
  {
    "id": "variables/020-bare-task-ref-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-VAR"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# D2 (breaking-window #75): the task result is a record — unprojected\n# access is ill-typed. Pick .output (the value) or .status/.error/.duration_ms.\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  gather:\n    invoke:\n      tool: \"nika:read\"\n      args: { path: \"./README.md\" }\n  think:\n    with:\n      gather: ${{ tasks.gather }}\n    infer:\n      prompt: \"Summarize ${{ with.gather }}\"\n"
  },
  {
    "id": "verbs-shape/001-two-verbs",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  greet:\n    infer:\n      prompt: \"hi\"\n    exec:\n      command: [\"echo\", \"hi\"]\n"
  },
  {
    "id": "verbs-shape/002-no-verb",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  greet:\n"
  },
  {
    "id": "verbs-shape/003-agent-with-schema-valid",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: review\nvars:\n  pr: { type: string, required: true }\ntasks:\n  review:\n    agent:\n      prompt: \"Review ${{ vars.pr }}\"\n      tools: [\"nika:read\", \"nika:done\"]\n      schema:\n        type: object\n        required: [findings]\n        properties:\n          findings: { type: array }\n"
  },
  {
    "id": "verbs-shape/004-task-id-not-snake-case",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  my-task:\n    infer:\n      prompt: \"hi\"\n"
  },
  {
    "id": "verbs-shape/005-exec-without-command",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  run:\n    exec:\n      cwd: \"/tmp\"\n"
  },
  {
    "id": "verbs-shape/006-infer-without-prompt",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  think:\n    infer:\n      model: mock/echo\n"
  },
  {
    "id": "verbs-shape/007-invoke-without-tool",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  call:\n    invoke:\n      args: { url: \"https://example.com\" }\n"
  },
  {
    "id": "verbs-shape/008-agent-without-prompt",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  review:\n    agent:\n      tools: [\"nika:read\", \"nika:done\"]\n"
  },
  {
    "id": "verbs-shape/009-unknown-field-on-verb-strict",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  think:\n    infer:\n      prompt: \"hi\"\n      temperture: 0.5\n"
  },
  {
    "id": "verbs-shape/010-x-vendor-tool-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: vendor-tool\ntasks:\n  research:\n    invoke:\n      tool: \"x-superclever:research\"\n      args:\n        topic: \"rust workflow engines\"\n"
  },
  {
    "id": "verbs-shape/011-mcp-no-slash",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "nika: v1\nworkflow:\n  id: core-mcp-no-slash\ntasks:\n  q:\n    invoke: { tool: \"mcp:postgres\", args: { sql: \"SELECT 1\" } }\n"
  },
  {
    "id": "verbs-shape/020-exec-string-command-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\n# D1 (breaking-window #75): semantics never fork on a YAML type — the\n# string form (the old implicit shell) is rejected; the shell door is\n# the explicit `shell:` field.\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  run:\n    exec:\n      command: \"echo hello | wc -l\"\n"
  },
  {
    "id": "verbs-shape/021-exec-shell-and-command-rejected",
    "valid": false,
    "codes": [],
    "namespaces": [
      "NIKA-PARSE"
    ],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  run:\n    exec:\n      command: [\"echo\", \"hi\"]\n      shell: \"echo hi\"\n"
  },
  {
    "id": "verbs-shape/022-exec-shell-form",
    "valid": true,
    "codes": [],
    "namespaces": [],
    "yaml": "# SPDX-License-Identifier: Apache-2.0\nnika: v1\nworkflow:\n  id: hello\ntasks:\n  run:\n    exec:\n      shell: \"echo hello | wc -l\"\n"
  }
]
