// extractors/estate.mjs — the site's own estate, as a graph node: nika.sh is
// a CITIZEN of the city it maps (§J.6 — the site eats its own food). The
// class census renders on /city/nika.sh at the casse; the release node the
// engine pin names is minted here too (identity from the pin, never typed).

import { edge, node, readJson, readYamlFile } from '../lib.mjs'

export function extract({ engineRef }) {
  const estate = readYamlFile('estate.yaml')
  const pin = readJson('.github/nika-engine-pin.json')
  const s = estate.summary ?? {}
  return {
    families: [
      { family: 'estate-manifest', count: 1, rooms_exist: false, source: 'estate.yaml', clock: 'site' },
      { family: 'release', count: 1, rooms_exist: false, lands: 'casse-wave (train 0.107 · /releases/:v · D2)', source: '.github/nika-engine-pin.json', clock: 'engine-release', note: 'the full 23-release ladder joins at the casse (releases extractor · gh-fed lane)' },
    ],
    nodes: [
      node({
        id: 'estate-manifest:nika.sh',
        family: 'estate-manifest',
        title: 'the nika.sh estate (schema 2 · E1)',
        data: {
          classified_files: s.classified_files ?? null,
          by_class: s.by_class ?? null,
          unverified: s['unverified-default'] ?? null,
        },
        evidence: 'estate.yaml summary block — rendered by the shared estate tool (byte-identical mirror at ESTATE_PIN)',
        provenance: 'supernovae-st/nika.sh · estate.yaml (generated by scripts/estate.py)',
      }),
      node({
        id: `release:${pin.release_tag}`,
        family: 'release',
        title: `nika ${pin.release_tag}`,
        lands: 'casse-wave (train 0.107 · /releases/:v · D2)',
        data: { repository: pin.repository, commit: pin.engine_commit, tree: pin.engine_tree },
        evidence: 'the engine pin (commit + tree · digest-verified by scripts/engine-resync.mjs before any vendoring)',
        provenance: `${engineRef} · .github/nika-engine-pin.json`,
      }),
    ],
    edges: [
      edge({
        from: 'building:engine',
        rel: 'ships',
        to: `release:${pin.release_tag}`,
        evidence: 'the engine pin names the release the /catalog world derives from (.github/nika-engine-pin.json — identity read, never typed)',
        provenance: `${engineRef} · .github/nika-engine-pin.json`,
      }),
    ],
    inputs: [{ path: 'estate.yaml' }, { path: '.github/nika-engine-pin.json' }],
  }
}
