// map-data.generated.ts — AUTO-GENERATED by scripts/atlas/build-atlas.mjs from
// scripts/atlas/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/atlas/build-atlas.mjs
// Drift gate: src/test/atlas.test.ts recompiles and byte-diffs.

export interface MapSet {
  id: string
  title: string
  url: string
  count: number
  surface: string
  slot: string | null
  closed: boolean
  /** the page is served today — a chip only links when true */
  exists: boolean
  lands: string | null
}
export interface MapLayer {
  id: string
  title: string
  hub: string
  exists: boolean
  lands: string | null
  opener: string
  sets: MapSet[]
}

export const MAP_OPENER = "Nika is a workflow language for agentic work. Everything it is fits on this map: seven layers, every set counted, every member accountable to the spec."

export const MAP_LAYERS: MapLayer[] = [
  {
    "id": "shape",
    "title": "The shape",
    "hub": "/language",
    "exists": true,
    "lands": null,
    "opener": "The shape layer is every word an author can type: the envelope, the task grammar, the namespaces that scope every value. If a key is not declared here, it is not Nika.",
    "sets": [
      {
        "id": "words",
        "title": "The language words",
        "url": "/language",
        "count": 53,
        "surface": "rooms",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "namespaces",
        "title": "The namespaces",
        "url": "/language",
        "count": 5,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": true,
        "lands": null
      },
      {
        "id": "types",
        "title": "The types",
        "url": "/language",
        "count": 0,
        "surface": "anchors",
        "slot": "W3",
        "closed": false,
        "exists": true,
        "lands": null
      }
    ]
  },
  {
    "id": "flow",
    "title": "The flow",
    "hub": "/flow",
    "exists": false,
    "lands": "wo-4",
    "opener": "Tasks link through two doors: with binds values, after orders effects. The engine reads those bindings and builds the run graph · nothing else creates an edge.",
    "sets": [
      {
        "id": "edge-kinds",
        "title": "The edge kinds",
        "url": "/flow",
        "count": 6,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": false,
        "lands": "wo-4"
      },
      {
        "id": "gate-predicates",
        "title": "The gate predicates",
        "url": "/flow",
        "count": 4,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": false,
        "lands": "wo-4"
      }
    ]
  },
  {
    "id": "acts",
    "title": "The acts",
    "hub": "/verbs",
    "exists": true,
    "lands": null,
    "opener": "A verb is a distinct native execution model: infer thinks, exec runs, invoke calls a tool, agent loops with judgment. The set is closed by design · everything callable is a tool under invoke.",
    "sets": [
      {
        "id": "verbs",
        "title": "The four verbs",
        "url": "/verbs",
        "count": 4,
        "surface": "rooms",
        "slot": null,
        "closed": true,
        "exists": true,
        "lands": null
      }
    ]
  },
  {
    "id": "reach",
    "title": "The reach",
    "hub": "/tools",
    "exists": true,
    "lands": null,
    "opener": "Reach is what a workflow can touch: the standard library, the model providers, the routing skeletons. Every capability is named, cataloged and versioned · nothing arrives by plugin.",
    "sets": [
      {
        "id": "builtins",
        "title": "The standard library",
        "url": "/tools",
        "count": 27,
        "surface": "rooms",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "tool-families",
        "title": "The tool families",
        "url": "/tools",
        "count": 6,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "providers",
        "title": "The providers",
        "url": "/providers",
        "count": 16,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "extract-modes",
        "title": "The extract modes",
        "url": "/tools/fetch",
        "count": 9,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "templates",
        "title": "The templates",
        "url": "/templates",
        "count": 10,
        "surface": "rooms",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      }
    ]
  },
  {
    "id": "boundary",
    "title": "The boundary",
    "hub": "/boundary",
    "exists": false,
    "lands": "wo-4",
    "opener": "The file declares its blast radius. Permits allowlist what runs, reads, writes and calls · secrets stay masked references. Absent means the engine floor, present means default-deny.",
    "sets": [
      {
        "id": "permit-families",
        "title": "The permit families",
        "url": "/boundary",
        "count": 4,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": false,
        "lands": "wo-4"
      },
      {
        "id": "secret-sources",
        "title": "The secret sources",
        "url": "/boundary",
        "count": 3,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": false,
        "lands": "wo-4"
      }
    ]
  },
  {
    "id": "refusals",
    "title": "The refusals",
    "hub": "/errors",
    "exists": true,
    "lands": null,
    "opener": "Every refusal has a name. Errors are data: stable codes with a category, a transient flag and a documented fix shape · never prose exceptions.",
    "sets": [
      {
        "id": "error-codes",
        "title": "The error codes",
        "url": "/errors",
        "count": 61,
        "surface": "rooms",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "error-namespaces",
        "title": "The error namespaces",
        "url": "/errors",
        "count": 14,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      },
      {
        "id": "error-categories",
        "title": "The error categories",
        "url": "/errors",
        "count": 12,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": true,
        "lands": null
      }
    ]
  },
  {
    "id": "proof",
    "title": "The proof",
    "hub": "/proof",
    "exists": false,
    "lands": "wo-4",
    "opener": "A run you can verify, a graph you can read. The proof layer is how Nika shows its work: the run graph, the hash-chained trace, the conformance suite that re-proves every claim.",
    "sets": [
      {
        "id": "conformance-levels",
        "title": "The conformance levels",
        "url": "/proof",
        "count": 3,
        "surface": "anchors",
        "slot": null,
        "closed": true,
        "exists": false,
        "lands": "wo-4"
      },
      {
        "id": "mcp-tools",
        "title": "The oracle tools",
        "url": "/proof",
        "count": 8,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": false,
        "lands": "wo-4"
      },
      {
        "id": "showcases",
        "title": "The showcases",
        "url": "/use-cases",
        "count": 26,
        "surface": "rooms",
        "slot": null,
        "closed": false,
        "exists": false,
        "lands": "wo-5"
      },
      {
        "id": "truth-words",
        "title": "The truth words",
        "url": "/sources",
        "count": 10,
        "surface": "anchors",
        "slot": null,
        "closed": false,
        "exists": false,
        "lands": "wo-7"
      }
    ]
  }
]
