// anatomy.generated.ts — AUTO-GENERATED by scripts/build-anatomy.mjs:
// the ENGINE'S OWN reading (`nika inspect --format json` · the released
// binary) of every showcase room (as SERVED · the door's W2 form) and every
// library flagship. DO NOT EDIT · regenerate: node scripts/build-anatomy.mjs
// Drift gates: src/test/anatomy.test.ts (byte-diff · slug parity · node⊆dag).

export interface AnatomyNode {
  id: string
  verb: 'infer' | 'exec' | 'invoke' | 'agent'
  tool?: string
  model?: string
  when?: string
  fan_out?: unknown
  /** the permit rows THIS node needs, in the engine's own words */
  permits: string[]
  cost_interval?: unknown
}
export interface AnatomyEdge {
  from: string
  to: string
  kind: string
}
export interface Anatomy {
  graph_format: number
  workflow: string
  nodes: AnatomyNode[]
  edges: AnatomyEdge[]
}

/** the engine release these graphs were read from (the provenance stamp) */
export const ANATOMY_ENGINE = "0.107.0"

export const ANATOMY: Record<string, Anatomy> = {
  "agent-loop": {
    "graph_format": 2,
    "workflow": "agent-loop-template",
    "nodes": [
      {
        "id": "plan",
        "verb": "infer",
        "model": "ollama/qwen2.5:14b",
        "permits": []
      },
      {
        "id": "execute",
        "verb": "agent",
        "model": "ollama/qwen2.5:14b",
        "permits": [
          "tool: nika:done",
          "tool: nika:jq"
        ]
      },
      {
        "id": "confirm",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      }
    ],
    "edges": [
      {
        "from": "execute",
        "to": "confirm",
        "kind": "value"
      },
      {
        "from": "plan",
        "to": "execute",
        "kind": "value"
      }
    ]
  },
  "api-upload-and-create": {
    "graph_format": 2,
    "workflow": "api-upload-and-create-template",
    "nodes": [
      {
        "id": "create",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      }
    ],
    "edges": []
  },
  "bookmark-triage": {
    "graph_format": 2,
    "workflow": "bookmark-triage",
    "nodes": [
      {
        "id": "pages",
        "verb": "invoke",
        "tool": "nika:fetch",
        "fan_out": {
          "kind": "expression",
          "count": 3
        },
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "table",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "report",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/bookmarks.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "pages",
        "to": "table",
        "kind": "value"
      },
      {
        "from": "table",
        "to": "report",
        "kind": "value"
      },
      {
        "from": "table",
        "to": "report",
        "kind": "value"
      }
    ]
  },
  "ceo-monday-brief": {
    "graph_format": 2,
    "workflow": "ceo-monday-brief",
    "nodes": [
      {
        "id": "approve",
        "verb": "invoke",
        "tool": "nika:prompt",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "news",
        "verb": "invoke",
        "tool": "nika:fetch",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "pulse",
        "verb": "exec",
        "when": "${{ with.go == true }}",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "sheet",
        "verb": "invoke",
        "tool": "nika:read",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "stamp",
        "verb": "invoke",
        "tool": "nika:date",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "rows",
        "verb": "invoke",
        "tool": "nika:convert",
        "when": "${{ with.csv != null }}",
        "permits": [
          "tool: nika:convert"
        ]
      },
      {
        "id": "revenue",
        "verb": "invoke",
        "tool": "nika:jq",
        "when": "${{ with.rows != null }}",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ with.go == true }}",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "alert",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ with.armed == true }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "approve",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "news",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "pulse",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "sheet",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "stamp",
        "kind": "value"
      },
      {
        "from": "brief",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "news",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "pulse",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "revenue",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "revenue",
        "kind": "value"
      },
      {
        "from": "save",
        "to": "alert",
        "kind": "control"
      },
      {
        "from": "save",
        "to": "alert",
        "kind": "terminal-observation"
      },
      {
        "from": "sheet",
        "to": "rows",
        "kind": "value"
      },
      {
        "from": "stamp",
        "to": "alert",
        "kind": "value"
      },
      {
        "from": "stamp",
        "to": "save",
        "kind": "value"
      }
    ]
  },
  "chain": {
    "graph_format": 2,
    "workflow": "chain-template",
    "nodes": [
      {
        "id": "gather",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "think",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "persist",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "gather",
        "to": "think",
        "kind": "value"
      },
      {
        "from": "think",
        "to": "persist",
        "kind": "value"
      }
    ]
  },
  "competitor-radar": {
    "graph_format": 2,
    "workflow": "competitor-radar",
    "nodes": [
      {
        "id": "now",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "map",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "cutoff",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "cutoff_day",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "recent",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "pages",
        "verb": "invoke",
        "tool": "nika:fetch",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "readable",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "digest",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ size(with.readable) > 0 }}",
        "permits": []
      },
      {
        "id": "record",
        "verb": "invoke",
        "tool": "nika:emit",
        "permits": [
          "tool: nika:emit"
        ]
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.digest != null }}",
        "permits": [
          "fs.write: ./radar/competitor-brief.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "cutoff",
        "to": "cutoff_day",
        "kind": "value"
      },
      {
        "from": "cutoff_day",
        "to": "digest",
        "kind": "value"
      },
      {
        "from": "cutoff_day",
        "to": "recent",
        "kind": "value"
      },
      {
        "from": "cutoff_day",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "digest",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "map",
        "to": "recent",
        "kind": "value"
      },
      {
        "from": "now",
        "to": "cutoff",
        "kind": "value"
      },
      {
        "from": "pages",
        "to": "readable",
        "kind": "value"
      },
      {
        "from": "readable",
        "to": "digest",
        "kind": "value"
      },
      {
        "from": "readable",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "recent",
        "to": "pages",
        "kind": "value"
      },
      {
        "from": "recent",
        "to": "readable",
        "kind": "value"
      },
      {
        "from": "recent",
        "to": "record",
        "kind": "value"
      }
    ]
  },
  "config-drift-sentinel": {
    "graph_format": 2,
    "workflow": "config-drift-sentinel",
    "nodes": [
      {
        "id": "live_raw",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "baseline_raw",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "fingerprint",
        "verb": "invoke",
        "tool": "nika:hash",
        "permits": [
          "tool: nika:hash"
        ]
      },
      {
        "id": "parsed",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "expected",
        "verb": "invoke",
        "tool": "nika:json_merge_patch",
        "permits": [
          "tool: nika:json_merge_patch"
        ]
      },
      {
        "id": "drift",
        "verb": "invoke",
        "tool": "nika:json_diff",
        "permits": [
          "tool: nika:json_diff"
        ]
      },
      {
        "id": "paging",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "explain",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ size(with.patch) > 0 }}",
        "permits": []
      },
      {
        "id": "alert",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ size(with.paging) > 0 }}",
        "permits": [
          "tool: nika:notify"
        ]
      },
      {
        "id": "record",
        "verb": "invoke",
        "tool": "nika:emit",
        "permits": [
          "tool: nika:emit"
        ]
      }
    ],
    "edges": [
      {
        "from": "baseline_raw",
        "to": "parsed",
        "kind": "value"
      },
      {
        "from": "drift",
        "to": "explain",
        "kind": "value"
      },
      {
        "from": "drift",
        "to": "paging",
        "kind": "value"
      },
      {
        "from": "drift",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "expected",
        "to": "drift",
        "kind": "value"
      },
      {
        "from": "explain",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "fingerprint",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "live_raw",
        "to": "fingerprint",
        "kind": "value"
      },
      {
        "from": "live_raw",
        "to": "parsed",
        "kind": "value"
      },
      {
        "from": "paging",
        "to": "alert",
        "kind": "value"
      },
      {
        "from": "paging",
        "to": "record",
        "kind": "value"
      },
      {
        "from": "parsed",
        "to": "drift",
        "kind": "value"
      },
      {
        "from": "parsed",
        "to": "expected",
        "kind": "value"
      }
    ]
  },
  "contract-guard": {
    "graph_format": 2,
    "workflow": "contract-guard",
    "nodes": [
      {
        "id": "contract",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "clauses",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "check",
        "verb": "invoke",
        "tool": "nika:validate",
        "permits": [
          "tool: nika:validate"
        ]
      },
      {
        "id": "gate",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      },
      {
        "id": "memo",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/risk-memo.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "check",
        "to": "gate",
        "kind": "value"
      },
      {
        "from": "clauses",
        "to": "check",
        "kind": "value"
      },
      {
        "from": "clauses",
        "to": "memo",
        "kind": "value"
      },
      {
        "from": "contract",
        "to": "clauses",
        "kind": "value"
      },
      {
        "from": "gate",
        "to": "memo",
        "kind": "control"
      },
      {
        "from": "memo",
        "to": "save",
        "kind": "value"
      }
    ]
  },
  "csv-chart-report": {
    "graph_format": 2,
    "workflow": "csv-chart-report",
    "nodes": [
      {
        "id": "raw",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "rows",
        "verb": "invoke",
        "tool": "nika:convert",
        "permits": [
          "tool: nika:convert"
        ]
      },
      {
        "id": "by_region",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "chart",
        "verb": "invoke",
        "tool": "nika:chart",
        "permits": [
          "fs.write: out/revenue-by-region.svg",
          "tool: nika:chart"
        ]
      },
      {
        "id": "rows_md",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "report",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/revenue-report.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "by_region",
        "to": "chart",
        "kind": "value"
      },
      {
        "from": "by_region",
        "to": "rows_md",
        "kind": "value"
      },
      {
        "from": "chart",
        "to": "report",
        "kind": "control"
      },
      {
        "from": "raw",
        "to": "rows",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "by_region",
        "kind": "value"
      },
      {
        "from": "rows_md",
        "to": "report",
        "kind": "value"
      }
    ]
  },
  "daily-brief": {
    "graph_format": 2,
    "workflow": "daily-brief",
    "nodes": [
      {
        "id": "notes",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./notes/today.md",
          "tool: nika:read"
        ]
      },
      {
        "id": "inbox",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./notes/inbox.md",
          "tool: nika:read"
        ]
      },
      {
        "id": "calendar",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./notes/calendar.md",
          "tool: nika:read"
        ]
      },
      {
        "id": "triage",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "agenda",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "draft",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: ./brief.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "agenda",
        "to": "draft",
        "kind": "value"
      },
      {
        "from": "calendar",
        "to": "agenda",
        "kind": "value"
      },
      {
        "from": "draft",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "inbox",
        "to": "triage",
        "kind": "value"
      },
      {
        "from": "notes",
        "to": "draft",
        "kind": "value"
      },
      {
        "from": "triage",
        "to": "draft",
        "kind": "value"
      }
    ]
  },
  "deep-research-brief": {
    "graph_format": 2,
    "workflow": "deep-research-brief",
    "nodes": [
      {
        "id": "slug",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "plan",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "investigate",
        "verb": "agent",
        "model": "ollama/qwen3.5:4b",
        "permits": [
          "tool: nika:done",
          "tool: nika:fetch"
        ]
      },
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "brief",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "investigate",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "investigate",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "plan",
        "to": "investigate",
        "kind": "value"
      },
      {
        "from": "slug",
        "to": "save",
        "kind": "value"
      }
    ]
  },
  "docker-report": {
    "graph_format": 2,
    "workflow": "docker-report-template",
    "nodes": [
      {
        "id": "ps",
        "verb": "exec",
        "permits": [
          "exec: docker"
        ]
      },
      {
        "id": "df",
        "verb": "exec",
        "permits": [
          "exec: docker"
        ]
      },
      {
        "id": "diagnose",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "keep",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: ./docker-health.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "df",
        "to": "diagnose",
        "kind": "value"
      },
      {
        "from": "diagnose",
        "to": "keep",
        "kind": "value"
      },
      {
        "from": "ps",
        "to": "diagnose",
        "kind": "value"
      }
    ]
  },
  "etl-quarantine": {
    "graph_format": 2,
    "workflow": "etl-quarantine",
    "nodes": [
      {
        "id": "empty_batch",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "raw",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "rows",
        "verb": "invoke",
        "tool": "nika:convert",
        "permits": [
          "tool: nika:convert"
        ]
      },
      {
        "id": "check",
        "verb": "invoke",
        "tool": "nika:validate",
        "permits": [
          "tool: nika:validate"
        ]
      },
      {
        "id": "good",
        "verb": "invoke",
        "tool": "nika:jq",
        "when": "${{ with.valid == true }}",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "quarantine",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.valid == false }}",
        "permits": [
          "fs.write: out/quarantine/orders-rejected.json",
          "tool: nika:write"
        ]
      },
      {
        "id": "report",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.totals != null && size(with.totals) > 0 }}",
        "permits": [
          "fs.write: out/reports/daily-totals.json",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "check",
        "to": "good",
        "kind": "value"
      },
      {
        "from": "check",
        "to": "quarantine",
        "kind": "value"
      },
      {
        "from": "check",
        "to": "quarantine",
        "kind": "value"
      },
      {
        "from": "empty_batch",
        "to": "rows",
        "kind": "recovery"
      },
      {
        "from": "good",
        "to": "report",
        "kind": "value"
      },
      {
        "from": "raw",
        "to": "rows",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "check",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "good",
        "kind": "value"
      }
    ]
  },
  "etl-state": {
    "graph_format": 2,
    "workflow": "etl-state-template",
    "nodes": [
      {
        "id": "approve",
        "verb": "invoke",
        "tool": "nika:prompt",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "previous_raw",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "fresh",
        "verb": "invoke",
        "tool": "nika:fetch",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "previous",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "save_state",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "delta",
        "verb": "invoke",
        "tool": "nika:json_diff",
        "permits": [
          "tool: nika:json_diff"
        ]
      },
      {
        "id": "process",
        "verb": "invoke",
        "tool": "nika:jq",
        "when": "${{ size(with.delta) > 0 }}",
        "permits": [
          "tool: nika:jq"
        ]
      }
    ],
    "edges": [
      {
        "from": "approve",
        "to": "fresh",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "save_state",
        "kind": "value"
      },
      {
        "from": "delta",
        "to": "process",
        "kind": "value"
      },
      {
        "from": "fresh",
        "to": "delta",
        "kind": "value"
      },
      {
        "from": "fresh",
        "to": "save_state",
        "kind": "value"
      },
      {
        "from": "previous",
        "to": "delta",
        "kind": "value"
      },
      {
        "from": "previous_raw",
        "to": "previous",
        "kind": "value"
      }
    ]
  },
  "fanout": {
    "graph_format": 2,
    "workflow": "fanout-template",
    "nodes": [
      {
        "id": "discover",
        "verb": "invoke",
        "tool": "nika:glob",
        "permits": [
          "tool: nika:glob"
        ]
      },
      {
        "id": "process",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "fan_out": {
          "kind": "expression"
        },
        "permits": []
      },
      {
        "id": "survivors",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "merge",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      }
    ],
    "edges": [
      {
        "from": "discover",
        "to": "process",
        "kind": "value"
      },
      {
        "from": "process",
        "to": "survivors",
        "kind": "value"
      },
      {
        "from": "survivors",
        "to": "merge",
        "kind": "value"
      }
    ]
  },
  "gate-and-act": {
    "graph_format": 2,
    "workflow": "gate-and-act-template",
    "nodes": [
      {
        "id": "check",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "act",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ with.value > const.threshold }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "check",
        "to": "act",
        "kind": "value"
      }
    ]
  },
  "human-gated-ship": {
    "graph_format": 2,
    "workflow": "human-gated-ship-template",
    "nodes": [
      {
        "id": "check_a",
        "verb": "exec",
        "permits": [
          "exec: echo"
        ]
      },
      {
        "id": "check_b",
        "verb": "exec",
        "permits": [
          "exec: echo"
        ]
      },
      {
        "id": "gates",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      },
      {
        "id": "human",
        "verb": "invoke",
        "tool": "nika:prompt",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "act",
        "verb": "exec",
        "when": "${{ with.go == true }}",
        "permits": [
          "exec: echo"
        ]
      },
      {
        "id": "record",
        "verb": "invoke",
        "tool": "nika:notify",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "act",
        "to": "record",
        "kind": "control"
      },
      {
        "from": "act",
        "to": "record",
        "kind": "terminal-observation"
      },
      {
        "from": "check_a",
        "to": "gates",
        "kind": "value"
      },
      {
        "from": "check_b",
        "to": "gates",
        "kind": "value"
      },
      {
        "from": "gates",
        "to": "human",
        "kind": "control"
      },
      {
        "from": "human",
        "to": "act",
        "kind": "value"
      }
    ]
  },
  "image-fx-batch": {
    "graph_format": 2,
    "workflow": "image-fx-batch",
    "nodes": [
      {
        "id": "shots",
        "verb": "invoke",
        "tool": "nika:glob",
        "permits": [
          "tool: nika:glob"
        ]
      },
      {
        "id": "jobs",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "stylize",
        "verb": "invoke",
        "tool": "nika:image_fx",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:image_fx"
        ]
      }
    ],
    "edges": [
      {
        "from": "jobs",
        "to": "stylize",
        "kind": "value"
      },
      {
        "from": "shots",
        "to": "jobs",
        "kind": "value"
      }
    ]
  },
  "incident-war-room": {
    "graph_format": 2,
    "workflow": "incident-war-room",
    "nodes": [
      {
        "id": "approve",
        "verb": "invoke",
        "tool": "nika:prompt",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "deploys",
        "verb": "exec",
        "when": "${{ with.go == true }}",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "status_history",
        "verb": "invoke",
        "tool": "nika:fetch",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "runbook",
        "verb": "invoke",
        "tool": "nika:read",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "timeline",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ with.runbook != null }}",
        "permits": []
      },
      {
        "id": "settle",
        "verb": "invoke",
        "tool": "nika:wait",
        "permits": [
          "tool: nika:wait"
        ]
      },
      {
        "id": "recheck",
        "verb": "invoke",
        "tool": "nika:fetch",
        "when": "${{ with.go == true }}",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "confirmed",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      },
      {
        "id": "postmortem",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "alert",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ with.armed == true }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "approve",
        "to": "deploys",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "recheck",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "runbook",
        "kind": "value"
      },
      {
        "from": "approve",
        "to": "status_history",
        "kind": "value"
      },
      {
        "from": "confirmed",
        "to": "postmortem",
        "kind": "control"
      },
      {
        "from": "deploys",
        "to": "timeline",
        "kind": "value"
      },
      {
        "from": "postmortem",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "recheck",
        "to": "confirmed",
        "kind": "value"
      },
      {
        "from": "runbook",
        "to": "timeline",
        "kind": "value"
      },
      {
        "from": "save",
        "to": "alert",
        "kind": "control"
      },
      {
        "from": "save",
        "to": "alert",
        "kind": "terminal-observation"
      },
      {
        "from": "settle",
        "to": "recheck",
        "kind": "control"
      },
      {
        "from": "status_history",
        "to": "timeline",
        "kind": "value"
      },
      {
        "from": "timeline",
        "to": "postmortem",
        "kind": "value"
      },
      {
        "from": "timeline",
        "to": "settle",
        "kind": "control"
      }
    ]
  },
  "invoice-chaser": {
    "graph_format": 2,
    "workflow": "invoice-chaser",
    "nodes": [
      {
        "id": "ledger",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "rows",
        "verb": "invoke",
        "tool": "nika:convert",
        "permits": [
          "tool: nika:convert"
        ]
      },
      {
        "id": "overdue",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "drafts",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ size(with.overdue) > 0 }}",
        "permits": []
      },
      {
        "id": "approve",
        "verb": "invoke",
        "tool": "nika:prompt",
        "when": "${{ with.drafts != null }}",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.drafts != null && with.approved == true }}",
        "permits": [
          "fs.write: out/reminders-to-send.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "approve",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "drafts",
        "to": "approve",
        "kind": "value"
      },
      {
        "from": "drafts",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "ledger",
        "to": "rows",
        "kind": "value"
      },
      {
        "from": "overdue",
        "to": "drafts",
        "kind": "value"
      },
      {
        "from": "rows",
        "to": "overdue",
        "kind": "value"
      }
    ]
  },
  "localization-factory": {
    "graph_format": 2,
    "workflow": "localization-factory",
    "nodes": [
      {
        "id": "files",
        "verb": "invoke",
        "tool": "nika:glob",
        "permits": [
          "tool: nika:glob"
        ]
      },
      {
        "id": "texts",
        "verb": "invoke",
        "tool": "nika:read",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "pairs",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "translated",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "fan_out": {
          "kind": "expression"
        },
        "permits": []
      },
      {
        "id": "bundle",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "mirror",
        "verb": "invoke",
        "tool": "nika:write",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "bundle",
        "to": "mirror",
        "kind": "value"
      },
      {
        "from": "files",
        "to": "pairs",
        "kind": "value"
      },
      {
        "from": "files",
        "to": "texts",
        "kind": "value"
      },
      {
        "from": "pairs",
        "to": "bundle",
        "kind": "value"
      },
      {
        "from": "pairs",
        "to": "translated",
        "kind": "value"
      },
      {
        "from": "texts",
        "to": "pairs",
        "kind": "value"
      },
      {
        "from": "translated",
        "to": "bundle",
        "kind": "value"
      }
    ]
  },
  "media-asset-pack": {
    "graph_format": 2,
    "workflow": "media-asset-pack-template",
    "nodes": [
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/qwen2.5:14b",
        "permits": []
      },
      {
        "id": "render",
        "verb": "invoke",
        "tool": "nika:image_generate",
        "permits": [
          "tool: nika:image_generate"
        ]
      },
      {
        "id": "manifest",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "persist",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "brief",
        "to": "manifest",
        "kind": "value"
      },
      {
        "from": "brief",
        "to": "render",
        "kind": "value"
      },
      {
        "from": "manifest",
        "to": "persist",
        "kind": "value"
      },
      {
        "from": "render",
        "to": "manifest",
        "kind": "value"
      }
    ]
  },
  "meeting-actions": {
    "graph_format": 2,
    "workflow": "meeting-actions",
    "nodes": [
      {
        "id": "transcript",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "extract",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/action-items.json",
          "tool: nika:write"
        ]
      },
      {
        "id": "trace",
        "verb": "invoke",
        "tool": "nika:log",
        "permits": [
          "tool: nika:log"
        ]
      }
    ],
    "edges": [
      {
        "from": "extract",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "extract",
        "to": "trace",
        "kind": "control"
      },
      {
        "from": "transcript",
        "to": "extract",
        "kind": "value"
      }
    ]
  },
  "model-bench": {
    "graph_format": 2,
    "workflow": "model-bench",
    "nodes": [
      {
        "id": "ask_incumbent",
        "verb": "infer",
        "model": "ollama/qwen2.5:14b",
        "permits": []
      },
      {
        "id": "ask_challenger",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "ask_tiny",
        "verb": "infer",
        "model": "ollama/qwen2.5:0.5b",
        "permits": []
      },
      {
        "id": "tabulate",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "persist",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/model-bench.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "ask_challenger",
        "to": "tabulate",
        "kind": "terminal-observation"
      },
      {
        "from": "ask_challenger",
        "to": "tabulate",
        "kind": "value"
      },
      {
        "from": "ask_incumbent",
        "to": "tabulate",
        "kind": "terminal-observation"
      },
      {
        "from": "ask_incumbent",
        "to": "tabulate",
        "kind": "value"
      },
      {
        "from": "ask_tiny",
        "to": "tabulate",
        "kind": "terminal-observation"
      },
      {
        "from": "ask_tiny",
        "to": "tabulate",
        "kind": "value"
      },
      {
        "from": "tabulate",
        "to": "persist",
        "kind": "value"
      }
    ]
  },
  "og-images": {
    "graph_format": 2,
    "workflow": "og-images",
    "nodes": [
      {
        "id": "hero",
        "verb": "invoke",
        "tool": "nika:image_generate",
        "permits": [
          "fs.write: out/og/**",
          "tool: nika:image_generate"
        ]
      }
    ],
    "edges": []
  },
  "pr-review-fanout": {
    "graph_format": 2,
    "workflow": "pr-review-fanout",
    "nodes": [
      {
        "id": "changed",
        "verb": "exec",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "todo_sweep",
        "verb": "invoke",
        "tool": "nika:grep",
        "permits": [
          "fs.read: ./src/**",
          "tool: nika:grep"
        ]
      },
      {
        "id": "files",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "reviews",
        "verb": "agent",
        "model": "ollama/qwen3.5:4b",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:done",
          "tool: nika:read"
        ]
      },
      {
        "id": "merged",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "summary",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: ./REVIEW.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "changed",
        "to": "files",
        "kind": "value"
      },
      {
        "from": "files",
        "to": "reviews",
        "kind": "value"
      },
      {
        "from": "merged",
        "to": "summary",
        "kind": "value"
      },
      {
        "from": "reviews",
        "to": "merged",
        "kind": "value"
      },
      {
        "from": "summary",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "todo_sweep",
        "to": "summary",
        "kind": "value"
      }
    ]
  },
  "pr-risk-review": {
    "graph_format": 2,
    "workflow": "pr-risk-review",
    "nodes": [
      {
        "id": "diff",
        "verb": "exec",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "risk",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "probe",
        "verb": "agent",
        "model": "ollama/llama3.2:3b",
        "when": "${{ with.score >= 7 }}",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "report",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: ./review.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "diff",
        "to": "risk",
        "kind": "value"
      },
      {
        "from": "risk",
        "to": "probe",
        "kind": "value"
      },
      {
        "from": "risk",
        "to": "probe",
        "kind": "value"
      },
      {
        "from": "risk",
        "to": "report",
        "kind": "value"
      }
    ]
  },
  "price-watch": {
    "graph_format": 2,
    "workflow": "price-watch",
    "nodes": [
      {
        "id": "check",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "alert",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ with.price < const.alert_below }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "check",
        "to": "alert",
        "kind": "value"
      },
      {
        "from": "check",
        "to": "alert",
        "kind": "value"
      }
    ]
  },
  "release-notes": {
    "graph_format": 2,
    "workflow": "release-notes",
    "nodes": [
      {
        "id": "history",
        "verb": "exec",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "existing",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "notes",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "copy",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "changelog",
        "verb": "invoke",
        "tool": "nika:edit",
        "permits": [
          "tool: nika:edit"
        ]
      },
      {
        "id": "announce",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ inputs.announce == true }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "changelog",
        "to": "announce",
        "kind": "control"
      },
      {
        "from": "copy",
        "to": "changelog",
        "kind": "control"
      },
      {
        "from": "existing",
        "to": "copy",
        "kind": "value"
      },
      {
        "from": "history",
        "to": "notes",
        "kind": "value"
      },
      {
        "from": "notes",
        "to": "announce",
        "kind": "value"
      },
      {
        "from": "notes",
        "to": "changelog",
        "kind": "value"
      },
      {
        "from": "notes",
        "to": "changelog",
        "kind": "value"
      }
    ]
  },
  "release-radar": {
    "graph_format": 2,
    "workflow": "release-radar",
    "nodes": [
      {
        "id": "no_state",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "previous",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "feed",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "fresh",
        "verb": "invoke",
        "tool": "nika:json_diff",
        "permits": [
          "tool: nika:json_diff"
        ]
      },
      {
        "id": "save_state",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "digest",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ size(with.fresh) > 0 }}",
        "permits": []
      }
    ],
    "edges": [
      {
        "from": "feed",
        "to": "digest",
        "kind": "value"
      },
      {
        "from": "feed",
        "to": "fresh",
        "kind": "value"
      },
      {
        "from": "feed",
        "to": "save_state",
        "kind": "value"
      },
      {
        "from": "fresh",
        "to": "digest",
        "kind": "value"
      },
      {
        "from": "no_state",
        "to": "previous",
        "kind": "recovery"
      },
      {
        "from": "previous",
        "to": "fresh",
        "kind": "value"
      }
    ]
  },
  "release-train": {
    "graph_format": 2,
    "workflow": "release-train",
    "nodes": [
      {
        "id": "t0",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "declared",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./VERSION",
          "tool: nika:read"
        ]
      },
      {
        "id": "notes",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./CHANGELOG.md",
          "tool: nika:read"
        ]
      },
      {
        "id": "schema",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "fs.read: ./schemas/workflow.schema.json",
          "tool: nika:read"
        ]
      },
      {
        "id": "board",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "gates_green",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      },
      {
        "id": "t1",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "gate_time",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "conductor",
        "verb": "invoke",
        "tool": "nika:prompt",
        "permits": [
          "tool: nika:prompt"
        ]
      },
      {
        "id": "signed_at",
        "verb": "invoke",
        "tool": "nika:date",
        "when": "${{ with.signed == true }}",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "window",
        "verb": "invoke",
        "tool": "nika:date",
        "when": "${{ with.at != null }}",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "hold",
        "verb": "invoke",
        "tool": "nika:wait",
        "when": "${{ with.window != null }}",
        "permits": [
          "tool: nika:wait"
        ]
      },
      {
        "id": "ship",
        "verb": "exec",
        "when": "${{ with.depart == true }}",
        "permits": [
          "exec: ./scripts/release.sh"
        ]
      },
      {
        "id": "verify",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "net.http: api.example.com",
          "tool: nika:fetch"
        ]
      },
      {
        "id": "live",
        "verb": "invoke",
        "tool": "nika:assert",
        "permits": [
          "tool: nika:assert"
        ]
      },
      {
        "id": "record",
        "verb": "invoke",
        "tool": "nika:emit",
        "permits": [
          "tool: nika:emit"
        ]
      }
    ],
    "edges": [
      {
        "from": "board",
        "to": "conductor",
        "kind": "value"
      },
      {
        "from": "board",
        "to": "gates_green",
        "kind": "value"
      },
      {
        "from": "conductor",
        "to": "signed_at",
        "kind": "value"
      },
      {
        "from": "declared",
        "to": "board",
        "kind": "value"
      },
      {
        "from": "gate_time",
        "to": "conductor",
        "kind": "value"
      },
      {
        "from": "gates_green",
        "to": "t1",
        "kind": "control"
      },
      {
        "from": "hold",
        "to": "ship",
        "kind": "control"
      },
      {
        "from": "live",
        "to": "record",
        "kind": "control"
      },
      {
        "from": "live",
        "to": "record",
        "kind": "terminal-observation"
      },
      {
        "from": "notes",
        "to": "board",
        "kind": "value"
      },
      {
        "from": "schema",
        "to": "board",
        "kind": "value"
      },
      {
        "from": "ship",
        "to": "verify",
        "kind": "control"
      },
      {
        "from": "signed_at",
        "to": "window",
        "kind": "value"
      },
      {
        "from": "t0",
        "to": "gate_time",
        "kind": "value"
      },
      {
        "from": "t1",
        "to": "gate_time",
        "kind": "value"
      },
      {
        "from": "verify",
        "to": "live",
        "kind": "value"
      },
      {
        "from": "window",
        "to": "hold",
        "kind": "value"
      }
    ]
  },
  "resume-screener": {
    "graph_format": 2,
    "workflow": "resume-screener",
    "nodes": [
      {
        "id": "pool",
        "verb": "invoke",
        "tool": "nika:glob",
        "permits": [
          "tool: nika:glob"
        ]
      },
      {
        "id": "cvs",
        "verb": "invoke",
        "tool": "nika:read",
        "fan_out": {
          "kind": "expression"
        },
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "pairs",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "screened",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "fan_out": {
          "kind": "expression"
        },
        "permits": []
      },
      {
        "id": "ranked",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "shortlist",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "when": "${{ size(with.shortlist) > 0 }}",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "when": "${{ with.brief != null }}",
        "permits": [
          "fs.write: ./hiring/shortlist-brief.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "brief",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "cvs",
        "to": "pairs",
        "kind": "value"
      },
      {
        "from": "pairs",
        "to": "screened",
        "kind": "value"
      },
      {
        "from": "pool",
        "to": "cvs",
        "kind": "value"
      },
      {
        "from": "pool",
        "to": "pairs",
        "kind": "value"
      },
      {
        "from": "ranked",
        "to": "shortlist",
        "kind": "value"
      },
      {
        "from": "screened",
        "to": "ranked",
        "kind": "value"
      },
      {
        "from": "shortlist",
        "to": "brief",
        "kind": "value"
      }
    ]
  },
  "seo-content-brief": {
    "graph_format": 2,
    "workflow": "seo-content-brief",
    "nodes": [
      {
        "id": "map",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "top_page",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "brief",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "map",
        "to": "brief",
        "kind": "value"
      },
      {
        "from": "map",
        "to": "top_page",
        "kind": "value"
      },
      {
        "from": "top_page",
        "to": "brief",
        "kind": "value"
      }
    ]
  },
  "social-repurpose": {
    "graph_format": 2,
    "workflow": "social-repurpose",
    "nodes": [
      {
        "id": "post",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "thread",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "linkedin",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "newsletter",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "bundle",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/social-bundle.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "linkedin",
        "to": "bundle",
        "kind": "value"
      },
      {
        "from": "newsletter",
        "to": "bundle",
        "kind": "value"
      },
      {
        "from": "post",
        "to": "linkedin",
        "kind": "value"
      },
      {
        "from": "post",
        "to": "newsletter",
        "kind": "value"
      },
      {
        "from": "post",
        "to": "thread",
        "kind": "value"
      },
      {
        "from": "thread",
        "to": "bundle",
        "kind": "value"
      }
    ]
  },
  "standup-digest": {
    "graph_format": 2,
    "workflow": "standup-digest",
    "nodes": [
      {
        "id": "today",
        "verb": "invoke",
        "tool": "nika:date",
        "permits": [
          "tool: nika:date"
        ]
      },
      {
        "id": "history",
        "verb": "exec",
        "permits": [
          "exec: git"
        ]
      },
      {
        "id": "digest",
        "verb": "infer",
        "model": "ollama/qwen3.5:4b",
        "permits": []
      },
      {
        "id": "save",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/standup-note.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "digest",
        "to": "save",
        "kind": "value"
      },
      {
        "from": "history",
        "to": "digest",
        "kind": "value"
      },
      {
        "from": "today",
        "to": "digest",
        "kind": "value"
      }
    ]
  },
  "support-triage": {
    "graph_format": 2,
    "workflow": "support-triage",
    "nodes": [
      {
        "id": "batch",
        "verb": "invoke",
        "tool": "nika:uuid",
        "permits": [
          "tool: nika:uuid"
        ]
      },
      {
        "id": "queue",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "triage",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "urgent",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "board",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      },
      {
        "id": "escalate",
        "verb": "invoke",
        "tool": "nika:notify",
        "when": "${{ size(with.urgent) > 0 }}",
        "permits": [
          "tool: nika:notify"
        ]
      }
    ],
    "edges": [
      {
        "from": "batch",
        "to": "board",
        "kind": "value"
      },
      {
        "from": "batch",
        "to": "escalate",
        "kind": "value"
      },
      {
        "from": "queue",
        "to": "triage",
        "kind": "value"
      },
      {
        "from": "triage",
        "to": "board",
        "kind": "value"
      },
      {
        "from": "triage",
        "to": "urgent",
        "kind": "value"
      },
      {
        "from": "urgent",
        "to": "escalate",
        "kind": "value"
      }
    ]
  },
  "transcript-shownotes": {
    "graph_format": 2,
    "workflow": "transcript-shownotes",
    "nodes": [
      {
        "id": "raw",
        "verb": "invoke",
        "tool": "nika:read",
        "permits": [
          "tool: nika:read"
        ]
      },
      {
        "id": "notes",
        "verb": "infer",
        "model": "ollama/llama3.2:3b",
        "permits": []
      },
      {
        "id": "sections",
        "verb": "invoke",
        "tool": "nika:jq",
        "permits": [
          "tool: nika:jq"
        ]
      },
      {
        "id": "page",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "fs.write: out/show-notes.md",
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "notes",
        "to": "page",
        "kind": "value"
      },
      {
        "from": "notes",
        "to": "sections",
        "kind": "value"
      },
      {
        "from": "raw",
        "to": "notes",
        "kind": "value"
      },
      {
        "from": "sections",
        "to": "page",
        "kind": "value"
      },
      {
        "from": "sections",
        "to": "page",
        "kind": "value"
      }
    ]
  },
  "website-brief": {
    "graph_format": 2,
    "workflow": "website-brief-template",
    "nodes": [
      {
        "id": "crawl_site",
        "verb": "invoke",
        "tool": "nika:fetch",
        "permits": [
          "tool: nika:fetch"
        ]
      },
      {
        "id": "brief",
        "verb": "infer",
        "model": "ollama/qwen2.5:14b",
        "permits": []
      },
      {
        "id": "persist",
        "verb": "invoke",
        "tool": "nika:write",
        "permits": [
          "tool: nika:write"
        ]
      }
    ],
    "edges": [
      {
        "from": "brief",
        "to": "persist",
        "kind": "value"
      },
      {
        "from": "crawl_site",
        "to": "brief",
        "kind": "value"
      }
    ]
  }
}
