// atlas-meta.generated.ts — AUTO-GENERATED by scripts/atlas/build-atlas.mjs from
// scripts/atlas/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/atlas/build-atlas.mjs
// Drift gate: src/test/atlas.test.ts recompiles and byte-diffs.

/** chrome-safe: provenance + counts only — the full graph stays lazy
 * (atlas.generated.ts) so the initial bundle never pays for it. */
export const ATLAS_PROVENANCE: {
  language_graph: 1
  /** stamped by the resync cron from its fresh spec clone · null until then */
  spec_pin: string | null
  canon_schema_version: number
  engine_version: string
  catalogs: { tools: string; providers: string }
} = {
  "language_graph": 1,
  "spec_pin": null,
  "canon_schema_version": 1,
  "engine_version": "v0.103.0",
  "catalogs": {
    "tools": "0.99.0",
    "providers": "0.99.0"
  }
}

export const ATLAS_SET_COUNTS: Record<string, { count: number; url: string; title: string }> =
  {
  "builtins": {
    "count": 28,
    "url": "/tools",
    "title": "The standard library"
  },
  "conformance-levels": {
    "count": 3,
    "url": "/proof",
    "title": "The conformance levels"
  },
  "edge-kinds": {
    "count": 6,
    "url": "/flow",
    "title": "The edge kinds"
  },
  "error-categories": {
    "count": 12,
    "url": "/errors",
    "title": "The error categories"
  },
  "error-codes": {
    "count": 82,
    "url": "/errors",
    "title": "The error codes"
  },
  "error-namespaces": {
    "count": 21,
    "url": "/errors",
    "title": "The error namespaces"
  },
  "extract-modes": {
    "count": 9,
    "url": "/tools/fetch",
    "title": "The extract modes"
  },
  "gate-predicates": {
    "count": 4,
    "url": "/flow",
    "title": "The gate predicates"
  },
  "mcp-tools": {
    "count": 9,
    "url": "/proof",
    "title": "The oracle tools"
  },
  "namespaces": {
    "count": 5,
    "url": "/language",
    "title": "The namespaces"
  },
  "permit-families": {
    "count": 4,
    "url": "/boundary",
    "title": "The permit families"
  },
  "providers": {
    "count": 16,
    "url": "/providers",
    "title": "The providers"
  },
  "secret-sources": {
    "count": 3,
    "url": "/boundary",
    "title": "The secret sources"
  },
  "showcases": {
    "count": 26,
    "url": "/proof",
    "title": "The showcases"
  },
  "templates": {
    "count": 10,
    "url": "/tools",
    "title": "The templates"
  },
  "tool-families": {
    "count": 6,
    "url": "/tools",
    "title": "The tool families"
  },
  "truth-words": {
    "count": 10,
    "url": "/sources",
    "title": "The truth words"
  },
  "types": {
    "count": 0,
    "url": "/language",
    "title": "The types"
  },
  "verbs": {
    "count": 4,
    "url": "/verbs",
    "title": "The four verbs"
  },
  "words": {
    "count": 57,
    "url": "/language",
    "title": "The language words"
  }
}

export const ATLAS_HUBS = [
  {
    "id": "shape",
    "title": "The shape",
    "hub": "/language",
    "exists": true,
    "lands": null
  },
  {
    "id": "flow",
    "title": "The flow",
    "hub": "/flow",
    "exists": true,
    "lands": null
  },
  {
    "id": "acts",
    "title": "The acts",
    "hub": "/verbs",
    "exists": true,
    "lands": null
  },
  {
    "id": "reach",
    "title": "The reach",
    "hub": "/tools",
    "exists": true,
    "lands": null
  },
  {
    "id": "boundary",
    "title": "The boundary",
    "hub": "/boundary",
    "exists": true,
    "lands": null
  },
  {
    "id": "refusals",
    "title": "The refusals",
    "hub": "/errors",
    "exists": true,
    "lands": null
  },
  {
    "id": "proof",
    "title": "The proof",
    "hub": "/proof",
    "exists": true,
    "lands": null
  }
] as const

export const ATLAS_SCORE = {
  "score": 100,
  "waived": [
    "showcases: rooms land in WO-5 · until then the /use-cases hub carries every member (galerie) · waiver dies with WO-5",
    "truth-words: /sources lands in WO-7 · the meta-set ships with it · waiver dies with WO-7"
  ],
  "unarmed": [
    "capture-stamps → arms at wo-4 (TermCapture)",
    "count-links (CanonCount deployment) → arms at wo-3",
    "keyboard+touch verdicts → arm at wo-12",
    "hreflang coverage → arms at wo-9"
  ]
} as const

/** the two clocks diffed (computed at compile · /map renders the line) */
export const ATLAS_CLOCK_DIFF: Record<'builtins' | 'providers', { ratified_only: string[]; shipped_only: string[] }> =
  {
  "builtins": {
    "ratified_only": [],
    "shipped_only": []
  },
  "providers": {
    "ratified_only": [],
    "shipped_only": []
  }
}

/** flips when /sources ships (WO-7) — TruthLine withholds the link until then */
export const SOURCES_LIVE = false
