/* AUTO-GENERATED by scripts/build-blog.mjs from content/blog/*.md — NEVER EDIT.
   Regenerate: node scripts/build-blog.mjs (the vitest drift gate recompiles + diffs). */

export interface BlogInline {
  k: 'text' | 'strong' | 'em' | 'code' | 'link'
  text: string
  href?: string
}

export type BlogToken =
  | { k: 'p'; inline: BlogInline[] }
  | { k: 'h'; depth: number; text: string; id: string }
  | { k: 'code'; lang: string; filename?: string; text: string }
  | { k: 'quote'; inline: BlogInline[] }
  | { k: 'list'; ordered: boolean; items: BlogInline[][] }
  | { k: 'hr' }

export interface BlogPost {
  slug: string
  /** the source file under content/blog/ — the GitHub edit target */
  file: string
  title: string
  tag: string
  date: string
  description: string
  readingMin: number
  tokens: BlogToken[]
}

/* newest first */
export const BLOG_POSTS: BlogPost[] = [
  {
    "slug": "the-trace-you-can-replay",
    "file": "2026-07-05-the-trace-you-can-replay.md",
    "title": "The trace you can replay",
    "tag": "Engine",
    "date": "2026-07-05",
    "description": "Every run leaves a flight recorder: a deterministic AI audit trail you can replay like a film, never re-execute by accident.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Ask most AI tooling what happened during a run and you get logs: interleaved, truncated, gone at the next rotation. Ask what "
          },
          {
            "k": "em",
            "text": "exactly"
          },
          {
            "k": "text",
            "text": " happened, in what order, at what cost, and the honest answer is usually a shrug."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Nika treats the question as part of the product. Every run can leave a "
          },
          {
            "k": "strong",
            "text": "flight recorder"
          },
          {
            "k": "text",
            "text": ": a stream of typed events, one JSON object per line, from "
          },
          {
            "k": "code",
            "text": "workflow_started"
          },
          {
            "k": "text",
            "text": " to the final verdict."
          }
        ]
      },
      {
        "k": "code",
        "lang": "text",
        "text": "❯ nika run daily-brief.nika.yaml --json > run.ndjson"
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "That file is the audit trail. Plain NDJSON on your disk: each event carries its id, timestamp, kind ("
          },
          {
            "k": "code",
            "text": "task_scheduled"
          },
          {
            "k": "text",
            "text": ", "
          },
          {
            "k": "code",
            "text": "task_started"
          },
          {
            "k": "text",
            "text": ", "
          },
          {
            "k": "code",
            "text": "task_finished"
          },
          {
            "k": "text",
            "text": "…) and typed fields. It is greppable, diffable, versionable: the same properties the workflow file itself has, extended to what the workflow "
          },
          {
            "k": "em",
            "text": "did"
          },
          {
            "k": "text",
            "text": "."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "And then the part that makes it a recorder rather than a log:"
          }
        ]
      },
      {
        "k": "code",
        "lang": "text",
        "text": "❯ nika trace replay run.ndjson"
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The run plays back "
          },
          {
            "k": "strong",
            "text": "live"
          },
          {
            "k": "text",
            "text": ", in the same renderer as the original: the plan, the waves lighting up, the verdict card. The engine's own help text states the law in five words: "
          },
          {
            "k": "em",
            "text": "replay = re-render, NEVER re-execute"
          },
          {
            "k": "text",
            "text": ". Watching a trace can not fire a request, write a file, or spend a token. The recorder is read-only by construction, which is what makes it safe to hand to a colleague, attach to an incident, or open six months later."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "code",
            "text": "nika trace show"
          },
          {
            "k": "text",
            "text": " prints just the final card when you only need the verdict."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Why this matters compounds with everything else in the file:"
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Same file, same steps, same order."
          },
          {
            "k": "text",
            "text": " The plan is derived from "
          },
          {
            "k": "code",
            "text": "depends_on"
          },
          {
            "k": "text",
            "text": " before anything runs, so two runs of the same file schedule identically. The trace makes that claim checkable: run it again, record it again, and diff the two NDJSON files like code. Determinism stops being a promise and becomes a property you can verify with tools you already have."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The boundary is in the recording."
          },
          {
            "k": "text",
            "text": " The trace opens by stating the permits context the run started under. An auditor reading the file sees not only what happened but what was "
          },
          {
            "k": "em",
            "text": "allowed"
          },
          {
            "k": "text",
            "text": " to happen: the blast radius and the actions, in one artifact."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "It closes the loop the site keeps drawing."
          },
          {
            "k": "text",
            "text": " The workflow is a file you review before it runs. The trace is a file you review after it ran. Between the two, there is no moment where the work lives only in someone's scrollback."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Chats evaporate. Files compound. It turns out that holds for the runs, too."
          }
        ]
      }
    ]
  },
  {
    "slug": "own-your-stack",
    "file": "2026-07-02-own-your-stack.md",
    "title": "No cloud needed",
    "tag": "Sovereignty",
    "date": "2026-07-02",
    "description": "One Rust binary, your models, your files. Run LLMs locally and see what local-first actually buys you.",
    "readingMin": 1,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Local-first gets said a lot, and it means anything from \"we cache\" to \"we sync, eventually\". Here is what it means in Nika, concretely."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The engine is one Rust binary."
          },
          {
            "k": "text",
            "text": " No daemon, no account, no telemetry phoning home. Brew or curl, and the whole runtime is on your disk. Air-gapped is a supported install path, not an afterthought."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "5 of the 16 model providers are local runtimes"
          },
          {
            "k": "text",
            "text": ": Ollama, LM Studio, llama.cpp, LocalAI, vLLM. The model is one line of the file; swap it and nothing else changes."
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "hello-ai.nika.yaml",
        "text": "nika: v1\nworkflow: hello-ai\nmodel: ollama/llama3.2:3b\n\ntasks:\n  - id: greet\n    infer:\n      prompt: \"Say hello in one sentence.\""
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "What that buys, concretely. "
          },
          {
            "k": "strong",
            "text": "Privacy that is structural, not contractual"
          },
          {
            "k": "text",
            "text": ": with a local model the data path never leaves the machine, so there is nothing to trust and nothing to audit. "
          },
          {
            "k": "strong",
            "text": "A free drafting loop"
          },
          {
            "k": "text",
            "text": ": iterate on prompts and plans at zero marginal cost, then point the same file at a bigger model only when the task earns it. "
          },
          {
            "k": "strong",
            "text": "Custody"
          },
          {
            "k": "text",
            "text": ": a provider deprecating a model is a one-line edit to your file, not a rewrite of your workflow."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Cloud stays a real choice: 10 cloud providers, bring your own keys, and every key stays yours. The point was never no-cloud. The point is that cloud is "
          },
          {
            "k": "strong",
            "text": "optional"
          },
          {
            "k": "text",
            "text": ": per file, per task, visible in the diff."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Your first run needs no key at all. That is not a trial mode. That is the architecture."
          }
        ]
      }
    ]
  },
  {
    "slug": "dag-for-free",
    "file": "2026-06-29-dag-for-free.md",
    "title": "The plan you get for free",
    "tag": "Engine",
    "date": "2026-06-29",
    "description": "depends_on is all you write. The orchestration falls out of the graph: parallel waves, drawn before anything runs.",
    "readingMin": 1,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Every orchestration tool eventually grows a scheduler dialect: stages, barriers, fan-in nodes, retry graphs. You learn its vocabulary, you maintain its diagrams, and one day the diagram and the code disagree."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Nika has one word: depends_on."
          },
          {
            "k": "text",
            "text": " A task lists what it waits for. That is the entire scheduling surface. Everything else is derived: tasks whose dependencies are met run together, waves form on their own, and your file's maximum parallelism is a fact the engine computes, not a number you tune."
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "release-radar.nika.yaml",
        "text": "nika: v1\nworkflow: release-radar\n\ntasks:\n  - id: changelog\n    invoke:\n      tool: \"nika:fetch\"\n      args:\n        url: \"https://nika.sh/changelog\"\n\n  - id: repo_log\n    exec:\n      command: \"git log --since='1 week'\"\n\n  - id: digest\n    depends_on: [changelog, repo_log]\n    infer:\n      prompt: \"What changed this week: ${{ tasks.changelog.output }} ${{ tasks.repo_log.output }}\""
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Nothing in that file says parallel. "
          },
          {
            "k": "code",
            "text": "changelog"
          },
          {
            "k": "text",
            "text": " and "
          },
          {
            "k": "code",
            "text": "repo_log"
          },
          {
            "k": "text",
            "text": " start together because nothing orders them; "
          },
          {
            "k": "code",
            "text": "digest"
          },
          {
            "k": "text",
            "text": " waits because it says so. Add a third source tomorrow and the plan redraws itself: no stage to renumber, no barrier to move."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The plan is also drawn "
          },
          {
            "k": "strong",
            "text": "before anything runs"
          },
          {
            "k": "text",
            "text": ". It is the first verdict "
          },
          {
            "k": "code",
            "text": "nika check"
          },
          {
            "k": "text",
            "text": " prints for that exact file:"
          }
        ]
      },
      {
        "k": "code",
        "lang": "text",
        "text": " ✔ PLAN     2 wave(s) · 3 task(s) · max parallelism 2"
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "A cycle is not a hang, it is a typed error naming its members. A ghost name in "
          },
          {
            "k": "code",
            "text": "depends_on"
          },
          {
            "k": "text",
            "text": " is caught in the same pass. The graph the engine runs is the graph you read, and both come from three verbs and a list."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "You never scheduled anything. The plan was in the file all along."
          }
        ]
      }
    ]
  },
  {
    "slug": "four-verbs",
    "file": "2026-06-22-four-verbs.md",
    "title": "Four verbs are enough",
    "tag": "Language",
    "date": "2026-06-22",
    "description": "A verb is a distinct execution model, not a feature. Why the language locks at four, forever.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Every workflow language faces the same temptation: keep adding verbs. A verb for HTTP. A verb for files. A verb for email, for SQL, for whatever last week's integration needed. Ten years later the language is a catalog nobody can hold in their head, and every file is written in a different dialect of it."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Nika locks the count at four, forever. The rule that makes this possible is strict: "
          },
          {
            "k": "strong",
            "text": "a verb is a distinct execution model"
          },
          {
            "k": "text",
            "text": ", not a feature. "
          },
          {
            "k": "strong",
            "text": "infer"
          },
          {
            "k": "text",
            "text": " generates with a model. "
          },
          {
            "k": "strong",
            "text": "exec"
          },
          {
            "k": "text",
            "text": " runs a process. "
          },
          {
            "k": "strong",
            "text": "invoke"
          },
          {
            "k": "text",
            "text": " calls a tool and returns. "
          },
          {
            "k": "strong",
            "text": "agent"
          },
          {
            "k": "text",
            "text": " loops with tools until the job is done. Four genuinely different ways for a machine to act. There is no fifth."
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "morning-brief.nika.yaml",
        "text": "nika: v1\nworkflow: morning-brief\n\ntasks:\n  - id: fetch_news\n    invoke:\n      tool: \"nika:fetch\"          # a tool, not a verb\n      args:\n        url: \"https://hnrss.org/frontpage\"\n\n  - id: build\n    exec:\n      command: \"cargo build --release\"\n\n  - id: digest\n    depends_on: [fetch_news, build]\n    infer:\n      prompt: \"Summarize what changed\"\n\noutputs:\n  brief: ${{ tasks.digest.output }}"
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The test case was fetch. Surely getting a web page deserves its own verb? It does not, and the reason is the whole design: "
          },
          {
            "k": "strong",
            "text": "fetching is not a distinct execution model."
          },
          {
            "k": "text",
            "text": " It is a tool call. So "
          },
          {
            "k": "code",
            "text": "nika:fetch"
          },
          {
            "k": "text",
            "text": " lives in the standard library, reached through invoke, next to read, write, jq and the other 19 builtins. Everything callable is a tool. Everything about ordering is the graph."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "A closed language is a feature you can feel. You can finish learning it: four words and the file reads like prose. Your files never rot into an old dialect, because there is no new dialect coming. And tools keep growing where growth belongs, in the library: a new builtin, a new tool server (MCP), a new provider. The language holds still while the toolbelt expands."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "That stillness is the promise. The file you write today is the file you run in ten years. Languages that stop moving are the ones you can build on."
          }
        ]
      }
    ]
  },
  {
    "slug": "intent-as-code",
    "file": "2026-06-15-intent-as-code.md",
    "title": "Intent as Code: why your AI work should be a file",
    "tag": "Manifesto",
    "date": "2026-06-15",
    "description": "Chats evaporate, files compound. The case for writing AI work down as source you own: your best prompts, versioned like code.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Think about the best thing you did with an AI last month. The careful prompt, the back-and-forth, the result that finally clicked. "
          },
          {
            "k": "strong",
            "text": "Where is it now?"
          },
          {
            "k": "text",
            "text": " For most people the honest answer is: gone. Buried in a chat history you will never scroll back through, on a server you don't control."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "We've accepted a strange deal: the more useful the work, the more disposable the container. Nobody would write software in a text box that forgets everything. Yet that's exactly how most AI work happens today."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Nika's bet is simple: useful AI work is worth writing down."
          },
          {
            "k": "text",
            "text": " Not as a transcript, as "
          },
          {
            "k": "em",
            "text": "source"
          },
          {
            "k": "text",
            "text": ". A small YAML file that says what you want: fetch this, think about that, run this command, save the result. The file is the workflow. Run it again tomorrow and it does the same thing. Change a line and "
          },
          {
            "k": "code",
            "text": "git diff"
          },
          {
            "k": "text",
            "text": " shows exactly what changed."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Four verbs cover the whole space: "
          },
          {
            "k": "strong",
            "text": "infer"
          },
          {
            "k": "text",
            "text": " (call a model), "
          },
          {
            "k": "strong",
            "text": "exec"
          },
          {
            "k": "text",
            "text": " (run a process), "
          },
          {
            "k": "strong",
            "text": "invoke"
          },
          {
            "k": "text",
            "text": " (use a tool), "
          },
          {
            "k": "strong",
            "text": "agent"
          },
          {
            "k": "text",
            "text": " (let it work a loop). Everything else is data flowing between tasks. The order falls out of the dependencies. Write "
          },
          {
            "k": "code",
            "text": "depends_on"
          },
          {
            "k": "text",
            "text": " and independent branches run in parallel, for free."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "And it runs on "
          },
          {
            "k": "strong",
            "text": "your machine"
          },
          {
            "k": "text",
            "text": ". One Rust binary. Your model keys, your files, your git history. No cloud between you and your own work, and a license (AGPL) that guarantees it stays that way."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Chat is a great place to "
          },
          {
            "k": "em",
            "text": "figure out"
          },
          {
            "k": "text",
            "text": " what you want. It is a terrible place to "
          },
          {
            "k": "em",
            "text": "keep"
          },
          {
            "k": "text",
            "text": " it. Explore in chat. Then write the intent down, and own it forever."
          }
        ]
      }
    ]
  },
  {
    "slug": "blast-radius-in-the-file",
    "file": "2026-06-04-blast-radius-in-the-file.md",
    "title": "The blast radius is part of the file",
    "tag": "Security",
    "date": "2026-06-04",
    "description": "permits: is the whole list, guardrails an agent can't talk past. Everything not on it is denied before it runs, with a named error.",
    "readingMin": 1,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Ask an agent framework what its agent may touch, and the honest answer is usually: whatever the process may touch. The permission model is the operating system's, the audit is a log file, and the log is written after the damage."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "In Nika, the boundary is a block in the file you review:"
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "daily-brief.nika.yaml",
        "text": "nika: v1\nworkflow: daily-brief\n\npermits:\n  fs:\n    read: [ ./notes/* ]\n    write: [ ./brief.md ]\n  tools: [ \"nika:read\", \"nika:write\" ]\n\ntasks:\n  - id: notes\n    invoke:\n      tool: \"nika:read\"\n      args:\n        path: ./notes/today.md\n\n  - id: save\n    depends_on: [notes]\n    invoke:\n      tool: \"nika:write\"\n      args:\n        path: ./brief.md\n        content: \"${{ tasks.notes.output }}\""
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "permits: is the whole list."
          },
          {
            "k": "text",
            "text": " Not a suggestion, not a default profile. Once the block is present, every category is default-deny: which files it may read and write, which tools it may call, which programs, which hosts. A reviewer reads the blast radius in the diff, right next to the logic it serves."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Denied means before."
          },
          {
            "k": "text",
            "text": " A step that reaches outside the list fails with a typed error, "
          },
          {
            "k": "code",
            "text": "NIKA-SEC-004"
          },
          {
            "k": "text",
            "text": ", before the effect happens. Not logged after the fact, not flagged for Monday's incident review: the write to "
          },
          {
            "k": "code",
            "text": "~/.ssh/config"
          },
          {
            "k": "text",
            "text": " simply never runs."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "And you do not hand-write the list. "
          },
          {
            "k": "code",
            "text": "nika check --infer-permits"
          },
          {
            "k": "text",
            "text": " reads the plan and prints the tightest boundary it needs. You loosen it deliberately, line by line, in review, which is where loosening belongs."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Capability declarations next to intent. It is one of the oldest ideas in security, applied to the newest way of doing work."
          }
        ]
      }
    ]
  },
  {
    "slug": "standard-library-not-plugin-store",
    "file": "2026-05-14-standard-library-not-plugin-store.md",
    "title": "A standard library, not a plugin store",
    "tag": "Language",
    "date": "2026-05-14",
    "description": "23 builtins in the binary, allow-listed, nothing to install. The library grows, the language holds still.",
    "readingMin": 1,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "A workflow language lives or dies on its tools, and the industry default is a marketplace: search, install, and trust someone's package with your filesystem. We shipped a standard library instead."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "23 builtins ride the binary"
          },
          {
            "k": "text",
            "text": ", across four families: files, data, web, flow. Read, write, fetch, jq and their siblings. They are reached the same way as everything else callable, with "
          },
          {
            "k": "code",
            "text": "invoke:"
          },
          {
            "k": "text",
            "text": ", they are versioned with the engine, and there is nothing to install. Nothing to install also means nothing to typosquat, no postinstall script, no supply chain roulette on a Tuesday."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "One builtin, 9 honest shapes."
          },
          {
            "k": "text",
            "text": " "
          },
          {
            "k": "code",
            "text": "nika:fetch"
          },
          {
            "k": "text",
            "text": " turns a page into typed output nine ways: article, markdown, text, links, metadata, selector, sitemap, feed, jq. Read-only by design. The point is not the feature count. The point is that a fetch inside a reviewed file has a declared, typed result, so the step after it knows exactly what it is holding."
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "headlines.nika.yaml",
        "text": "nika: v1\nworkflow: headlines\n\ntasks:\n  - id: page\n    invoke:\n      tool: \"nika:fetch\"\n      args:\n        url: \"https://nika.sh\"\n\n  - id: save\n    depends_on: [page]\n    invoke:\n      tool: \"nika:write\"\n      args:\n        path: \"./page.md\"\n        content: \"${{ tasks.page.output }}\""
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Everything beyond the library arrives through MCP: name a "
          },
          {
            "k": "code",
            "text": "mcp:"
          },
          {
            "k": "text",
            "text": " tool id and any server you already run is reachable, but only if the file allow-lists it. Growth belongs in the toolbelt, not in the grammar."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The library grows. The language holds still. That trade is the design."
          }
        ]
      }
    ]
  },
  {
    "slug": "open-spec-copyleft-engine",
    "file": "2026-05-01-open-spec-copyleft-engine.md",
    "title": "An open spec, a copyleft engine",
    "tag": "Sovereignty",
    "date": "2026-05-01",
    "description": "Two licenses, one argument: the file must outlive every vendor, including us.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The nika-spec repository went public this week, under Apache-2.0. The engine that runs it is AGPL-3.0-or-later. Two licenses for one project is a choice you should be able to interrogate, so here is the whole argument."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The spec is the part you adopt."
          },
          {
            "k": "text",
            "text": " The envelope, the four verbs, the task shape, the JSON schema, the conformance suite: all Apache-2.0, with a patent grant. Any team can build a competing runtime on it, and nothing we do later can revoke that. A language you might write hundreds of files in should not have a single implementation as its ceiling. This is the GraphQL shape: an open contract, many possible engines."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The engine is the part someone would take."
          },
          {
            "k": "text",
            "text": " The recent history of open agent tooling is a history of extraction: a permissively-licensed runtime gets wrapped, hosted, improved in private, and the improvements never come home. AGPL closes that door. Run our engine as a service, fork it, build a business next to it: all fine. But the changes ship back. The protection this buys is not ours, it is yours: no fork of the engine can quietly become a closed thing your files depend on."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Your exit is cp -r."
          },
          {
            "k": "text",
            "text": " The workflows are plain text in your repo. The spec is Apache. The engine is copyleft. Take the three together and the cost of leaving Nika is copying a folder. Compare that with the cost of leaving wherever your prompts live today."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Licenses are boring until the Friday they are not. We picked ours so the file you write today still runs the day the company that made the runner is gone. That includes us."
          }
        ]
      }
    ]
  },
  {
    "slug": "starting-over-on-purpose",
    "file": "2026-04-14-starting-over-on-purpose.md",
    "title": "Starting over, on purpose",
    "tag": "Origins",
    "date": "2026-04-14",
    "description": "We had a working prototype. We rebuilt from scratch anyway: craft, not extraction, one gate at a time.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "By spring 2026 there was a working prototype. The note from October had become a real engine: files ran, models answered, tools fired. The fastest path from there was obvious: refactor what worked, extract the good parts, ship."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "We did the opposite. The first architecture decision record of the current engine says it plainly: "
          },
          {
            "k": "strong",
            "text": "rebuild from scratch, never copy-paste the prototype."
          },
          {
            "k": "text",
            "text": " Craft, not extraction."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "That sounds romantic. It was actually the cold option."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "A prototype answers a different question."
          },
          {
            "k": "text",
            "text": " The prototype existed to learn whether the idea held: can intent live in a file, can a plan be drawn before it runs, can permissions be enforced rather than logged. It answered yes. But code written to "
          },
          {
            "k": "em",
            "text": "find out"
          },
          {
            "k": "text",
            "text": " is shaped by the finding-out: shortcuts where the idea was still fuzzy, generosity where discipline was needed later. Extracting it would have meant carrying every one of those youthful decisions into the thing people would trust with their machines."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Trust infrastructure has a different bar."
          },
          {
            "k": "text",
            "text": " An engine that enforces a permission boundary cannot itself be casual about correctness. So the rebuild came with rules the prototype never had: every crate passes a fixed set of admission gates before it enters the workspace; hard caps on file and function size; no unchecked failure paths in source. The gates are boring on purpose. Boring is what you want from the layer that decides whether a write to your disk is allowed to happen."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The language was frozen before the engine was grown."
          },
          {
            "k": "text",
            "text": " Rebuilding gave us the order most projects never get: spec first, engine second. The envelope ("
          },
          {
            "k": "code",
            "text": "nika: v1"
          },
          {
            "k": "text",
            "text": "), the four verbs, the permits model were locked as a contract, and then the engine was built "
          },
          {
            "k": "em",
            "text": "to"
          },
          {
            "k": "text",
            "text": " the contract, gate by gate. It is why the spec could open under Apache while the engine carries the AGPL: they were separate artifacts from the first day of the rebuild."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The prototype is not disowned; it was the necessary first draft, and drafts are how honest writing works. But you do not ship the draft. You keep what it taught you and write the real sentence."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Starting over cost months. It bought a foundation that will not need to apologize later. In a tool whose whole promise is "
          },
          {
            "k": "em",
            "text": "the file you write today still runs in ten years"
          },
          {
            "k": "text",
            "text": ", that trade is not a luxury. It is the product."
          }
        ]
      }
    ]
  },
  {
    "slug": "naming-the-drum",
    "file": "2026-03-21-naming-the-drum.md",
    "title": "Naming the drum",
    "tag": "Origins",
    "date": "2026-03-21",
    "description": "Why a workflow engine carries the name of a liberation god, and a butterfly on every commit.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "For months the project had no name. It was \"the file thing\": a note from October, a growing conviction, some early Rust. Then the question stopped being avoidable, because naming a thing is deciding what it is for."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The technical description was easy: a workflow language, four verbs, files you own. But the description missed the "
          },
          {
            "k": "em",
            "text": "reason"
          },
          {
            "k": "text",
            "text": ". We were not building a scheduler. We were building a way out of a trap: the trap where your best work, your context, your habits of thought all live behind someone else's login, priced monthly, revocable by letter."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "There is an old story about that trap. "
          },
          {
            "k": "strong",
            "text": "Nika is named for the sun god of liberation: the drum that turns fear into laughter and frees the ones who were locked out."
          },
          {
            "k": "text",
            "text": " A warrior of liberation whose weapon is not a sword but a "
          },
          {
            "k": "em",
            "text": "rhythm"
          },
          {
            "k": "text",
            "text": ": joy, repetition, the beat that makes the cage ridiculous. That is exactly the energy a workflow engine should have. Not conquest: release. Not a louder lock-in with better branding: the drum that plays until the door opens."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "So the name is a promise with lore attached:"
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Every workflow run is a beat of that drum."
          },
          {
            "k": "text",
            "text": " Each time a file runs on your machine, with your model, under your permits, the argument for owned intelligence gets one beat louder. Small, repeated, unstoppable: that is how rhythms win."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The butterfly signs the work."
          },
          {
            "k": "text",
            "text": " Every commit in the project carries a small butterfly. It is the signature of the craft: light, alive, impossible to cage. If you have scrolled to the bottom of this site, you have met it in particles."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "The liberation is structural, not rhetorical."
          },
          {
            "k": "text",
            "text": " A god of freedom would be a terrible mascot for a proprietary tool. The name only works because the license (AGPL, forever), the local-first engine, and the plain-text files make the freedom mechanical. Delete our company tomorrow and the drum keeps beating on your machine."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The full argument, what happened the day intelligence got a kill switch, what we promise, why sovereignty is for everyone or for no one, lives in "
          },
          {
            "k": "link",
            "text": "the manifesto",
            "href": "/manifesto"
          },
          {
            "k": "text",
            "text": ". It now speaks several languages, because liberation that only speaks English is not liberation."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The note asked for a file. The name asked for a fight worth having. The rest is shipping."
          }
        ]
      }
    ]
  },
  {
    "slug": "the-note-that-started-it",
    "file": "2025-10-17-the-note-that-started-it.md",
    "title": "The note that started it",
    "tag": "Origins",
    "date": "2025-10-17",
    "description": "Before the spec, before the name, there was one evening note: the best AI work of the month had just disappeared.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Before the spec, before the engine, before the name, there was a note. October 2025, one evening, after losing an afternoon's work to a closed tab."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The work was good. A careful chain of prompts that turned a messy pile of notes into a clean weekly brief: gather, think, write, save. It had taken a week of small refinements to get right. And it lived nowhere. It was a scroll position in a chat window, on someone else's server, in a format no tool could read back."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The note said, roughly:"
          }
        ]
      },
      {
        "k": "code",
        "lang": "text",
        "text": "the work is real. the container is fake.\nif it's worth doing twice, it's worth writing down.\nnot a transcript. the INTENT.\nwhat to fetch, what to think about, what to run, where it lands.\na file. plain text. mine."
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "That was the whole idea. Not a product, not an architecture: an objection. Software had spent fifty years learning to keep work: source control, reviews, diffs, the entire craft of making thought durable. And the newest, most powerful way of working had quietly dropped all of it. The more useful the AI work, the more disposable its container. Nobody had decided this. It was just the default."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Defaults can be refused."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Everything that came later unpacks that note. Write the intent down, and the work survives the session: that became "
          },
          {
            "k": "strong",
            "text": "the file"
          },
          {
            "k": "text",
            "text": ". Say what it may touch, and you can let it act: that became "
          },
          {
            "k": "strong",
            "text": "permits"
          },
          {
            "k": "text",
            "text": ". Name the four ways a machine can act, and the whole thing stays readable: that became "
          },
          {
            "k": "strong",
            "text": "the verbs"
          },
          {
            "k": "text",
            "text": ". Keep it on your machine, under a license nobody can revoke: that became the local-first engine and the AGPL."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "None of those words existed yet in October. There was only the feeling every builder knows: the tools were getting smarter and the work was getting "
          },
          {
            "k": "em",
            "text": "less"
          },
          {
            "k": "text",
            "text": " durable, and those two lines should never cross."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "If you have felt that too, the good session that evaporated, the prompt you rebuilt from memory for the third time: the rest of this site is for you. It starts where the note ended: write it down, and own it forever."
          }
        ]
      }
    ]
  }
]
