/* AUTO-GENERATED by scripts/build-blog.mjs from content/blog/*.md — NEVER EDIT.
   Regenerate: node scripts/build-blog.mjs (the vitest drift gate recompiles + diffs). */

export interface BlogInline {
  k: 'text' | 'strong' | 'em' | 'code' | 'link'
  text: string
  href?: string
}

export type BlogToken =
  | { k: 'p'; inline: BlogInline[] }
  | { k: 'h'; depth: number; text: string; id: string }
  | { k: 'code'; lang: string; filename?: string; text: string }
  | { k: 'quote'; inline: BlogInline[] }
  | { k: 'list'; ordered: boolean; items: BlogInline[][] }
  | { k: 'hr' }

export interface BlogPost {
  slug: string
  /** the source file under content/blog/ — the GitHub edit target */
  file: string
  title: string
  tag: string
  date: string
  description: string
  readingMin: number
  tokens: BlogToken[]
}

/* newest first */
export const BLOG_POSTS: BlogPost[] = [
  {
    "slug": "four-verbs",
    "file": "2026-06-22-four-verbs.md",
    "title": "Four verbs are enough",
    "tag": "Language",
    "date": "2026-06-22",
    "description": "A verb is a distinct execution model, not a feature. Why the language locks at four, forever.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Every workflow language faces the same temptation: keep adding verbs. A verb for HTTP. A verb for files. A verb for email, for SQL, for whatever last week's integration needed. Ten years later the language is a catalog nobody can hold in their head, and every file is written in a different dialect of it."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Nika locks the count at four, forever. The rule that makes this possible is strict: "
          },
          {
            "k": "strong",
            "text": "a verb is a distinct execution model"
          },
          {
            "k": "text",
            "text": ", not a feature. "
          },
          {
            "k": "strong",
            "text": "infer"
          },
          {
            "k": "text",
            "text": " generates with a model. "
          },
          {
            "k": "strong",
            "text": "exec"
          },
          {
            "k": "text",
            "text": " runs a process. "
          },
          {
            "k": "strong",
            "text": "invoke"
          },
          {
            "k": "text",
            "text": " calls a tool and returns. "
          },
          {
            "k": "strong",
            "text": "agent"
          },
          {
            "k": "text",
            "text": " loops with tools until the job is done. Four genuinely different ways for a machine to act. There is no fifth."
          }
        ]
      },
      {
        "k": "code",
        "lang": "yaml",
        "filename": "morning-brief.nika.yaml",
        "text": "nika: v1\nworkflow: morning-brief\n\ntasks:\n  - id: fetch_news\n    invoke:\n      tool: \"nika:fetch\"          # a tool, not a verb\n\n  - id: build\n    exec:\n      command: \"cargo build --release\"\n\n  - id: digest\n    depends_on: [fetch_news, build]\n    infer:\n      prompt: \"Summarize what changed\""
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "The test case was fetch. Surely getting a web page deserves its own verb? It does not, and the reason is the whole design: "
          },
          {
            "k": "strong",
            "text": "fetching is not a distinct execution model."
          },
          {
            "k": "text",
            "text": " It is a tool call. So "
          },
          {
            "k": "code",
            "text": "nika:fetch"
          },
          {
            "k": "text",
            "text": " lives in the standard library, reached through invoke, next to read, write, jq and the other 19 builtins. Everything callable is a tool. Everything about ordering is the graph."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "A closed language is a feature you can feel. You can finish learning it: four words and the file reads like prose. Your files never rot into an old dialect, because there is no new dialect coming. And tools keep growing where growth belongs, in the library: a new builtin, a new tool server (MCP), a new provider. The language holds still while the toolbelt expands."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "That stillness is the promise. The file you write today is the file you run in ten years. Languages that stop moving are the ones you can build on."
          }
        ]
      }
    ]
  },
  {
    "slug": "intent-as-code",
    "file": "2026-06-15-intent-as-code.md",
    "title": "Intent as Code: why your AI work should be a file",
    "tag": "Manifesto",
    "date": "2026-06-15",
    "description": "Chats evaporate, files compound. The case for writing AI work down as source you own.",
    "readingMin": 2,
    "tokens": [
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Think about the best thing you did with an AI last month. The careful prompt, the back-and-forth, the result that finally clicked. "
          },
          {
            "k": "strong",
            "text": "Where is it now?"
          },
          {
            "k": "text",
            "text": " For most people the honest answer is: gone. Buried in a chat history you will never scroll back through, on a server you don't control."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "We've accepted a strange deal: the more useful the work, the more disposable the container. Nobody would write software in a text box that forgets everything. Yet that's exactly how most AI work happens today."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "strong",
            "text": "Nika's bet is simple: useful AI work is worth writing down."
          },
          {
            "k": "text",
            "text": " Not as a transcript, as "
          },
          {
            "k": "em",
            "text": "source"
          },
          {
            "k": "text",
            "text": ". A small YAML file that says what you want: fetch this, think about that, run this command, save the result. The file is the workflow. Run it again tomorrow and it does the same thing. Change a line and "
          },
          {
            "k": "code",
            "text": "git diff"
          },
          {
            "k": "text",
            "text": " shows exactly what changed."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Four verbs cover the whole space: "
          },
          {
            "k": "strong",
            "text": "infer"
          },
          {
            "k": "text",
            "text": " (call a model), "
          },
          {
            "k": "strong",
            "text": "exec"
          },
          {
            "k": "text",
            "text": " (run a process), "
          },
          {
            "k": "strong",
            "text": "invoke"
          },
          {
            "k": "text",
            "text": " (use a tool), "
          },
          {
            "k": "strong",
            "text": "agent"
          },
          {
            "k": "text",
            "text": " (let it work a loop). Everything else is data flowing between tasks. The order falls out of the dependencies. Write "
          },
          {
            "k": "code",
            "text": "depends_on"
          },
          {
            "k": "text",
            "text": " and independent branches run in parallel, for free."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "And it runs on "
          },
          {
            "k": "strong",
            "text": "your machine"
          },
          {
            "k": "text",
            "text": ". One Rust binary. Your model keys, your files, your git history. No cloud between you and your own work, and a license (AGPL) that guarantees it stays that way."
          }
        ]
      },
      {
        "k": "p",
        "inline": [
          {
            "k": "text",
            "text": "Chat is a great place to "
          },
          {
            "k": "em",
            "text": "figure out"
          },
          {
            "k": "text",
            "text": " what you want. It is a terrible place to "
          },
          {
            "k": "em",
            "text": "keep"
          },
          {
            "k": "text",
            "text": " it. Explore in chat. Then write the intent down, and own it forever."
          }
        ]
      }
    ]
  }
]
