// i18n-pages.generated.ts — AUTO-GENERATED by scripts/build-i18n-pages.mjs
// from content/i18n/<locale>/*.yaml (the reviewed L1 corpus — the EN twin
// included: one shape, every voice, zero twin↔page drift by construction).
// DO NOT EDIT · regenerate: node scripts/build-i18n-pages.mjs
// Gates: src/test/i18n-lexicon.test.ts (corpus laws) · i18n.test.ts (routes).

export interface InstallStepCopy {
  n: string
  title: string
  plain: string
  plain2?: string
  ghost?: string
}
export interface InstallCopy {
  page: string
  fig: string
  title: string
  punch: string
  lede: string
  stamp: string
  steps: {
    brew: InstallStepCopy
    script: InstallStepCopy
    manual: InstallStepCopy
    editor: InstallStepCopy
    agents: InstallStepCopy
    first_run: InstallStepCopy
  }
  capture_title: string
  trouble_title: string
  trouble: { q: string; a: string }[]
  more: { next: string; learn: string; usecases: string; docs: string }
  labels: Record<string, string>
}

export const I18N_PAGES: { install: Record<string, InstallCopy> } = {
  "install": {
    "de": {
      "page": "/install",
      "fig": "install",
      "title": "Ein Binary. Deine Maschine.",
      "punch": "Zwei Minuten bis zum ersten Run.",
      "lede": "Nika ist **ein einziges Rust-Binary**: kein Daemon, kein Account, keine Cloud nötig. Wähl unten einen Weg hinein und starte dein erstes File mit einem **kostenlosen lokalen Modell**.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "Der Einzeiler",
          "plain": "macOS oder Linux mit Homebrew: sofort auf deinem `PATH`. Prüf es mit `nika --version`."
        },
        "script": {
          "n": "02 · script",
          "title": "Ohne Homebrew",
          "plain": "Lädt das **verifizierte Release-Binary** nach `~/.nika/bin` und druckt die eine `PATH`-Zeile für dein Shell-Profil. Terminal neu öffnen, und `nika --version` antwortet.",
          "plain2": "Toolchain schon an Bord? **cargo** holt den vorgebauten Release-Tarball, kein Kompilieren (das Binary landet als `nika-cli`, bis der crates.io-Publish steht: einmal einen Symlink auf den öffentlichen Namen legen). **nix** baut die exakte Release-Source über das Repo-Flake; der erste Run kompiliert, der Store cacht."
        },
        "manual": {
          "n": "03 · manuell",
          "title": "Air-gapped, oder von Hand",
          "plain": "Lade den Plattform-Tarball und `SHA256SUMS` vom letzten Release, verifiziere, dann schieb `nika` auf deinen `PATH`. Nichts telefoniert nach Hause."
        },
        "editor": {
          "n": "04 · editor",
          "title": "Die Editor-Extension",
          "plain": "`supernovae.nika-lang` · im VS Code Marketplace und auf Open VSX (Cursor · Windsurf · VSCodium). Sie lädt beim ersten Einsatz das passende `nika`-Release-Binary automatisch, oder nutzt das auf deinem `PATH` vorhandene. Jeder andere Editor: `nika lsp` spricht LSP über stdio · Source + Issues.",
          "ghost": "Completions · Diagnostics · eine Sicht auf den Plan · in deinem Editor"
        },
        "agents": {
          "n": "05 · agents",
          "title": "Arbeite mit deinen Agents",
          "plain": "Nika ist gebaut, um **von Agents geschrieben und von dir reviewt** zu werden. `nika init` legt das Schema-Wiring + `AGENTS.md` in dein Repo, damit Claude Code, Cursor, Codex und Co. beim ersten Versuch valide Workflows schreiben; `nika wire` ergänzt explizites Agent-Tool-Wiring (MCP), wo du es willst."
        },
        "first_run": {
          "n": "06 · erster run",
          "title": "Null Keys, null Cloud",
          "plain": "Starte mit `nika welcome`, dem Spiegel: was diese Maschine schon hat (Editoren · lokale Modelle · Key-*Präsenz*, nie Werte) und wohin als Nächstes. Dein erster Workflow braucht weder Modell noch API-Key. Speichere das File, auditiere es mit `nika check` (Plan · Kosten · Secrets, bevor irgendwas läuft), dann `nika run`. Ein KI-Schritt dazu? Zeig auf ein **kostenloses lokales Modell** (ein `ollama pull`, nichts verlässt deine Maschine), und `nika doctor` sagt dir exakt, was verkabelt ist."
        }
      },
      "capture_title": "was du sehen solltest",
      "trouble_title": "falls etwas hakt",
      "trouble": [
        {
          "q": "command not found: nika (nach dem Install-Script)",
          "a": "Das Script installiert nach `~/.nika/bin` und druckt die exakte `PATH`-Zeile für dein Shell-Profil (`~/.zshrc`, `~/.bashrc`). Zeile einfügen, Terminal neu öffnen, und `nika --version` antwortet."
        },
        {
          "q": "macOS blockiert das Binary (nur manueller Tarball)",
          "a": "Ein von Hand geladenes Binary trägt das Quarantine-Flag; brew und das Install-Script nicht. Einmal entfernen, oder Rechtsklick → Öffnen."
        },
        {
          "q": "hinter einem Firmen-Proxy",
          "a": "Das Install-Script ist pures curl; es respektiert die Standard-Proxy-Variablen für den Download. Das Binary selbst telefoniert nirgendwohin."
        },
        {
          "q": "checksum mismatch beim Tarball",
          "a": "Ein Mismatch heißt: korrupter oder manipulierter Download. Nicht ausführen. Tarball und `SHA256SUMS` neu von der Release-Seite laden und erneut verifizieren."
        }
      ],
      "more": {
        "next": "Weiter:",
        "learn": "lern das File in 5 Minuten",
        "usecases": "echte Workflows ansehen",
        "docs": "volle Docs"
      },
      "labels": {
        "one_liner": "Install-Script",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "Checksum-Verifikation",
        "repo_wiring": "Repo-Wiring",
        "cursor_wiring": "Cursor-Agent-Wiring",
        "welcome": "der Spiegel · starte hier",
        "check": "statisches Audit",
        "run": "run",
        "ollama": "das kostenlose lokale Modell",
        "example": "Beispiel-Run · lokales Modell",
        "doctor": "Environment-Check"
      }
    },
    "en": {
      "page": "/install",
      "fig": "install",
      "title": "One binary. Your machine.",
      "punch": "Two minutes to your first run.",
      "lede": "Nika is **one Rust binary**: no daemon, no account, no cloud required. Pick a way in below and run your first file with a **free local model**.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "The one-liner",
          "plain": "macOS or Linux with Homebrew: on your `PATH` immediately. Check it with `nika --version`."
        },
        "script": {
          "n": "02 · script",
          "title": "Without Homebrew",
          "plain": "Downloads the **verified release binary** into `~/.nika/bin` and prints the single `PATH` line to add to your shell profile. Reopen the terminal and `nika --version` works.",
          "plain2": "Already carrying a toolchain? **cargo** fetches the prebuilt release tarball, no compile (the binary lands as `nika-cli` until the crates.io publish: symlink the public name once). **nix** builds the exact release source via the repo flake; the first run compiles, the store caches it."
        },
        "manual": {
          "n": "03 · manual",
          "title": "Air-gapped, or by hand",
          "plain": "Download the platform tarball and `SHA256SUMS` from the latest release, verify, then move `nika` onto your `PATH`. Nothing phones home."
        },
        "editor": {
          "n": "04 · editor",
          "title": "The editor extension",
          "plain": "`supernovae.nika-lang` · on the VS Code Marketplace and Open VSX (Cursor · Windsurf · VSCodium). It auto-downloads the matching `nika` release binary on first use, or reuses the one already on your `PATH`. Any other editor: `nika lsp` speaks LSP over stdio · source + issues.",
          "ghost": "completions · diagnostics · a view of the plan · in your editor"
        },
        "agents": {
          "n": "05 · agents",
          "title": "Work with your agents",
          "plain": "Nika is built to be **written by agents and reviewed by you**. `nika init` drops the schema wiring + `AGENTS.md` into your repo so Claude Code, Cursor, Codex and friends author valid workflows on the first try; `nika wire` adds explicit agent-tool (MCP) wiring where you want it."
        },
        "first_run": {
          "n": "06 · first run",
          "title": "Zero keys, zero cloud",
          "plain": "Start with `nika welcome`, the mirror: what this machine already has (editors · local models · key *presence*, never values) and where to go next. Your first workflow needs no model and no API key. Save the file, audit it with `nika check` (plan · cost · secrets, before anything runs), then `nika run`. Adding an AI step? Point it at a **free local model** (one `ollama pull`, nothing leaves your machine), and `nika doctor` tells you exactly what's wired."
        }
      },
      "capture_title": "what you should see",
      "trouble_title": "if something catches",
      "trouble": [
        {
          "q": "command not found: nika (after the install script)",
          "a": "The script installs to `~/.nika/bin` and prints the exact `PATH` line to add to your shell profile (`~/.zshrc`, `~/.bashrc`). Add it, reopen the terminal, and `nika --version` answers."
        },
        {
          "q": "macOS blocks the binary (manual tarball only)",
          "a": "A hand-downloaded binary carries the quarantine flag; brew and the install script don't. Clear it once, or right-click → Open."
        },
        {
          "q": "behind a corporate proxy",
          "a": "The install script is plain curl; it honors the standard proxy variables for the download. The binary itself phones nothing home."
        },
        {
          "q": "checksum mismatch on the tarball",
          "a": "A mismatch means a corrupted or tampered download. Don't run it. Re-download both the tarball and `SHA256SUMS` from the release page and verify again."
        }
      ],
      "more": {
        "next": "Next:",
        "learn": "learn the file in 5 minutes",
        "usecases": "browse real workflows",
        "docs": "full docs"
      },
      "labels": {
        "one_liner": "install script",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "checksum verification",
        "repo_wiring": "repo wiring",
        "cursor_wiring": "Cursor agent wiring",
        "welcome": "the mirror · start here",
        "check": "static audit",
        "run": "run",
        "ollama": "the free local model",
        "example": "example run · local model",
        "doctor": "environment check"
      }
    },
    "es": {
      "page": "/install",
      "fig": "install",
      "title": "Un binario. Tu máquina.",
      "punch": "Dos minutos hasta tu primer run.",
      "lede": "Nika es **un solo binario Rust**: sin daemon, sin cuenta, sin cloud obligatorio. Elige una puerta de entrada abajo y ejecuta tu primer archivo con un **modelo local gratuito**.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "El one-liner",
          "plain": "macOS o Linux con Homebrew: en tu `PATH` de inmediato. Compruébalo con `nika --version`."
        },
        "script": {
          "n": "02 · script",
          "title": "Sin Homebrew",
          "plain": "Descarga el **binario de release verificado** en `~/.nika/bin` e imprime la única línea `PATH` que añadir a tu perfil de shell. Reabre la terminal y `nika --version` responde.",
          "plain2": "¿Ya llevas una toolchain? **cargo** trae el tarball de release precompilado, sin compilar (el binario llega como `nika-cli` hasta la publicación en crates.io: un symlink al nombre público, una vez). **nix** construye la source exacta de la release vía el flake del repo; el primer run compila, el store la cachea."
        },
        "manual": {
          "n": "03 · manual",
          "title": "Air-gapped, o a mano",
          "plain": "Descarga el tarball de tu plataforma y `SHA256SUMS` desde la última release, verifica, y mueve `nika` a tu `PATH`. Nada llama a casa."
        },
        "editor": {
          "n": "04 · editor",
          "title": "La extensión del editor",
          "plain": "`supernovae.nika-lang` · en el VS Code Marketplace y Open VSX (Cursor · Windsurf · VSCodium). Descarga automáticamente el binario `nika` de la release correspondiente en el primer uso, o reutiliza el que ya está en tu `PATH`. ¿Cualquier otro editor? `nika lsp` habla LSP sobre stdio · source + issues.",
          "ghost": "completions · diagnósticos · una vista del plan · en tu editor"
        },
        "agents": {
          "n": "05 · agentes",
          "title": "Trabaja con tus agentes",
          "plain": "Nika está hecho para ser **escrito por agentes y revisado por ti**. `nika init` deja el cableado del schema + `AGENTS.md` en tu repo para que Claude Code, Cursor, Codex y compañía escriban workflows válidos a la primera; `nika wire` añade cableado agent-tool (MCP) explícito donde tú quieras."
        },
        "first_run": {
          "n": "06 · primer run",
          "title": "Cero claves, cero cloud",
          "plain": "Empieza con `nika welcome`, el espejo: lo que esta máquina ya tiene (editores · modelos locales · *presencia* de claves, nunca valores) y adónde ir después. Tu primer workflow no necesita modelo ni clave API. Guarda el archivo, audítalo con `nika check` (plan · coste · secretos, antes de que nada corra), y luego `nika run`. ¿Añades un paso de IA? Apúntalo a un **modelo local gratuito** (un `ollama pull`, nada sale de tu máquina), y `nika doctor` te dice exactamente qué está cableado."
        }
      },
      "capture_title": "lo que deberías ver",
      "trouble_title": "si algo se atasca",
      "trouble": [
        {
          "q": "command not found: nika (después del script de instalación)",
          "a": "El script instala en `~/.nika/bin` e imprime la línea `PATH` exacta que añadir a tu perfil de shell (`~/.zshrc`, `~/.bashrc`). Añádela, reabre la terminal, y `nika --version` responde."
        },
        {
          "q": "macOS bloquea el binario (solo tarball manual)",
          "a": "Un binario descargado a mano lleva el flag de quarantine; brew y el script de instalación no. Quítalo una vez, o clic derecho → Abrir."
        },
        {
          "q": "detrás de un proxy corporativo",
          "a": "El script de instalación es curl puro; respeta las variables proxy estándar para la descarga. El binario en sí no llama a ninguna parte."
        },
        {
          "q": "checksum mismatch en el tarball",
          "a": "Un mismatch significa una descarga corrupta o manipulada. No lo ejecutes. Vuelve a descargar el tarball y `SHA256SUMS` desde la página de release y verifica de nuevo."
        }
      ],
      "more": {
        "next": "Siguiente:",
        "learn": "aprende el archivo en 5 minutos",
        "usecases": "explora workflows reales",
        "docs": "docs completas"
      },
      "labels": {
        "one_liner": "script de instalación",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "verificación de checksum",
        "repo_wiring": "cableado del repo",
        "cursor_wiring": "cableado del agente Cursor",
        "welcome": "el espejo · empieza aquí",
        "check": "auditoría estática",
        "run": "run",
        "ollama": "el modelo local gratuito",
        "example": "run de ejemplo · modelo local",
        "doctor": "check del entorno"
      }
    },
    "fr": {
      "page": "/install",
      "fig": "install",
      "title": "Un binaire. Ta machine.",
      "punch": "Deux minutes jusqu'à ton premier run.",
      "lede": "Nika, c'est **un seul binaire Rust** : pas de daemon, pas de compte, pas de cloud obligatoire. Choisis une porte d'entrée ci-dessous et lance ton premier fichier avec un **modèle local gratuit**.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "La one-liner",
          "plain": "macOS ou Linux avec Homebrew : sur ton `PATH` immédiatement. Vérifie avec `nika --version`."
        },
        "script": {
          "n": "02 · script",
          "title": "Sans Homebrew",
          "plain": "Télécharge le **binaire de release vérifié** dans `~/.nika/bin` et imprime l'unique ligne `PATH` à ajouter à ton profil shell. Rouvre le terminal et `nika --version` répond.",
          "plain2": "Une toolchain déjà en place ? **cargo** récupère le tarball de release précompilé, zéro compilation (le binaire arrive sous le nom `nika-cli` jusqu'à la publication crates.io : un symlink vers le nom public, une fois). **nix** construit la source exacte de la release via le flake du repo ; le premier run compile, le store met en cache."
        },
        "manual": {
          "n": "03 · manuel",
          "title": "Air-gapped, ou à la main",
          "plain": "Télécharge le tarball de ta plateforme et `SHA256SUMS` depuis la dernière release, vérifie, puis place `nika` sur ton `PATH`. Rien ne téléphone à la maison."
        },
        "editor": {
          "n": "04 · éditeur",
          "title": "L'extension éditeur",
          "plain": "`supernovae.nika-lang` · sur le VS Code Marketplace et Open VSX (Cursor · Windsurf · VSCodium). Elle télécharge le binaire `nika` de la release correspondante au premier usage, ou réutilise celui déjà sur ton `PATH`. Tout autre éditeur : `nika lsp` parle LSP sur stdio · source + issues.",
          "ghost": "complétions · diagnostics · une vue du plan · dans ton éditeur"
        },
        "agents": {
          "n": "05 · agents",
          "title": "Travaille avec tes agents",
          "plain": "Nika est conçu pour être **écrit par des agents et relu par toi**. `nika init` dépose le câblage du schema + `AGENTS.md` dans ton repo pour que Claude Code, Cursor, Codex et les autres écrivent des workflows valides du premier coup ; `nika wire` ajoute le câblage agent-tool (MCP) explicite là où tu le veux."
        },
        "first_run": {
          "n": "06 · premier run",
          "title": "Zéro clé, zéro cloud",
          "plain": "Commence par `nika welcome`, le miroir : ce que cette machine a déjà (éditeurs · modèles locaux · *présence* des clés, jamais leurs valeurs) et où aller ensuite. Ton premier workflow n'a besoin ni de modèle ni de clé API. Sauve le fichier, audite-le avec `nika check` (plan · coût · secrets, avant que rien ne tourne), puis `nika run`. Tu ajoutes une étape IA ? Pointe-la sur un **modèle local gratuit** (un `ollama pull`, rien ne quitte ta machine), et `nika doctor` te dit exactement ce qui est câblé."
        }
      },
      "capture_title": "ce que tu devrais voir",
      "trouble_title": "si quelque chose accroche",
      "trouble": [
        {
          "q": "command not found: nika (après le script d'install)",
          "a": "Le script installe dans `~/.nika/bin` et imprime la ligne `PATH` exacte à ajouter à ton profil shell (`~/.zshrc`, `~/.bashrc`). Ajoute-la, rouvre le terminal, et `nika --version` répond."
        },
        {
          "q": "macOS bloque le binaire (tarball manuel uniquement)",
          "a": "Un binaire téléchargé à la main porte le flag quarantine ; brew et le script d'install non. Retire-le une fois, ou clic droit → Ouvrir."
        },
        {
          "q": "derrière un proxy d'entreprise",
          "a": "Le script d'install est du curl pur ; il honore les variables proxy standard pour le téléchargement. Le binaire lui-même ne téléphone nulle part."
        },
        {
          "q": "checksum mismatch sur le tarball",
          "a": "Un mismatch signifie un téléchargement corrompu ou trafiqué. Ne le lance pas. Retélécharge le tarball et `SHA256SUMS` depuis la page de release et vérifie à nouveau."
        }
      ],
      "more": {
        "next": "Ensuite :",
        "learn": "apprends le fichier en 5 minutes",
        "usecases": "parcours des workflows réels",
        "docs": "docs complètes"
      },
      "labels": {
        "one_liner": "script d'install",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "vérification checksum",
        "repo_wiring": "câblage du repo",
        "cursor_wiring": "câblage agent Cursor",
        "welcome": "le miroir · commence ici",
        "check": "audit statique",
        "run": "run",
        "ollama": "le modèle local gratuit",
        "example": "run d'exemple · modèle local",
        "doctor": "check d'environnement"
      }
    },
    "ja": {
      "page": "/install",
      "fig": "install",
      "title": "バイナリひとつ。きみのマシンで。",
      "punch": "最初の run まで 2 分。",
      "lede": "Nika は **Rust バイナリひとつ**。daemon なし、アカウント不要、cloud も 必須ではない。下から入り口を選んで、**無料のローカルモデル**で最初の ファイルを動かそう。",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "ワンライナー",
          "plain": "Homebrew のある macOS / Linux なら、すぐに `PATH` に載る。 `nika --version` で確認。"
        },
        "script": {
          "n": "02 · script",
          "title": "Homebrew なしで",
          "plain": "**検証済みの release バイナリ**を `~/.nika/bin` にダウンロードし、 シェルプロファイルに足す `PATH` の 1 行を表示する。ターミナルを 開き直せば `nika --version` が答える。",
          "plain2": "toolchain がすでにあるなら: **cargo** はビルド済みの release tarball を 取ってくる。コンパイル不要（crates.io 公開までバイナリ名は `nika-cli`。 公開名への symlink を一度だけ張る）。**nix** はリポジトリの flake から release のソースをそのままビルドする。初回 run はコンパイル、store が キャッシュする。"
        },
        "manual": {
          "n": "03 · 手動",
          "title": "air-gapped でも、手作業でも",
          "plain": "最新 release からプラットフォームの tarball と `SHA256SUMS` を ダウンロードして検証し、`nika` を `PATH` に置く。 どこにも通信しない。"
        },
        "editor": {
          "n": "04 · エディタ",
          "title": "エディタ拡張",
          "plain": "`supernovae.nika-lang` · VS Code Marketplace と Open VSX にある （Cursor · Windsurf · VSCodium）。初回使用時に対応する `nika` release バイナリを自動ダウンロード、`PATH` 上の既存バイナリがあればそれを 使う。他のエディタなら: `nika lsp` が stdio で LSP を話す · source + issues。",
          "ghost": "補完 · 診断 · プランのビュー · きみのエディタの中で"
        },
        "agents": {
          "n": "05 · エージェント",
          "title": "エージェントと一緒に",
          "plain": "Nika は**エージェントが書き、きみがレビューする**ために作られている。 `nika init` が schema の配線と `AGENTS.md` をリポジトリに置き、 Claude Code · Cursor · Codex たちが一発で valid な workflow を書ける ようにする。`nika wire` は agent-tool（MCP）の明示的な配線を、 欲しい場所にだけ足す。"
        },
        "first_run": {
          "n": "06 · 最初の run",
          "title": "キーゼロ、cloud ゼロ",
          "plain": "まず `nika welcome`、鏡だ: このマシンに何があるか（エディタ · ローカルモデル · キーの*有無*だけ、値は決して見ない）と、次に 行く場所。最初の workflow にモデルも API キーも要らない。ファイルを 保存し、`nika check` で監査（plan · コスト · secrets を、何かが 動く前に）、それから `nika run`。AI ステップを足すなら **無料のローカルモデル**へ（`ollama pull` ひとつ、マシンから何も 出ない）。`nika doctor` が配線済みのものを正確に教えてくれる。"
        }
      },
      "capture_title": "表示されるはずのもの",
      "trouble_title": "引っかかったら",
      "trouble": [
        {
          "q": "command not found: nika（インストールスクリプトの後）",
          "a": "スクリプトは `~/.nika/bin` にインストールし、シェルプロファイル （`~/.zshrc`, `~/.bashrc`）に足す正確な `PATH` 行を表示する。 追加してターミナルを開き直せば `nika --version` が答える。"
        },
        {
          "q": "macOS がバイナリをブロックする（手動 tarball のみ）",
          "a": "手でダウンロードしたバイナリは quarantine フラグ付き。brew と インストールスクリプトは付かない。一度クリアするか、右クリック → 開く。"
        },
        {
          "q": "社内 proxy の内側で",
          "a": "インストールスクリプトは素の curl。ダウンロードには標準の proxy 変数をそのまま使う。バイナリ自体はどこにも通信しない。"
        },
        {
          "q": "tarball の checksum mismatch",
          "a": "mismatch は破損か改ざんされたダウンロードの印。実行しないこと。 release ページから tarball と `SHA256SUMS` を取り直して再検証する。"
        }
      ],
      "more": {
        "next": "次へ:",
        "learn": "5 分でファイルを学ぶ",
        "usecases": "実物の workflow を見る",
        "docs": "フルドキュメント"
      },
      "labels": {
        "one_liner": "インストールスクリプト",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "checksum 検証",
        "repo_wiring": "リポジトリ配線",
        "cursor_wiring": "Cursor エージェント配線",
        "welcome": "鏡 · ここから",
        "check": "静的監査",
        "run": "run",
        "ollama": "無料のローカルモデル",
        "example": "実行例 · ローカルモデル",
        "doctor": "環境チェック"
      }
    },
    "ko": {
      "page": "/install",
      "fig": "install",
      "title": "바이너리 하나. 너의 머신.",
      "punch": "첫 run까지 2분.",
      "lede": "Nika는 **Rust 바이너리 하나**다. daemon 없음, 계정 없음, cloud 필수 아님. 아래에서 들어갈 문을 고르고 **무료 로컬 모델**로 첫 파일을 실행해 보자.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "원라이너",
          "plain": "Homebrew가 있는 macOS 또는 Linux: 바로 `PATH`에 올라간다. `nika --version`으로 확인."
        },
        "script": {
          "n": "02 · script",
          "title": "Homebrew 없이",
          "plain": "**검증된 release 바이너리**를 `~/.nika/bin`에 내려받고, 셸 프로필에 추가할 `PATH` 한 줄을 출력한다. 터미널을 다시 열면 `nika --version`이 답한다.",
          "plain2": "toolchain이 이미 있다면: **cargo**는 미리 빌드된 release tarball을 가져온다. 컴파일 없음 (crates.io publish 전까지 바이너리 이름은 `nika-cli`: 공개 이름으로 symlink 한 번). **nix**는 repo flake로 release 소스를 그대로 빌드한다. 첫 run은 컴파일하고, store가 캐시한다."
        },
        "manual": {
          "n": "03 · 수동",
          "title": "air-gapped, 또는 직접",
          "plain": "최신 release에서 플랫폼 tarball과 `SHA256SUMS`를 내려받아 검증한 뒤 `nika`를 `PATH`에 놓는다. 아무 데도 연결하지 않는다."
        },
        "editor": {
          "n": "04 · 에디터",
          "title": "에디터 확장",
          "plain": "`supernovae.nika-lang` · VS Code Marketplace와 Open VSX에 있다 (Cursor · Windsurf · VSCodium). 첫 사용 시 맞는 `nika` release 바이너리를 자동으로 내려받거나, `PATH`에 이미 있는 것을 재사용한다. 다른 에디터라면: `nika lsp`가 stdio로 LSP를 말한다 · source + issues.",
          "ghost": "자동완성 · 진단 · 플랜 뷰 · 너의 에디터 안에서"
        },
        "agents": {
          "n": "05 · 에이전트",
          "title": "에이전트와 함께",
          "plain": "Nika는 **에이전트가 쓰고 네가 리뷰하도록** 만들어졌다. `nika init`이 schema 연결과 `AGENTS.md`를 repo에 넣어 Claude Code, Cursor, Codex 들이 첫 시도에 valid한 workflow를 쓰게 하고, `nika wire`는 원하는 곳에만 명시적 agent-tool(MCP) 연결을 더한다."
        },
        "first_run": {
          "n": "06 · 첫 run",
          "title": "키 제로, cloud 제로",
          "plain": "`nika welcome`부터, 거울이다: 이 머신에 이미 있는 것들 (에디터 · 로컬 모델 · 키의 *존재 여부*만, 값은 절대 아님) 그리고 다음에 갈 곳. 첫 workflow에는 모델도 API 키도 필요 없다. 파일을 저장하고 `nika check`로 감사한 뒤 (plan · 비용 · secrets, 무엇이든 돌기 전에) `nika run`. AI 스텝을 더한다면 **무료 로컬 모델**로 (`ollama pull` 한 번, 머신 밖으로 아무것도 안 나간다), `nika doctor`가 무엇이 연결됐는지 정확히 알려준다."
        }
      },
      "capture_title": "이렇게 보여야 한다",
      "trouble_title": "뭔가 걸린다면",
      "trouble": [
        {
          "q": "command not found: nika (설치 스크립트 후)",
          "a": "스크립트는 `~/.nika/bin`에 설치하고 셸 프로필(`~/.zshrc`, `~/.bashrc`)에 추가할 정확한 `PATH` 줄을 출력한다. 추가하고 터미널을 다시 열면 `nika --version`이 답한다."
        },
        {
          "q": "macOS가 바이너리를 차단 (수동 tarball만)",
          "a": "손으로 내려받은 바이너리는 quarantine 플래그가 붙는다. brew와 설치 스크립트는 안 붙는다. 한 번 지우거나, 우클릭 → 열기."
        },
        {
          "q": "회사 proxy 뒤에서",
          "a": "설치 스크립트는 순수 curl이다. 다운로드에 표준 proxy 변수를 그대로 쓴다. 바이너리 자체는 어디에도 연결하지 않는다."
        },
        {
          "q": "tarball checksum mismatch",
          "a": "mismatch는 손상되었거나 변조된 다운로드라는 뜻이다. 실행하지 말 것. release 페이지에서 tarball과 `SHA256SUMS`를 다시 받아 재검증한다."
        }
      ],
      "more": {
        "next": "다음:",
        "learn": "5분 만에 파일 배우기",
        "usecases": "실제 workflow 둘러보기",
        "docs": "전체 문서"
      },
      "labels": {
        "one_liner": "설치 스크립트",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "checksum 검증",
        "repo_wiring": "repo 연결",
        "cursor_wiring": "Cursor 에이전트 연결",
        "welcome": "거울 · 여기서 시작",
        "check": "정적 감사",
        "run": "run",
        "ollama": "무료 로컬 모델",
        "example": "예시 run · 로컬 모델",
        "doctor": "환경 체크"
      }
    },
    "pt-br": {
      "page": "/install",
      "fig": "install",
      "title": "Um binário. Sua máquina.",
      "punch": "Dois minutos até o seu primeiro run.",
      "lede": "Nika é **um único binário Rust**: sem daemon, sem conta, sem cloud obrigatória. Escolha uma porta de entrada abaixo e rode seu primeiro arquivo com um **modelo local gratuito**.",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "O one-liner",
          "plain": "macOS ou Linux com Homebrew: no seu `PATH` na hora. Confira com `nika --version`."
        },
        "script": {
          "n": "02 · script",
          "title": "Sem Homebrew",
          "plain": "Baixa o **binário de release verificado** em `~/.nika/bin` e imprime a única linha `PATH` para adicionar ao seu perfil de shell. Reabra o terminal e `nika --version` responde.",
          "plain2": "Já carrega uma toolchain? O **cargo** busca o tarball de release pré-compilado, sem compilar (o binário chega como `nika-cli` até a publicação no crates.io: um symlink para o nome público, uma vez). O **nix** constrói a source exata da release via o flake do repo; o primeiro run compila, o store guarda em cache."
        },
        "manual": {
          "n": "03 · manual",
          "title": "Air-gapped, ou na mão",
          "plain": "Baixe o tarball da sua plataforma e o `SHA256SUMS` da última release, verifique, e mova o `nika` para o seu `PATH`. Nada liga para casa."
        },
        "editor": {
          "n": "04 · editor",
          "title": "A extensão do editor",
          "plain": "`supernovae.nika-lang` · no VS Code Marketplace e no Open VSX (Cursor · Windsurf · VSCodium). Ela baixa automaticamente o binário `nika` da release correspondente no primeiro uso, ou reutiliza o que já está no seu `PATH`. Qualquer outro editor: `nika lsp` fala LSP por stdio · source + issues.",
          "ghost": "completions · diagnósticos · uma visão do plano · no seu editor"
        },
        "agents": {
          "n": "05 · agentes",
          "title": "Trabalhe com os seus agentes",
          "plain": "Nika foi feito para ser **escrito por agentes e revisado por você**. `nika init` coloca o wiring do schema + `AGENTS.md` no seu repo para que Claude Code, Cursor, Codex e companhia escrevam workflows válidos de primeira; `nika wire` adiciona wiring agent-tool (MCP) explícito onde você quiser."
        },
        "first_run": {
          "n": "06 · primeiro run",
          "title": "Zero chaves, zero cloud",
          "plain": "Comece com `nika welcome`, o espelho: o que esta máquina já tem (editores · modelos locais · *presença* de chaves, nunca valores) e para onde ir depois. Seu primeiro workflow não precisa de modelo nem de chave de API. Salve o arquivo, audite com `nika check` (plano · custo · secrets, antes de qualquer coisa rodar), depois `nika run`. Vai adicionar um passo de IA? Aponte para um **modelo local gratuito** (um `ollama pull`, nada sai da sua máquina), e o `nika doctor` diz exatamente o que está ligado."
        }
      },
      "capture_title": "o que você deve ver",
      "trouble_title": "se algo travar",
      "trouble": [
        {
          "q": "command not found: nika (depois do script de instalação)",
          "a": "O script instala em `~/.nika/bin` e imprime a linha `PATH` exata para adicionar ao seu perfil de shell (`~/.zshrc`, `~/.bashrc`). Adicione, reabra o terminal, e `nika --version` responde."
        },
        {
          "q": "macOS bloqueia o binário (só tarball manual)",
          "a": "Um binário baixado na mão carrega a flag de quarantine; brew e o script de instalação, não. Remova uma vez, ou clique direito → Abrir."
        },
        {
          "q": "atrás de um proxy corporativo",
          "a": "O script de instalação é curl puro; ele respeita as variáveis proxy padrão para o download. O binário em si não liga para lugar nenhum."
        },
        {
          "q": "checksum mismatch no tarball",
          "a": "Um mismatch significa download corrompido ou adulterado. Não execute. Baixe de novo o tarball e o `SHA256SUMS` da página da release e verifique outra vez."
        }
      ],
      "more": {
        "next": "Próximo:",
        "learn": "aprenda o arquivo em 5 minutos",
        "usecases": "veja workflows reais",
        "docs": "docs completas"
      },
      "labels": {
        "one_liner": "script de instalação",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "verificação de checksum",
        "repo_wiring": "wiring do repo",
        "cursor_wiring": "wiring do agente Cursor",
        "welcome": "o espelho · comece aqui",
        "check": "auditoria estática",
        "run": "run",
        "ollama": "o modelo local gratuito",
        "example": "run de exemplo · modelo local",
        "doctor": "check do ambiente"
      }
    },
    "zh-hans": {
      "page": "/install",
      "fig": "install",
      "title": "一个二进制文件。你的机器。",
      "punch": "两分钟到你的第一次 run。",
      "lede": "Nika 是**单个 Rust 二进制文件**：没有 daemon，不需要账号，不强制 cloud。 在下面选一个入口，用**免费的本地模型**跑起你的第一个文件。",
      "stamp": "macOS · Linux · air-gapped OK",
      "steps": {
        "brew": {
          "n": "01 · homebrew",
          "title": "一行命令",
          "plain": "有 Homebrew 的 macOS 或 Linux：立刻进入你的 `PATH`。 用 `nika --version` 确认。"
        },
        "script": {
          "n": "02 · script",
          "title": "不用 Homebrew",
          "plain": "把**经过验证的 release 二进制**下载到 `~/.nika/bin`，并打印出要加进 shell 配置文件的那一行 `PATH`。重开终端，`nika --version` 就有回应。",
          "plain2": "已经带着 toolchain？**cargo** 直接拉取预编译的 release tarball， 无需编译（在 crates.io 发布之前二进制名为 `nika-cli`：给公开名字 做一次 symlink 即可）。**nix** 通过仓库的 flake 构建 release 的 精确源码；首次 run 编译，store 负责缓存。"
        },
        "manual": {
          "n": "03 · 手动",
          "title": "air-gapped，或者手动来",
          "plain": "从最新 release 下载对应平台的 tarball 和 `SHA256SUMS`，校验后把 `nika` 放进你的 `PATH`。它不会向任何地方发送数据。"
        },
        "editor": {
          "n": "04 · 编辑器",
          "title": "编辑器扩展",
          "plain": "`supernovae.nika-lang` · 在 VS Code Marketplace 和 Open VSX 上 （Cursor · Windsurf · VSCodium）。首次使用时自动下载匹配的 `nika` release 二进制，或复用你 `PATH` 上已有的那个。其他编辑器： `nika lsp` 通过 stdio 说 LSP · source + issues。",
          "ghost": "补全 · 诊断 · 计划视图 · 就在你的编辑器里"
        },
        "agents": {
          "n": "05 · 智能体",
          "title": "与你的智能体协作",
          "plain": "Nika 生来就是**由智能体书写、由你审阅**的。`nika init` 把 schema 接线和 `AGENTS.md` 放进你的仓库，让 Claude Code、Cursor、Codex 们第一次就写出合法的 workflow；`nika wire` 在你需要的地方加上 显式的 agent-tool（MCP）接线。"
        },
        "first_run": {
          "n": "06 · 第一次 run",
          "title": "零密钥，零 cloud",
          "plain": "从 `nika welcome` 开始，它是一面镜子：这台机器已经有什么 （编辑器 · 本地模型 · 密钥的*存在与否*，绝不读取值），以及下一步 去哪。你的第一个 workflow 不需要模型也不需要 API 密钥。保存文件， 用 `nika check` 审计（plan · 成本 · secrets，在任何东西运行之前）， 然后 `nika run`。要加一个 AI 步骤？指向一个**免费的本地模型** （一次 `ollama pull`，什么都不离开你的机器），`nika doctor` 会 准确告诉你接好了什么。"
        }
      },
      "capture_title": "你应该看到的",
      "trouble_title": "如果卡住了",
      "trouble": [
        {
          "q": "command not found: nika（安装脚本之后）",
          "a": "脚本安装到 `~/.nika/bin`，并打印出要加进 shell 配置文件 （`~/.zshrc`、`~/.bashrc`）的确切 `PATH` 行。加上它，重开终端， `nika --version` 就有回应。"
        },
        {
          "q": "macOS 拦截了二进制（仅手动 tarball）",
          "a": "手动下载的二进制带着 quarantine 标记；brew 和安装脚本不带。 清除一次即可，或右键 → 打开。"
        },
        {
          "q": "在公司 proxy 之后",
          "a": "安装脚本就是纯 curl；下载时遵循标准的 proxy 环境变量。二进制 本身不向任何地方发送数据。"
        },
        {
          "q": "tarball 的 checksum mismatch",
          "a": "mismatch 意味着下载损坏或被篡改。不要运行它。从 release 页面 重新下载 tarball 和 `SHA256SUMS`，再校验一次。"
        }
      ],
      "more": {
        "next": "下一步：",
        "learn": "5 分钟学会这个文件",
        "usecases": "浏览真实的 workflow",
        "docs": "完整文档"
      },
      "labels": {
        "one_liner": "安装脚本",
        "binstall": "cargo binstall",
        "nix": "nix",
        "checksum": "checksum 校验",
        "repo_wiring": "仓库接线",
        "cursor_wiring": "Cursor 智能体接线",
        "welcome": "镜子 · 从这里开始",
        "check": "静态审计",
        "run": "run",
        "ollama": "免费的本地模型",
        "example": "示例 run · 本地模型",
        "doctor": "环境检查"
      }
    }
  }
}
