// language.generated.ts — AUTO-GENERATED by scripts/build-language.mjs
// from public/schema/workflow.json (the served contract — the same file
// editors and the engine validate against). DO NOT EDIT · regenerate:
//   node scripts/build-language.mjs
// Drift gate: src/test/language.test.ts recompiles and byte-diffs, and
// pins the verb-flagged set against CANON.verbNames.

export interface WordDecl {
  /** where the word speaks (envelope · task · a verb block · the leashes) */
  scope: string
  /** required at that surface (a miss is a schema finding) */
  required: boolean
  /** the schema's own type label, when it declares one */
  type?: string
  /** closed value set, when the schema pins one */
  enum?: string[]
  /** value language annotation (cel-expression · jq) when the schema marks one */
  format?: string
  /** the schema's own regex (the word's, or its items') */
  pattern?: string
  /** the schema's own description — the teaching voice, never prose */
  desc?: string
}

export interface LanguageWord {
  /** the key as an author types it */
  word: string
  /** one of the four verbs (its room lives at /verbs/:name) */
  verb: boolean
  /** every declaration of this word, surface reading order */
  decls: WordDecl[]
}

/** the language's surfaces, reading order (the register's groups) */
export const LANGUAGE_SCOPES = [
  {
    "scope": "envelope",
    "blurb": "the file itself"
  },
  {
    "scope": "workflow",
    "blurb": "inside workflow:"
  },
  {
    "scope": "task",
    "blurb": "one step of the plan"
  },
  {
    "scope": "infer",
    "blurb": "inside infer:"
  },
  {
    "scope": "exec",
    "blurb": "inside exec:"
  },
  {
    "scope": "invoke",
    "blurb": "inside invoke:"
  },
  {
    "scope": "agent",
    "blurb": "inside agent:"
  },
  {
    "scope": "retry",
    "blurb": "inside retry:"
  },
  {
    "scope": "on_error",
    "blurb": "inside on_error:"
  },
  {
    "scope": "on_finally",
    "blurb": "inside an on_finally step"
  }
] as const

/** every unique word the schema declares, sorted. */
export const LANGUAGE_WORDS: LanguageWord[] = [
  {
    "word": "after",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object",
        "desc": "The CONTROL boundary · {producer-task: predicate}. Each entry is one control edge (spec/03-dag.md §after). State, never data — observe outcomes through with:."
      }
    ]
  },
  {
    "word": "agent",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "args",
    "verb": false,
    "decls": [
      {
        "scope": "invoke",
        "required": false,
        "type": "object",
        "desc": "Arguments passed to the tool · an object whose shape is the TOOL's own schema, not the language's. Each builtin and each MCP tool declares its own (spec/02-verbs.md §invoke) · `${{ }}` may appear in any leaf value."
      }
    ]
  },
  {
    "word": "backoff_max_ms",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "integer",
        "desc": "Ceiling on the computed delay, in milliseconds · default 60000, one minute. Exponential growth stops climbing here."
      }
    ]
  },
  {
    "word": "backoff_ms",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "integer",
        "desc": "Initial delay between attempts, in milliseconds · default 1000. `backoff_strategy` decides how it grows from there."
      }
    ]
  },
  {
    "word": "backoff_strategy",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "string",
        "enum": [
          "fixed",
          "linear",
          "exponential"
        ],
        "desc": "Which curve the delay follows between attempts · `fixed` · `linear` · `exponential` · default `exponential`. Each attempt waits `backoff_ms` flat, `backoff_ms × attempt`, or `backoff_ms × 2^(attempt-1)` capped at `backoff_max_ms`."
      }
    ]
  },
  {
    "word": "capture",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "enum": [
          "stdout",
          "stderr",
          "combined",
          "structured"
        ],
        "desc": "Which stream becomes the task's output · `stdout` (default) · `stderr` · `combined` · `structured` = `{ stdout, stderr, exit_code }`. This is the SOURCE; `decode:` is how that string becomes a value."
      }
    ]
  },
  {
    "word": "command",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "array",
        "desc": "argv — the program and its arguments, execve, NO shell. Each element substituted independently (the injection-safe form). Shell features (pipes · redirects · globs) live in `shell:`."
      }
    ]
  },
  {
    "word": "config",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Typed non-sensitive runtime config · `${{ config.X }}` · supplied by the deployment or environment, may appear in logs (R3a · LAW-SURFACE-0201 · succeeds the dead `env:` block). Each entry is a typed declaration; a `default:` MUST conform to `type:` (LAW-TYPE-0211 · NIKA-DEFAULT-001)."
      }
    ]
  },
  {
    "word": "const",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Named constants · `${{ const.X }}` · a fixed value baked into the workflow (R3a · LAW-SURFACE-0201 · the literal half of the dead `vars:` block · everything that is not required:true lands here per the E-split total rule). Either a bare literal, or a `{ type, value }` typed constant whose `value:` MUST conform to `type:`."
      }
    ]
  },
  {
    "word": "cwd",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "desc": "Working directory for the subprocess · default = the engine's own cwd."
      }
    ]
  },
  {
    "word": "declassify",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "array",
        "desc": "The ONLY door through the permit-parameterization taint (spec/10-authority.md §the permit-parameterization taint · NEP-0004 · LAW-AUTH-0325) · each entry raises ONE binding from untrusted to trusted, check-visible and receipt-recorded. Lifts the taint law only — the value is still matched against the declared boundary (never a permit bypass)."
      }
    ]
  },
  {
    "word": "decode",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "enum": [
          "text",
          "json",
          "jsonl",
          "bytes"
        ],
        "desc": "How the captured string becomes a value (spec 09 §decode) — illegal with capture: structured (NIKA-PARSE-025)"
      }
    ]
  },
  {
    "word": "description",
    "verb": false,
    "decls": [
      {
        "scope": "workflow",
        "required": false,
        "type": "string",
        "desc": "Free-form prose about the workflow · documentation for whoever reads the file, never read by the engine (spec/01-envelope.md)."
      }
    ]
  },
  {
    "word": "env",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "object",
        "desc": "OS environment variables for THIS subprocess · a key→value map applied over the composed environment. Nothing is inherited — the ambient environment reaches a task only through `permits.env` (spec/01-envelope.md §permits)."
      }
    ]
  },
  {
    "word": "exec",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "fail_fast",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "boolean",
        "desc": "for_each abort-on-error · default true."
      }
    ]
  },
  {
    "word": "fail_workflow",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false,
        "type": "boolean",
        "desc": "Fail the whole workflow on this error · the written-down form of the default, so a reader sees the choice instead of inferring it. Exactly one of `recover` · `skip` · `fail_workflow`."
      }
    ]
  },
  {
    "word": "for_each",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string | array",
        "desc": "Map this task over a collection · `${{ ... }}` reference OR a literal array."
      }
    ]
  },
  {
    "word": "id",
    "verb": false,
    "decls": [
      {
        "scope": "workflow",
        "required": true,
        "type": "string",
        "pattern": "^[a-z][a-z0-9-]*$",
        "desc": "Workflow id · kebab-case · the document-type discriminator (W1: the envelope became an object)."
      }
    ]
  },
  {
    "word": "inert",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string",
        "desc": "The honest door of the data-as-code sink (spec/10-authority.md §the data-as-code sink · NEP-0006 · LAW-AUTH-0327) · declares this task's fetch a code-bearing artifact it will never load or run · the non-empty string IS the justification · lifts the sink law only, never the net boundary or the SSRF floor."
      }
    ]
  },
  {
    "word": "infer",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "inputs",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Typed workflow inputs · `${{ inputs.X }}` · the parameters an author declares and a caller supplies (R3a · LAW-SURFACE-0201 · the typed half of the dead `vars:` block · a required:true value lands here per the E-split total rule). Each entry is a typed declaration whose `type:` speaks the full TypeExpr of 09-types (R3b · LAW-GRAMMAR-0211 · the flat 6-enum is dead · LAW-SURFACE-0211)."
      }
    ]
  },
  {
    "word": "invoke",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "jitter",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "boolean",
        "desc": "Randomize the computed delay so tasks retrying the same upstream do not synchronize · default TRUE. Engines SHOULD use a full-jitter or equal-jitter family — the anti-thundering-herd default (spec/05-errors.md §Retry policy)."
      }
    ]
  },
  {
    "word": "max_attempts",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": true,
        "type": "integer",
        "desc": "Total attempts, counting the first try · integer ≥ 1 · the one required field of a `retry:` block. Engines honor it strictly and surface the LAST error if every attempt fails (spec/05-errors.md §Retry policy)."
      }
    ]
  },
  {
    "word": "max_parallel",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "integer",
        "desc": "Cap concurrent for_each iterations · default unbounded · 1 = sequential."
      }
    ]
  },
  {
    "word": "max_tokens",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "integer | string"
      }
    ]
  },
  {
    "word": "max_tokens_total",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "integer | string",
        "desc": "Cumulative token budget across every turn of the loop · the SPEND ceiling, where `max_turns` is the step ceiling. Default is engine-configurable (spec/02-verbs.md §agent)."
      }
    ]
  },
  {
    "word": "max_turns",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "integer | string"
      }
    ]
  },
  {
    "word": "model",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "string",
        "desc": "Default model · `<provider>/<name>` (e.g. ollama/qwen3.5:9b · anthropic/claude-sonnet-4-6 · mock/echo)."
      },
      {
        "scope": "infer",
        "required": false,
        "type": "string"
      },
      {
        "scope": "agent",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "nika",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "\"v1\"",
        "desc": "Language contract version · exactly `v1` for the v1 lifetime. NOT `v1.0` · `1` · `1.0`."
      }
    ]
  },
  {
    "word": "on_codes",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "array",
        "pattern": "^NIKA-[A-Z]{2,9}(-[A-Z][A-Z0-9_]{1,15})?-[0-9]{3}$",
        "desc": "Retry ONLY on these canonical `NIKA-<NS>-<NNN>` codes · absent, the engine retries anything transient. Codes, never HTTP status numbers · the retry-side mirror of `on_error.on_codes`."
      },
      {
        "scope": "on_error",
        "required": false,
        "type": "array",
        "pattern": "^NIKA-[A-Z]{2,9}(-[A-Z][A-Z0-9_]{1,15})?-[0-9]{3}$",
        "desc": "Optional catch-side filter (mirror of retry.on_codes · same regex) · the action applies ONLY when the final error code is listed · unlisted codes fall through to the default fail (spec/05-errors.md §Fields)."
      }
    ]
  },
  {
    "word": "on_error",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false
      }
    ]
  },
  {
    "word": "on_finally",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "array",
        "desc": "Cleanup mini-tasks · ALWAYS run (success/fail/timeout/cancel) · sequential · best-effort."
      }
    ]
  },
  {
    "word": "output",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object",
        "format": "jq",
        "desc": "Named jq-expression bindings · `${{ tasks.X.<name> }}`. jq is the single data extraction-and-transform language (the former RFC 9535 JSONPath was dropped · jq is a superset · per spec/04-variables.md §216-225). Reserved names forbidden at parse time (spec/04-variables.md §Rules): output · status · error · started_at · ended_at · duration_ms — enforced via propertyNames."
      }
    ]
  },
  {
    "word": "outputs",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "The workflow's return value · symmetric to inputs. Each entry is a `${{ tasks.X.output }}` reference (untyped form · string) OR a typed declaration { value · type · description }. Powers `nika run` result + the output half of the callable-workflow schema."
      }
    ]
  },
  {
    "word": "permits",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "The declared capability boundary · once present every category is default-deny unless listed (spec/01-envelope.md §permits · NIKA-SEC-004)."
      }
    ]
  },
  {
    "word": "policy",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Named workflow law · hard families (require/forbid/allow/limits) are judged at check (NIKA-POLICY-001) · soft families (prefer/optimize) are recorded, never judged in v1 (spec/10-authority.md)."
      }
    ]
  },
  {
    "word": "prompt",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": true,
        "type": "string"
      },
      {
        "scope": "agent",
        "required": true,
        "type": "string"
      }
    ]
  },
  {
    "word": "recover",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false,
        "desc": "Recovery output · a `${{ }}` ref OR a literal (merges the former fallback/value per spec/05-errors.md)."
      }
    ]
  },
  {
    "word": "retry",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "desc": "Retry policy for this task · `{ max_attempts, backoff_ms, backoff_strategy, backoff_max_ms, jitter, on_codes }`. Retries run BEFORE `on_error` sees anything — the catch handles the last error only (spec/05-errors.md §Retry policy)."
      }
    ]
  },
  {
    "word": "returns",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "desc": "The task's output contract (spec 09-types.md) — exclusive with a verb-level schema: (NIKA-TYPE-003)"
      }
    ]
  },
  {
    "word": "run",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "The run's entropy + clock declaration (NEP-0010) · every source of randomness and time is declared, never ambient · the dimensions couple: only ambient×system (the status quo) and none|seeded×virtual (the deterministic states) are legal · a contradiction refuses at parse (NIKA-PARSE-026 ambient×virtual · NIKA-PARSE-027 none|seeded×system) and a strict declaration contradicted by the body refuses at check (NIKA-PARSE-028)."
      }
    ]
  },
  {
    "word": "schema",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "object",
        "desc": "JSON Schema · structured output contract."
      },
      {
        "scope": "agent",
        "required": false,
        "type": "object",
        "desc": "JSON Schema · validate the agent's final message as structured output."
      }
    ]
  },
  {
    "word": "secrets",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Vault-backed masked references · `${{ secrets.X }}` · never inline literals."
      }
    ]
  },
  {
    "word": "shell",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "desc": "One shell line, run via /bin/sh -c — the EXPLICIT dangerous door (pipes · redirects · globs). The blocklist applies here; interpolating untrusted values here is on the author. Exactly one of command|shell."
      }
    ]
  },
  {
    "word": "skills",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "array",
        "desc": "Agent Skill (SKILL.md) file paths · agentskills.io shape · explicit static paths only (no globs · no templates) · loaded at compose time and injected into the system context."
      }
    ]
  },
  {
    "word": "skip",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false,
        "type": "boolean",
        "desc": "Swallow the error and let the DAG continue · the task produces no output, and the original error stays readable at `tasks.<id>.error`. Exactly one of `recover` · `skip` · `fail_workflow`."
      }
    ]
  },
  {
    "word": "stdin",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "desc": "Data written to the command's standard input · may interpolate `${{ }}`."
      }
    ]
  },
  {
    "word": "system",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "string",
        "desc": "System prompt · the standing instruction, sent ahead of `prompt:` and unchanged by it."
      },
      {
        "scope": "agent",
        "required": false,
        "type": "string",
        "desc": "System prompt · the standing instruction, sent ahead of `prompt:` and unchanged by any turn of the loop."
      }
    ]
  },
  {
    "word": "tasks",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "object",
        "desc": "The task map · the KEY is the task's identity (snake_case · CEL-safe). Source order is presentation only — the graph alone schedules."
      }
    ]
  },
  {
    "word": "temperature",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "number | string",
        "desc": "0-2 · number or `${{ }}`."
      },
      {
        "scope": "agent",
        "required": false,
        "type": "number | string"
      }
    ]
  },
  {
    "word": "thinking",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "object",
        "desc": "Extended thinking · `{ enabled, budget_tokens }` — reasoning the model may spend before it answers (spec/02-verbs.md §infer)."
      }
    ]
  },
  {
    "word": "timeout",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string",
        "pattern": "^[0-9]+(\\.[0-9]+)?(ns|us|µs|ms|s|m|h)([0-9]+(\\.[0-9]+)?(ns|us|µs|ms|s|m|h))*$",
        "desc": "Go-duration string · quoted · e.g. \"30s\" \"5m\" \"1h30m\" \"2.5s\". Max 24h."
      },
      {
        "scope": "on_finally",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "tool",
    "verb": false,
    "decls": [
      {
        "scope": "invoke",
        "required": false,
        "type": "string",
        "pattern": "^mcp:[a-z][a-z0-9-]*/[A-Za-z0-9_/-]+$",
        "desc": "Tool reference · nika:<path> (closed v0.1 builtin set) OR mcp:<server>/<tool> (requires the slash). The namespace set is CLOSED at v1 (spec/02-verbs.md) — an x-<vendor>: prefix is RESERVED, not valid (engine-specific tools route through mcp: · spec/06-stdlib-contract.md §Namespace ownership)."
      }
    ]
  },
  {
    "word": "tools",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "array",
        "desc": "Whitelist · DEFAULT-DENY (no tools if absent) · gitignore-style globs · `!` negation."
      }
    ]
  },
  {
    "word": "types",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object",
        "desc": "Named type declarations (spec 09-types.md · PascalCase · acyclic)"
      }
    ]
  },
  {
    "word": "vision",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "array",
        "desc": "Image inputs for the call · each entry `{ source: file | url, path | url }` · the images `prompt:` is allowed to refer to."
      }
    ]
  },
  {
    "word": "when",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "boolean | string",
        "format": "cel-expression",
        "desc": "LOCAL business condition · evaluated POST-gate over {vars · env · with · item · index} — tasks.* is illegal here (NIKA-VAR-021 · hoist into with:). false → skipped (spec/03-dag.md §when)."
      },
      {
        "scope": "on_finally",
        "required": false,
        "type": "boolean | string",
        "format": "cel-expression",
        "desc": "Cleanup condition · may read the PARENT task's record (tasks.<parent>.status / .error — the only legal tasks.* target inside on_finally · spec/03-dag.md §on_finally)."
      }
    ]
  },
  {
    "word": "with",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object",
        "desc": "Task-level scope injection · `${{ with.X }}`."
      }
    ]
  },
  {
    "word": "workflow",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "object",
        "desc": "The workflow object · a stable home for identity and metadata (W1 'the map')."
      },
      {
        "scope": "invoke",
        "required": false,
        "type": "string",
        "desc": "Compose another workflow (spec 14) · a STATIC target: a filesystem path OR registry:owner/name@version (pinned). A templated target is refused at check (NIKA-COMP-001). Exactly one of tool: | workflow: (the invoke tagged union · G21)."
      }
    ]
  }
]

/** word → entry (the /language/:word lookup). */
export const WORD_INDEX: Record<string, LanguageWord> = Object.fromEntries(
  LANGUAGE_WORDS.map((w) => [w.word, w]),
)
