// language.generated.ts — AUTO-GENERATED by scripts/build-language.mjs
// from public/schema/workflow.json (the served contract — the same file
// editors and the engine validate against). DO NOT EDIT · regenerate:
//   node scripts/build-language.mjs
// Drift gate: src/test/language.test.ts recompiles and byte-diffs, and
// pins the verb-flagged set against CANON.verbNames.

export interface WordDecl {
  /** where the word speaks (envelope · task · a verb block · the leashes) */
  scope: string
  /** required at that surface (a miss is a schema finding) */
  required: boolean
  /** the schema's own type label, when it declares one */
  type?: string
  /** closed value set, when the schema pins one */
  enum?: string[]
  /** value language annotation (cel-expression · jq) when the schema marks one */
  format?: string
  /** the schema's own regex (the word's, or its items') */
  pattern?: string
}

export interface LanguageWord {
  /** the key as an author types it */
  word: string
  /** one of the four verbs (its room lives at /verbs/:name) */
  verb: boolean
  /** every declaration of this word, surface reading order */
  decls: WordDecl[]
}

/** the language's surfaces, reading order (the register's groups) */
export const LANGUAGE_SCOPES = [
  {
    "scope": "envelope",
    "blurb": "the file itself"
  },
  {
    "scope": "workflow",
    "blurb": "inside workflow:"
  },
  {
    "scope": "task",
    "blurb": "one step of the plan"
  },
  {
    "scope": "infer",
    "blurb": "inside infer:"
  },
  {
    "scope": "exec",
    "blurb": "inside exec:"
  },
  {
    "scope": "invoke",
    "blurb": "inside invoke:"
  },
  {
    "scope": "agent",
    "blurb": "inside agent:"
  },
  {
    "scope": "retry",
    "blurb": "inside retry:"
  },
  {
    "scope": "on_error",
    "blurb": "inside on_error:"
  },
  {
    "scope": "on_finally",
    "blurb": "inside an on_finally step"
  }
] as const

/** every unique word the schema declares, sorted. */
export const LANGUAGE_WORDS: LanguageWord[] = [
  {
    "word": "after",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "agent",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "args",
    "verb": false,
    "decls": [
      {
        "scope": "invoke",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "backoff_max_ms",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "integer"
      }
    ]
  },
  {
    "word": "backoff_ms",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "integer"
      }
    ]
  },
  {
    "word": "backoff_strategy",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "string",
        "enum": [
          "fixed",
          "linear",
          "exponential"
        ]
      }
    ]
  },
  {
    "word": "capture",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "enum": [
          "stdout",
          "stderr",
          "combined",
          "structured"
        ]
      }
    ]
  },
  {
    "word": "command",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "config",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "const",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "cwd",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "declassify",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "decode",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string",
        "enum": [
          "text",
          "json",
          "jsonl",
          "bytes"
        ]
      }
    ]
  },
  {
    "word": "description",
    "verb": false,
    "decls": [
      {
        "scope": "workflow",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "env",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "exec",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "fail_fast",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  {
    "word": "fail_workflow",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  {
    "word": "for_each",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string | array"
      }
    ]
  },
  {
    "word": "id",
    "verb": false,
    "decls": [
      {
        "scope": "workflow",
        "required": true,
        "type": "string",
        "pattern": "^[a-z][a-z0-9-]*$"
      }
    ]
  },
  {
    "word": "inert",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "infer",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "inputs",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "invoke",
    "verb": true,
    "decls": [
      {
        "scope": "task",
        "required": false
      },
      {
        "scope": "on_finally",
        "required": false
      }
    ]
  },
  {
    "word": "jitter",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  {
    "word": "max_attempts",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": true,
        "type": "integer"
      }
    ]
  },
  {
    "word": "max_parallel",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "integer"
      }
    ]
  },
  {
    "word": "max_tokens",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "integer | string"
      }
    ]
  },
  {
    "word": "max_tokens_total",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "integer | string"
      }
    ]
  },
  {
    "word": "max_turns",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "integer | string"
      }
    ]
  },
  {
    "word": "model",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "string"
      },
      {
        "scope": "infer",
        "required": false,
        "type": "string"
      },
      {
        "scope": "agent",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "nika",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "\"v1\""
      }
    ]
  },
  {
    "word": "on_codes",
    "verb": false,
    "decls": [
      {
        "scope": "retry",
        "required": false,
        "type": "array",
        "pattern": "^NIKA-[A-Z]{2,9}(-[A-Z][A-Z0-9_]{1,15})?-[0-9]{3}$"
      },
      {
        "scope": "on_error",
        "required": false,
        "type": "array",
        "pattern": "^NIKA-[A-Z]{2,9}(-[A-Z][A-Z0-9_]{1,15})?-[0-9]{3}$"
      }
    ]
  },
  {
    "word": "on_error",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false
      }
    ]
  },
  {
    "word": "on_finally",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "output",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object",
        "format": "jq"
      }
    ]
  },
  {
    "word": "outputs",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "permits",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "policy",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "prompt",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": true,
        "type": "string"
      },
      {
        "scope": "agent",
        "required": true,
        "type": "string"
      }
    ]
  },
  {
    "word": "recover",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false
      }
    ]
  },
  {
    "word": "retry",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false
      }
    ]
  },
  {
    "word": "returns",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false
      }
    ]
  },
  {
    "word": "run",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "schema",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "object"
      },
      {
        "scope": "agent",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "secrets",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "shell",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "skills",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "skip",
    "verb": false,
    "decls": [
      {
        "scope": "on_error",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  {
    "word": "stdin",
    "verb": false,
    "decls": [
      {
        "scope": "exec",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "system",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "string"
      },
      {
        "scope": "agent",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "tasks",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "object"
      }
    ]
  },
  {
    "word": "temperature",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "number | string"
      },
      {
        "scope": "agent",
        "required": false,
        "type": "number | string"
      }
    ]
  },
  {
    "word": "thinking",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "timeout",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "string",
        "pattern": "^[0-9]+(\\.[0-9]+)?(ns|us|µs|ms|s|m|h)([0-9]+(\\.[0-9]+)?(ns|us|µs|ms|s|m|h))*$"
      },
      {
        "scope": "on_finally",
        "required": false,
        "type": "string"
      }
    ]
  },
  {
    "word": "tool",
    "verb": false,
    "decls": [
      {
        "scope": "invoke",
        "required": false,
        "type": "string",
        "pattern": "^mcp:[a-z][a-z0-9-]*/[A-Za-z0-9_/-]+$"
      }
    ]
  },
  {
    "word": "tools",
    "verb": false,
    "decls": [
      {
        "scope": "agent",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "types",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "vision",
    "verb": false,
    "decls": [
      {
        "scope": "infer",
        "required": false,
        "type": "array"
      }
    ]
  },
  {
    "word": "when",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "boolean | string",
        "format": "cel-expression"
      },
      {
        "scope": "on_finally",
        "required": false,
        "type": "boolean | string",
        "format": "cel-expression"
      }
    ]
  },
  {
    "word": "with",
    "verb": false,
    "decls": [
      {
        "scope": "task",
        "required": false,
        "type": "object"
      }
    ]
  },
  {
    "word": "workflow",
    "verb": false,
    "decls": [
      {
        "scope": "envelope",
        "required": true,
        "type": "object"
      },
      {
        "scope": "invoke",
        "required": false,
        "type": "string"
      }
    ]
  }
]

/** word → entry (the /language/:word lookup). */
export const WORD_INDEX: Record<string, LanguageWord> = Object.fromEntries(
  LANGUAGE_WORDS.map((w) => [w.word, w]),
)
