// lens-bases.generated.ts — AUTO-GENERATED by scripts/lens/graph/build-lens.mjs from
// scripts/lens/graph/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/lens/graph/build-lens.mjs
// Drift gate: src/test/lens.test.ts recompiles and byte-diffs.

/** every roomed family's URL prefix, derived from the descriptor.
 * A link built from these follows a family that moves; a link built from a
 * literal keeps pointing at the doorway the move left behind. */
export const ROOM_BASES: Record<string, string> = {
 "builtins": "/language/stdlib",
 "error-codes": "/errors",
 "showcases": "/workflows/jobs",
 "templates": "/workflows/skeletons",
 "verbs": "/language/verbs",
 "words": "/language/words"
}
