// lens-nav.generated.ts — AUTO-GENERATED by scripts/lens/graph/build-lens.mjs from
// scripts/lens/graph/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/lens/graph/build-lens.mjs
// Drift gate: src/test/lens.test.ts recompiles and byte-diffs.

/** the chrome as projection (§4.11-4.12): the Reference panel, the Product
 * panel (authored in the descriptor) and the footer's five columns. Soon
 * flags and counts are RESOLVED against the graph — a hub landing flips
 * them here, never in Nav.tsx. Docs/GitHub hrefs stay content.ts consts
 * (external: true marks them). */
export interface NavItem {
  label: string
  to?: string
  href?: string
  external?: boolean
  icon?: string
  /** anchored sub-door of the row above (one path, one door — §4.11) */
  sub?: boolean
  /** the derived register count (a one-token receipt · rendered as a chip) */
  count?: number
  /** what the count counts — authored, so the chip reads « 62 words » */
  unit?: string
  /** the HUD readout on the featured row · [n, noun] pairs, derived */
  stats?: [number, string][]
  /** the lens layer the destination belongs to — the row wears its colour */
  layer?: string
  /** the surface has not landed yet (wave slot or a WO ahead) */
  soon?: boolean
  slot_wave?: string | null
  lands?: string | null
  slot?: boolean
  title?: string
  desc?: string
}

export const NAV_BAR_LINKS: NavItem[] = [
  {
    "label": "How it works",
    "to": "/how"
  },
  {
    "label": "The language",
    "to": "/language"
  },
  {
    "label": "Workflows",
    "to": "/workflows"
  },
  {
    "label": "Catalog",
    "to": "/catalog"
  },
  {
    "label": "Docs",
    "external": true
  },
  {
    "label": "Blog",
    "to": "/blog"
  }
]

export const NAV_VERSION_PILL = {
  "to": "/changelog",
  "title": "shipping in the open · the ship log"
} as const

export const FOOTER_COLS: { kick: string; items: NavItem[] }[] = [
  {
    "kick": "How it works",
    "items": [
      {
        "label": "The loop",
        "to": "/how"
      },
      {
        "label": "The router",
        "to": "/how/router"
      },
      {
        "label": "The flow",
        "to": "/how/flow"
      },
      {
        "label": "The boundary",
        "to": "/how/boundary"
      },
      {
        "label": "The proof",
        "to": "/how/proof"
      },
      {
        "label": "The MCP oracle",
        "to": "/how/oracle"
      }
    ]
  },
  {
    "kick": "The language",
    "items": [
      {
        "label": "Every word",
        "to": "/language"
      },
      {
        "label": "The four verbs",
        "to": "/language/verbs"
      },
      {
        "label": "The specification",
        "to": "/language/spec"
      },
      {
        "label": "Governance",
        "to": "/language/governance"
      },
      {
        "label": "Error codes",
        "to": "/language/errors"
      },
      {
        "label": "Standard library",
        "to": "/language/stdlib"
      },
      {
        "label": "Types",
        "to": "/language/types"
      },
      {
        "label": "Permits",
        "to": "/language/permits"
      },
      {
        "label": "Conformance",
        "to": "/language/conformance"
      }
    ]
  },
  {
    "kick": "Workflows",
    "items": [
      {
        "label": "The corpus",
        "to": "/workflows"
      },
      {
        "label": "The teaching path",
        "to": "/workflows/path/01-hello"
      },
      {
        "label": "Real jobs",
        "to": "/workflows/jobs"
      },
      {
        "label": "Skeletons",
        "to": "/workflows/skeletons"
      },
      {
        "label": "Playground",
        "to": "/play"
      },
      {
        "label": "Learn it in 5 min",
        "to": "/learn"
      }
    ]
  },
  {
    "kick": "What it knows",
    "items": [
      {
        "label": "The catalog",
        "to": "/catalog"
      },
      {
        "label": "Models",
        "to": "/catalog/models"
      },
      {
        "label": "Providers",
        "to": "/catalog/providers"
      },
      {
        "label": "Pricing",
        "to": "/catalog/pricing"
      },
      {
        "label": "Energy",
        "to": "/catalog/energy"
      },
      {
        "label": "MCP servers",
        "to": "/catalog/mcp"
      },
      {
        "label": "Embeddings",
        "to": "/catalog/embeddings"
      },
      {
        "label": "Capability rules",
        "to": "/catalog/capabilities"
      }
    ]
  },
  {
    "kick": "Get it running",
    "items": [
      {
        "label": "Install",
        "to": "/install"
      },
      {
        "label": "Wire your client",
        "to": "/integrations"
      },
      {
        "label": "Registry",
        "to": "/integrations/registry"
      },
      {
        "label": "VS Code extension",
        "to": "/integrations/vscode"
      },
      {
        "label": "Homebrew tap",
        "to": "/integrations/homebrew"
      },
      {
        "label": "Send a workflow",
        "to": "/convert"
      }
    ]
  },
  {
    "kick": "The project",
    "items": [
      {
        "label": "The map",
        "to": "/map"
      },
      {
        "label": "The city",
        "to": "/city"
      },
      {
        "label": "The decisions",
        "to": "/city/decisions"
      },
      {
        "label": "The truth system",
        "to": "/truth"
      },
      {
        "label": "Releases",
        "to": "/releases"
      },
      {
        "label": "Changelog",
        "to": "/changelog"
      },
      {
        "label": "Timeline",
        "to": "/timeline"
      },
      {
        "label": "Manifesto",
        "to": "/manifesto"
      },
      {
        "label": "Design system",
        "to": "/brand"
      },
      {
        "label": "Blog",
        "to": "/blog"
      },
      {
        "label": "GitHub",
        "external": true
      }
    ]
  }
]

export const FOOTER_MACHINE: { label: string; href: string }[] =
  [
  {
    "label": "llms.txt",
    "href": "/llms.txt"
  },
  {
    "label": "sitemap.xml",
    "href": "/sitemap.xml"
  },
  {
    "label": "nika-graph.json",
    "href": "/nika-graph.json"
  },
  {
    "label": "schema",
    "href": "/schema/workflow.json"
  },
  {
    "label": "errors",
    "href": "/errors/catalog.json"
  }
]
