// member-rooms.generated.ts — AUTO-GENERATED by scripts/atlas/build-atlas.mjs from
// scripts/atlas/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/atlas/build-atlas.mjs
// Drift gate: src/test/atlas.test.ts recompiles and byte-diffs.

/** the generic member-room registry (rooms universelles · one route, every
 * family): family URL segment → set identity + ordered members. The room's
 * BODY comes from the lazy graph (readoutFor · the inspector's renderer) —
 * this module stays chrome-lean by law. */
export interface MemberRoomEntry {
  id: string
  title: string
  url: string
  /** the atlas node id (readoutFor's key · TruthLine's key) */
  node: string
  /** the member's one-line teaching (its graph opener · roots render it) */
  gloss?: string
}
export interface MemberRoomFamily {
  set: string
  title: string
  /** the register view this family's members anchor on (the parent door) */
  hub: string
  members: MemberRoomEntry[]
}
export const MEMBER_ROOM_FAMILIES: Record<string, MemberRoomFamily> = {
  "namespaces": {
    "set": "namespaces",
    "title": "The namespaces",
    "hub": "/language",
    "members": [
      {
        "id": "config",
        "title": "config",
        "url": "/namespaces/config",
        "node": "ns:config"
      },
      {
        "id": "const",
        "title": "const",
        "url": "/namespaces/const",
        "node": "ns:const"
      },
      {
        "id": "inputs",
        "title": "inputs",
        "url": "/namespaces/inputs",
        "node": "ns:inputs"
      },
      {
        "id": "secrets",
        "title": "secrets",
        "url": "/namespaces/secrets",
        "node": "ns:secrets"
      },
      {
        "id": "tasks",
        "title": "tasks",
        "url": "/namespaces/tasks",
        "node": "ns:tasks"
      },
      {
        "id": "with",
        "title": "with",
        "url": "/namespaces/with",
        "node": "ns:with"
      }
    ]
  },
  "types": {
    "set": "types",
    "title": "The types",
    "hub": "/language",
    "members": [
      {
        "id": "bool",
        "title": "bool",
        "url": "/types/bool",
        "node": "type:bool"
      },
      {
        "id": "bytes",
        "title": "bytes",
        "url": "/types/bytes",
        "node": "type:bytes"
      },
      {
        "id": "duration",
        "title": "duration",
        "url": "/types/duration",
        "node": "type:duration"
      },
      {
        "id": "integer",
        "title": "integer",
        "url": "/types/integer",
        "node": "type:integer"
      },
      {
        "id": "null",
        "title": "null",
        "url": "/types/null",
        "node": "type:null"
      },
      {
        "id": "number",
        "title": "number",
        "url": "/types/number",
        "node": "type:number"
      },
      {
        "id": "path",
        "title": "path",
        "url": "/types/path",
        "node": "type:path"
      },
      {
        "id": "string",
        "title": "string",
        "url": "/types/string",
        "node": "type:string"
      },
      {
        "id": "timestamp",
        "title": "timestamp",
        "url": "/types/timestamp",
        "node": "type:timestamp"
      },
      {
        "id": "uri",
        "title": "uri",
        "url": "/types/uri",
        "node": "type:uri"
      }
    ]
  },
  "edges": {
    "set": "edge-kinds",
    "title": "The edge kinds",
    "hub": "/flow",
    "members": [
      {
        "id": "control",
        "title": "control",
        "url": "/edges/control",
        "node": "edgekind:control",
        "gloss": "an after entry · carries its gate predicate"
      },
      {
        "id": "failure-observation",
        "title": "failure-observation",
        "url": "/edges/failure-observation",
        "node": "edgekind:failure-observation",
        "gloss": "an error read in with · flows only when the producer failed"
      },
      {
        "id": "finally",
        "title": "finally",
        "url": "/edges/finally",
        "node": "edgekind:finally",
        "gloss": "reserved · named so the enum is complete before the trace wave gives cleanup identity"
      },
      {
        "id": "recovery",
        "title": "recovery",
        "url": "/edges/recovery",
        "node": "edgekind:recovery",
        "gloss": "an on_error.recover reference · a parking read, not an ordering edge"
      },
      {
        "id": "terminal-observation",
        "title": "terminal-observation",
        "url": "/edges/terminal-observation",
        "node": "edgekind:terminal-observation",
        "gloss": "a status or timing read in with · settles with the producer"
      },
      {
        "id": "value",
        "title": "value",
        "url": "/edges/value",
        "node": "edgekind:value",
        "gloss": "a with binding referencing a task output · carries the binding name"
      }
    ]
  },
  "predicates": {
    "set": "gate-predicates",
    "title": "The gate predicates",
    "hub": "/flow",
    "members": [
      {
        "id": "failure",
        "title": "failure",
        "url": "/predicates/failure",
        "node": "predicate:failure",
        "gloss": "fire when the producer failed terminally"
      },
      {
        "id": "skipped",
        "title": "skipped",
        "url": "/predicates/skipped",
        "node": "predicate:skipped",
        "gloss": "fire when the producer was gated out"
      },
      {
        "id": "success",
        "title": "success",
        "url": "/predicates/success",
        "node": "predicate:success",
        "gloss": "fire when the producer completed clean"
      },
      {
        "id": "terminal",
        "title": "terminal",
        "url": "/predicates/terminal",
        "node": "predicate:terminal",
        "gloss": "fire when the producer reached any terminal state"
      }
    ]
  },
  "families": {
    "set": "tool-families",
    "title": "The tool families",
    "hub": "/tools",
    "members": [
      {
        "id": "core",
        "title": "core",
        "url": "/families/core",
        "node": "family:core"
      },
      {
        "id": "data",
        "title": "data",
        "url": "/families/data",
        "node": "family:data"
      },
      {
        "id": "file",
        "title": "file",
        "url": "/families/file",
        "node": "family:file"
      },
      {
        "id": "introspection",
        "title": "introspection",
        "url": "/families/introspection",
        "node": "family:introspection"
      },
      {
        "id": "media",
        "title": "media",
        "url": "/families/media",
        "node": "family:media"
      },
      {
        "id": "network",
        "title": "network",
        "url": "/families/network",
        "node": "family:network"
      }
    ]
  },
  "providers": {
    "set": "providers",
    "title": "The providers",
    "hub": "/providers",
    "members": [
      {
        "id": "anthropic",
        "title": "Anthropic Claude",
        "url": "/providers/anthropic",
        "node": "provider:anthropic",
        "gloss": "Claude models (Opus, Sonnet, Haiku)."
      },
      {
        "id": "deepseek",
        "title": "DeepSeek",
        "url": "/providers/deepseek",
        "node": "provider:deepseek",
        "gloss": "DeepSeek Chat and Coder models."
      },
      {
        "id": "gemini",
        "title": "Google Gemini",
        "url": "/providers/gemini",
        "node": "provider:gemini",
        "gloss": "Gemini Pro, Flash, and Ultra models."
      },
      {
        "id": "groq",
        "title": "Groq",
        "url": "/providers/groq",
        "node": "provider:groq",
        "gloss": "Fast inference with Llama, Mixtral models."
      },
      {
        "id": "huggingface",
        "title": "Hugging Face",
        "url": "/providers/huggingface",
        "node": "provider:huggingface",
        "gloss": "Inference Providers router · 100+ open-weight models across 18 providers (Groq · Cerebras · Together · Scaleway · OVHcloud · …) · zero markup · :provider or :fastest/:cheapest routing suffix."
      },
      {
        "id": "llamacpp",
        "title": "llama.cpp",
        "url": "/providers/llamacpp",
        "node": "provider:llamacpp",
        "gloss": "llama.cpp server (default port 8080) — serves the loaded GGUF; the wire model id is free-form."
      },
      {
        "id": "lmstudio",
        "title": "LM Studio",
        "url": "/providers/lmstudio",
        "node": "provider:lmstudio",
        "gloss": "LM Studio local server (default port 1234) — serves the loaded model."
      },
      {
        "id": "localai",
        "title": "LocalAI",
        "url": "/providers/localai",
        "node": "provider:localai",
        "gloss": "LocalAI server (default port 8080) — an OpenAI-compatible gateway over local backends."
      },
      {
        "id": "mistral",
        "title": "Mistral AI",
        "url": "/providers/mistral",
        "node": "provider:mistral",
        "gloss": "Mistral Large, Medium, Small models."
      },
      {
        "id": "mock",
        "title": "Mock",
        "url": "/providers/mock",
        "node": "provider:mock",
        "gloss": "Deterministic test responses — no API calls, no keys needed."
      },
      {
        "id": "moonshot",
        "title": "Moonshot (Kimi)",
        "url": "/providers/moonshot",
        "node": "provider:moonshot",
        "gloss": "Moonshot AI — Kimi K2, K2.5 (international endpoint api.moonshot.ai/v1). rig-core native provider."
      },
      {
        "id": "nvidia",
        "title": "NVIDIA",
        "url": "/providers/nvidia",
        "node": "provider:nvidia",
        "gloss": "NVIDIA API (integrate.api.nvidia.com) · Nemotron 3 family (Open Model License · agentic-first) + hosted open models · self-hosted NIM containers expose the same surface."
      },
      {
        "id": "ollama",
        "title": "Ollama",
        "url": "/providers/ollama",
        "node": "provider:ollama",
        "gloss": "Local Ollama server (default port 11434) — serves any pulled model."
      },
      {
        "id": "openai",
        "title": "OpenAI",
        "url": "/providers/openai",
        "node": "provider:openai",
        "gloss": "GPT-5.x, the o-series, and other OpenAI models."
      },
      {
        "id": "openrouter",
        "title": "OpenRouter",
        "url": "/providers/openrouter",
        "node": "provider:openrouter",
        "gloss": "200+ models via unified gateway."
      },
      {
        "id": "vllm",
        "title": "vLLM",
        "url": "/providers/vllm",
        "node": "provider:vllm",
        "gloss": "vLLM server (default port 8000) — serves Hugging Face model ids at throughput."
      },
      {
        "id": "xai",
        "title": "xAI Grok",
        "url": "/providers/xai",
        "node": "provider:xai",
        "gloss": "Grok models (Grok-3, Grok-4)."
      }
    ]
  },
  "modes": {
    "set": "extract-modes",
    "title": "The extract modes",
    "hub": "/tools/fetch",
    "members": [
      {
        "id": "article",
        "title": "article",
        "url": "/modes/article",
        "node": "mode:article"
      },
      {
        "id": "feed",
        "title": "feed",
        "url": "/modes/feed",
        "node": "mode:feed"
      },
      {
        "id": "jq",
        "title": "jq",
        "url": "/modes/jq",
        "node": "mode:jq"
      },
      {
        "id": "links",
        "title": "links",
        "url": "/modes/links",
        "node": "mode:links"
      },
      {
        "id": "markdown",
        "title": "markdown",
        "url": "/modes/markdown",
        "node": "mode:markdown"
      },
      {
        "id": "metadata",
        "title": "metadata",
        "url": "/modes/metadata",
        "node": "mode:metadata"
      },
      {
        "id": "selector",
        "title": "selector",
        "url": "/modes/selector",
        "node": "mode:selector"
      },
      {
        "id": "sitemap",
        "title": "sitemap",
        "url": "/modes/sitemap",
        "node": "mode:sitemap"
      },
      {
        "id": "text",
        "title": "text",
        "url": "/modes/text",
        "node": "mode:text"
      }
    ]
  },
  "permits": {
    "set": "permit-families",
    "title": "The permit families",
    "hub": "/boundary",
    "members": [
      {
        "id": "exec",
        "title": "exec",
        "url": "/permits/exec",
        "node": "permit:exec",
        "gloss": "which commands may run · false kills the family"
      },
      {
        "id": "fs",
        "title": "fs",
        "url": "/permits/fs",
        "node": "permit:fs",
        "gloss": "read and write globs · the walk root is gated"
      },
      {
        "id": "net",
        "title": "net",
        "url": "/permits/net",
        "node": "permit:net",
        "gloss": "http allowlist · the SSRF floor stays on regardless"
      },
      {
        "id": "tools",
        "title": "tools",
        "url": "/permits/tools",
        "node": "permit:tools",
        "gloss": "which nika tools the file may invoke"
      }
    ]
  },
  "secrets": {
    "set": "secret-sources",
    "title": "The secret sources",
    "hub": "/boundary",
    "members": [
      {
        "id": "env",
        "title": "env",
        "url": "/secrets/env",
        "node": "secret:env",
        "gloss": "read from the environment at run time"
      },
      {
        "id": "file",
        "title": "file",
        "url": "/secrets/file",
        "node": "secret:file",
        "gloss": "read from a path the boundary allows"
      },
      {
        "id": "vault",
        "title": "vault",
        "url": "/secrets/vault",
        "node": "secret:vault",
        "gloss": "the OS keychain backend · the default posture"
      }
    ]
  },
  "error-namespaces": {
    "set": "error-namespaces",
    "title": "The error namespaces",
    "hub": "/errors",
    "members": [
      {
        "id": "NIKA-AGENT",
        "title": "NIKA-AGENT",
        "url": "/error-namespaces/NIKA-AGENT",
        "node": "errns:NIKA-AGENT",
        "gloss": "agent: verb errors"
      },
      {
        "id": "NIKA-ASSERT",
        "title": "NIKA-ASSERT",
        "url": "/error-namespaces/NIKA-ASSERT",
        "node": "errns:NIKA-ASSERT"
      },
      {
        "id": "NIKA-BUILTIN",
        "title": "NIKA-BUILTIN",
        "url": "/error-namespaces/NIKA-BUILTIN",
        "node": "errns:NIKA-BUILTIN",
        "gloss": "Builtin tool errors · per-builtin sub-namespace"
      },
      {
        "id": "NIKA-CANCEL",
        "title": "NIKA-CANCEL",
        "url": "/error-namespaces/NIKA-CANCEL",
        "node": "errns:NIKA-CANCEL",
        "gloss": "Task or workflow cancellation"
      },
      {
        "id": "NIKA-COMP",
        "title": "NIKA-COMP",
        "url": "/error-namespaces/NIKA-COMP",
        "node": "errns:NIKA-COMP"
      },
      {
        "id": "NIKA-DAG",
        "title": "NIKA-DAG",
        "url": "/error-namespaces/NIKA-DAG",
        "node": "errns:NIKA-DAG",
        "gloss": "DAG topology · cycles · invalid deps"
      },
      {
        "id": "NIKA-DECIDE",
        "title": "NIKA-DECIDE",
        "url": "/error-namespaces/NIKA-DECIDE",
        "node": "errns:NIKA-DECIDE"
      },
      {
        "id": "NIKA-EXEC",
        "title": "NIKA-EXEC",
        "url": "/error-namespaces/NIKA-EXEC",
        "node": "errns:NIKA-EXEC",
        "gloss": "exec: verb errors"
      },
      {
        "id": "NIKA-IMPL",
        "title": "NIKA-IMPL",
        "url": "/error-namespaces/NIKA-IMPL",
        "node": "errns:NIKA-IMPL",
        "gloss": "Engine internal errors"
      },
      {
        "id": "NIKA-INFER",
        "title": "NIKA-INFER",
        "url": "/error-namespaces/NIKA-INFER",
        "node": "errns:NIKA-INFER",
        "gloss": "infer: verb errors"
      },
      {
        "id": "NIKA-INVOKE",
        "title": "NIKA-INVOKE",
        "url": "/error-namespaces/NIKA-INVOKE",
        "node": "errns:NIKA-INVOKE",
        "gloss": "invoke: verb errors"
      },
      {
        "id": "NIKA-LOCK",
        "title": "NIKA-LOCK",
        "url": "/error-namespaces/NIKA-LOCK",
        "node": "errns:NIKA-LOCK"
      },
      {
        "id": "NIKA-MCP",
        "title": "NIKA-MCP",
        "url": "/error-namespaces/NIKA-MCP",
        "node": "errns:NIKA-MCP",
        "gloss": "MCP client errors"
      },
      {
        "id": "NIKA-PARSE",
        "title": "NIKA-PARSE",
        "url": "/error-namespaces/NIKA-PARSE",
        "node": "errns:NIKA-PARSE",
        "gloss": "YAML parse + envelope validation"
      },
      {
        "id": "NIKA-POLICY",
        "title": "NIKA-POLICY",
        "url": "/error-namespaces/NIKA-POLICY",
        "node": "errns:NIKA-POLICY"
      },
      {
        "id": "NIKA-PORT",
        "title": "NIKA-PORT",
        "url": "/error-namespaces/NIKA-PORT",
        "node": "errns:NIKA-PORT"
      },
      {
        "id": "NIKA-PROVIDER",
        "title": "NIKA-PROVIDER",
        "url": "/error-namespaces/NIKA-PROVIDER",
        "node": "errns:NIKA-PROVIDER",
        "gloss": "Provider adapter errors"
      },
      {
        "id": "NIKA-SEC",
        "title": "NIKA-SEC",
        "url": "/error-namespaces/NIKA-SEC",
        "node": "errns:NIKA-SEC",
        "gloss": "Security policy violations (SSRF · blocklist)"
      },
      {
        "id": "NIKA-TIMEOUT",
        "title": "NIKA-TIMEOUT",
        "url": "/error-namespaces/NIKA-TIMEOUT",
        "node": "errns:NIKA-TIMEOUT",
        "gloss": "Task or step timeouts"
      },
      {
        "id": "NIKA-TYPE",
        "title": "NIKA-TYPE",
        "url": "/error-namespaces/NIKA-TYPE",
        "node": "errns:NIKA-TYPE"
      },
      {
        "id": "NIKA-VAR",
        "title": "NIKA-VAR",
        "url": "/error-namespaces/NIKA-VAR",
        "node": "errns:NIKA-VAR",
        "gloss": "Variable resolution failures"
      }
    ]
  },
  "error-categories": {
    "set": "error-categories",
    "title": "The error categories",
    "hub": "/errors",
    "members": [
      {
        "id": "budget_error",
        "title": "budget_error",
        "url": "/error-categories/budget_error",
        "node": "errcat:budget_error"
      },
      {
        "id": "cancelled",
        "title": "cancelled",
        "url": "/error-categories/cancelled",
        "node": "errcat:cancelled"
      },
      {
        "id": "internal_error",
        "title": "internal_error",
        "url": "/error-categories/internal_error",
        "node": "errcat:internal_error"
      },
      {
        "id": "network_error",
        "title": "network_error",
        "url": "/error-categories/network_error",
        "node": "errcat:network_error"
      },
      {
        "id": "parse_error",
        "title": "parse_error",
        "url": "/error-categories/parse_error",
        "node": "errcat:parse_error"
      },
      {
        "id": "process_error",
        "title": "process_error",
        "url": "/error-categories/process_error",
        "node": "errcat:process_error"
      },
      {
        "id": "provider_error",
        "title": "provider_error",
        "url": "/error-categories/provider_error",
        "node": "errcat:provider_error"
      },
      {
        "id": "security_error",
        "title": "security_error",
        "url": "/error-categories/security_error",
        "node": "errcat:security_error"
      },
      {
        "id": "timeout_error",
        "title": "timeout_error",
        "url": "/error-categories/timeout_error",
        "node": "errcat:timeout_error"
      },
      {
        "id": "tool_error",
        "title": "tool_error",
        "url": "/error-categories/tool_error",
        "node": "errcat:tool_error"
      },
      {
        "id": "validation_error",
        "title": "validation_error",
        "url": "/error-categories/validation_error",
        "node": "errcat:validation_error"
      },
      {
        "id": "variable_error",
        "title": "variable_error",
        "url": "/error-categories/variable_error",
        "node": "errcat:variable_error"
      }
    ]
  },
  "conformance": {
    "set": "conformance-levels",
    "title": "The conformance levels",
    "hub": "/proof",
    "members": [
      {
        "id": "core",
        "title": "core",
        "url": "/conformance/core",
        "node": "level:core",
        "gloss": "parse · validate · DAG · variables · typed errors · no execution"
      },
      {
        "id": "runtime",
        "title": "runtime",
        "url": "/conformance/runtime",
        "node": "level:runtime",
        "gloss": "executes verbs · evaluates when and for_each over run state"
      },
      {
        "id": "stdlib",
        "title": "stdlib",
        "url": "/conformance/stdlib",
        "node": "level:stdlib",
        "gloss": "proves the v0.1 library surface · the production default"
      }
    ]
  },
  "mcp": {
    "set": "mcp-tools",
    "title": "The oracle tools",
    "hub": "/proof",
    "members": [
      {
        "id": "nika_canon",
        "title": "nika_canon",
        "url": "/mcp/nika_canon",
        "node": "mcp:nika_canon"
      },
      {
        "id": "nika_catalog",
        "title": "nika_catalog",
        "url": "/mcp/nika_catalog",
        "node": "mcp:nika_catalog"
      },
      {
        "id": "nika_check",
        "title": "nika_check",
        "url": "/mcp/nika_check",
        "node": "mcp:nika_check"
      },
      {
        "id": "nika_examples",
        "title": "nika_examples",
        "url": "/mcp/nika_examples",
        "node": "mcp:nika_examples"
      },
      {
        "id": "nika_explain",
        "title": "nika_explain",
        "url": "/mcp/nika_explain",
        "node": "mcp:nika_explain"
      },
      {
        "id": "nika_inspect",
        "title": "nika_inspect",
        "url": "/mcp/nika_inspect",
        "node": "mcp:nika_inspect"
      },
      {
        "id": "nika_schema",
        "title": "nika_schema",
        "url": "/mcp/nika_schema",
        "node": "mcp:nika_schema"
      },
      {
        "id": "nika_template",
        "title": "nika_template",
        "url": "/mcp/nika_template",
        "node": "mcp:nika_template"
      },
      {
        "id": "nika_tools",
        "title": "nika_tools",
        "url": "/mcp/nika_tools",
        "node": "mcp:nika_tools"
      }
    ]
  },
  "truth": {
    "set": "truth-words",
    "title": "The truth words",
    "hub": "/sources",
    "members": [
      {
        "id": "atlas",
        "title": "atlas",
        "url": "/truth/atlas",
        "node": "truth:atlas",
        "gloss": "language_graph 1 · the graph of the language, site-side"
      },
      {
        "id": "canon",
        "title": "canon",
        "url": "/truth/canon",
        "node": "truth:canon",
        "gloss": "canon.yaml · the counted sets, spec-first"
      },
      {
        "id": "catalog",
        "title": "catalog",
        "url": "/truth/catalog",
        "node": "truth:catalog",
        "gloss": "a machine projection the site serves · byte-diffed in CI"
      },
      {
        "id": "manifest",
        "title": "manifest",
        "url": "/truth/manifest",
        "node": "truth:manifest",
        "gloss": "the snippet lineage table · every rendered block resolves here"
      },
      {
        "id": "mirror",
        "title": "mirror",
        "url": "/truth/mirror",
        "node": "truth:mirror",
        "gloss": "a byte-pinned copy, sha256-verified"
      },
      {
        "id": "pack",
        "title": "pack",
        "url": "/truth/pack",
        "node": "truth:pack",
        "gloss": "the spec corpus vendored inside the engine"
      },
      {
        "id": "pin",
        "title": "pin",
        "url": "/truth/pin",
        "node": "truth:pin",
        "gloss": "SPEC_PIN · the exact spec sha the engine targets"
      },
      {
        "id": "registry",
        "title": "registry",
        "url": "/truth/registry",
        "node": "truth:registry",
        "gloss": "nika-registry THE PRODUCT · shared workflows, re-proven nightly"
      },
      {
        "id": "schema",
        "title": "schema",
        "url": "/truth/schema",
        "node": "truth:schema",
        "gloss": "workflow.schema.json · the shapes"
      },
      {
        "id": "spec",
        "title": "spec",
        "url": "/truth/spec",
        "node": "truth:spec",
        "gloss": "the nika-spec repo · the truth of the language"
      }
    ]
  }
}
