// nep-ids.generated.ts — AUTO-GENERATED by scripts/build-neps.mjs
// The CHROME-LEAN half: the slugs, for the map and the path census. The
// register itself rides src/lib/neps-access.ts (an async chunk).
// DO NOT EDIT · regenerate: node scripts/build-neps.mjs

/** every proposal, in number order */
export const NEP_SLUGS: string[] = [
 "nep-0000-the-nep-process"
]
