// showcase-dag.generated.ts — AUTO-GENERATED by scripts/lens/graph/build-lens.mjs from
// scripts/lens/graph/sets.yaml (the authored descriptor) + the gated sources.
// DO NOT EDIT · regenerate: node scripts/lens/graph/build-lens.mjs
// Drift gate: src/test/lens.test.ts recompiles and byte-diffs.

/** the showcase plan facts (value-equal projection of SHOWCASE_DAG in
 * usecases-yaml.generated.ts — lens.test pins the equality; import THIS
 * for first-render facts so the yaml strings can stay an async chunk). */
export interface ShowcaseTask {
  id: string
  verb: 'infer' | 'exec' | 'invoke' | 'agent'
  deps: string[]
  wave: number
  gate: 'default' | 'when' | 'always'
  gloss: string
  flags: string[]
  line0: number
  line1: number
}
export interface ShowcaseDag {
  tasks: ShowcaseTask[]
  outputs: string[]
  waves: number
}
export const SHOWCASE_DAG: Record<string, ShowcaseDag> = {
  "t1-image-fx-batch": {
    "tasks": [
      {
        "id": "shots",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:glob`",
        "flags": [],
        "line0": 21,
        "line1": 26
      },
      {
        "id": "stylize",
        "verb": "invoke",
        "deps": [
          "shots"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "for each item · call `nika:image_fx`",
        "flags": [
          "fan-out · ≤4 in flight"
        ],
        "line0": 27,
        "line1": 40
      }
    ],
    "outputs": [
      "rendered"
    ],
    "waves": 2
  },
  "t1-meeting-actions": {
    "tasks": [
      {
        "id": "transcript",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 17,
        "line1": 20
      },
      {
        "id": "extract",
        "verb": "infer",
        "deps": [
          "transcript"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 22,
        "line1": 41
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "extract"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 43,
        "line1": 50
      },
      {
        "id": "trace",
        "verb": "invoke",
        "deps": [
          "extract"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:log`",
        "flags": [],
        "line0": 52,
        "line1": 59
      }
    ],
    "outputs": [
      "actions"
    ],
    "waves": 3
  },
  "t1-og-images": {
    "tasks": [
      {
        "id": "hero",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:image_generate`",
        "flags": [],
        "line0": 10,
        "line1": 20
      }
    ],
    "outputs": [
      "paths",
      "manifest"
    ],
    "waves": 1
  },
  "t1-price-watch": {
    "tasks": [
      {
        "id": "check",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 18,
        "line1": 31
      },
      {
        "id": "alert",
        "verb": "invoke",
        "deps": [
          "check"
        ],
        "wave": 1,
        "gate": "when",
        "gloss": "call `nika:notify` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 33,
        "line1": 44
      }
    ],
    "outputs": [
      "price"
    ],
    "waves": 2
  },
  "t1-social-repurpose": {
    "tasks": [
      {
        "id": "post",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 14,
        "line1": 19
      },
      {
        "id": "thread",
        "verb": "infer",
        "deps": [
          "post"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 20,
        "line1": 24
      },
      {
        "id": "linkedin",
        "verb": "infer",
        "deps": [
          "post"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 26,
        "line1": 30
      },
      {
        "id": "newsletter",
        "verb": "infer",
        "deps": [
          "post"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 32,
        "line1": 36
      },
      {
        "id": "bundle",
        "verb": "invoke",
        "deps": [
          "thread",
          "linkedin",
          "newsletter"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 38,
        "line1": 57
      }
    ],
    "outputs": [
      "bundle_path"
    ],
    "waves": 3
  },
  "t1-standup-digest": {
    "tasks": [
      {
        "id": "today",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:date`",
        "flags": [],
        "line0": 13,
        "line1": 16
      },
      {
        "id": "history",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `git`",
        "flags": [],
        "line0": 18,
        "line1": 20
      },
      {
        "id": "digest",
        "verb": "infer",
        "deps": [
          "today",
          "history"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 22,
        "line1": 33
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "digest"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 35,
        "line1": 42
      }
    ],
    "outputs": [
      "note"
    ],
    "waves": 3
  },
  "t2-bookmark-triage": {
    "tasks": [
      {
        "id": "pages",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "for each item · call `nika:fetch`",
        "flags": [
          "fan-out · ≤3 in flight",
          "collects errors",
          "retry"
        ],
        "line0": 25,
        "line1": 38
      },
      {
        "id": "table",
        "verb": "invoke",
        "deps": [
          "pages"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 39,
        "line1": 55
      },
      {
        "id": "report",
        "verb": "invoke",
        "deps": [
          "table"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 57,
        "line1": 74
      }
    ],
    "outputs": [
      "table"
    ],
    "waves": 3
  },
  "t2-contract-guard": {
    "tasks": [
      {
        "id": "contract",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 17,
        "line1": 20
      },
      {
        "id": "clauses",
        "verb": "infer",
        "deps": [
          "contract"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 22,
        "line1": 42
      },
      {
        "id": "check",
        "verb": "invoke",
        "deps": [
          "clauses"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:validate`",
        "flags": [],
        "line0": 44,
        "line1": 58
      },
      {
        "id": "gate",
        "verb": "invoke",
        "deps": [
          "check"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:assert`",
        "flags": [],
        "line0": 60,
        "line1": 67
      },
      {
        "id": "memo",
        "verb": "infer",
        "deps": [
          "clauses",
          "gate"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 69,
        "line1": 78
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "memo"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 80,
        "line1": 88
      }
    ],
    "outputs": [
      "clauses",
      "memo"
    ],
    "waves": 6
  },
  "t2-csv-chart-report": {
    "tasks": [
      {
        "id": "raw",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 16,
        "line1": 19
      },
      {
        "id": "rows",
        "verb": "invoke",
        "deps": [
          "raw"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:convert`",
        "flags": [],
        "line0": 21,
        "line1": 32
      },
      {
        "id": "by_region",
        "verb": "invoke",
        "deps": [
          "rows"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 33,
        "line1": 42
      },
      {
        "id": "chart",
        "verb": "invoke",
        "deps": [
          "by_region"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:chart`",
        "flags": [],
        "line0": 43,
        "line1": 55
      },
      {
        "id": "rows_md",
        "verb": "invoke",
        "deps": [
          "by_region"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 56,
        "line1": 67
      },
      {
        "id": "report",
        "verb": "invoke",
        "deps": [
          "rows_md",
          "chart"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 68,
        "line1": 86
      }
    ],
    "outputs": [
      "by_region"
    ],
    "waves": 5
  },
  "t2-etl-quarantine": {
    "tasks": [
      {
        "id": "empty_batch",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 13,
        "line1": 16
      },
      {
        "id": "raw",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 18,
        "line1": 21
      },
      {
        "id": "rows",
        "verb": "invoke",
        "deps": [
          "raw"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:convert`",
        "flags": [],
        "line0": 23,
        "line1": 34
      },
      {
        "id": "check",
        "verb": "invoke",
        "deps": [
          "rows"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:validate`",
        "flags": [],
        "line0": 36,
        "line1": 52
      },
      {
        "id": "good",
        "verb": "invoke",
        "deps": [
          "rows",
          "check"
        ],
        "wave": 3,
        "gate": "when",
        "gloss": "call `nika:jq` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 54,
        "line1": 63
      },
      {
        "id": "quarantine",
        "verb": "invoke",
        "deps": [
          "check"
        ],
        "wave": 3,
        "gate": "when",
        "gloss": "call `nika:write` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 65,
        "line1": 75
      },
      {
        "id": "report",
        "verb": "invoke",
        "deps": [
          "good"
        ],
        "wave": 4,
        "gate": "when",
        "gloss": "call `nika:write` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 77,
        "line1": 86
      }
    ],
    "outputs": [
      "totals"
    ],
    "waves": 5
  },
  "t2-invoice-chaser": {
    "tasks": [
      {
        "id": "ledger",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 14,
        "line1": 17
      },
      {
        "id": "rows",
        "verb": "invoke",
        "deps": [
          "ledger"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:convert`",
        "flags": [],
        "line0": 19,
        "line1": 28
      },
      {
        "id": "overdue",
        "verb": "invoke",
        "deps": [
          "rows"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 30,
        "line1": 37
      },
      {
        "id": "drafts",
        "verb": "infer",
        "deps": [
          "overdue"
        ],
        "wave": 3,
        "gate": "when",
        "gloss": "ask the model · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 39,
        "line1": 47
      },
      {
        "id": "approve",
        "verb": "invoke",
        "deps": [
          "drafts"
        ],
        "wave": 4,
        "gate": "when",
        "gloss": "call `nika:prompt` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 49,
        "line1": 57
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "drafts",
          "approve"
        ],
        "wave": 5,
        "gate": "when",
        "gloss": "call `nika:write` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 59,
        "line1": 68
      }
    ],
    "outputs": [
      "overdue"
    ],
    "waves": 6
  },
  "t2-model-bench": {
    "tasks": [
      {
        "id": "ask_incumbent",
        "verb": "infer",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 16,
        "line1": 20
      },
      {
        "id": "ask_challenger",
        "verb": "infer",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 22,
        "line1": 26
      },
      {
        "id": "ask_tiny",
        "verb": "infer",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 28,
        "line1": 32
      },
      {
        "id": "tabulate",
        "verb": "invoke",
        "deps": [
          "ask_incumbent",
          "ask_challenger",
          "ask_tiny"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 34,
        "line1": 61
      },
      {
        "id": "persist",
        "verb": "invoke",
        "deps": [
          "tabulate"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 63,
        "line1": 77
      }
    ],
    "outputs": [],
    "waves": 3
  },
  "t2-release-notes": {
    "tasks": [
      {
        "id": "history",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `git`",
        "flags": [],
        "line0": 23,
        "line1": 25
      },
      {
        "id": "notes",
        "verb": "infer",
        "deps": [
          "history"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 27,
        "line1": 41
      },
      {
        "id": "changelog",
        "verb": "invoke",
        "deps": [
          "notes"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:edit`",
        "flags": [],
        "line0": 43,
        "line1": 57
      },
      {
        "id": "announce",
        "verb": "invoke",
        "deps": [
          "notes",
          "changelog"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:notify`",
        "flags": [],
        "line0": 59,
        "line1": 70
      }
    ],
    "outputs": [
      "headline",
      "body"
    ],
    "waves": 4
  },
  "t2-release-radar": {
    "tasks": [
      {
        "id": "no_state",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 13,
        "line1": 16
      },
      {
        "id": "previous",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 18,
        "line1": 24
      },
      {
        "id": "feed",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 26,
        "line1": 33
      },
      {
        "id": "fresh",
        "verb": "invoke",
        "deps": [
          "previous",
          "feed"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:json_diff`",
        "flags": [],
        "line0": 35,
        "line1": 43
      },
      {
        "id": "digest",
        "verb": "infer",
        "deps": [
          "fresh",
          "feed"
        ],
        "wave": 2,
        "gate": "when",
        "gloss": "ask the model · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 45,
        "line1": 57
      },
      {
        "id": "save_state",
        "verb": "invoke",
        "deps": [
          "feed"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 59,
        "line1": 68
      }
    ],
    "outputs": [
      "new_entries"
    ],
    "waves": 3
  },
  "t2-seo-content-brief": {
    "tasks": [
      {
        "id": "map",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 15,
        "line1": 22
      },
      {
        "id": "top_page",
        "verb": "invoke",
        "deps": [
          "map"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 24,
        "line1": 31
      },
      {
        "id": "brief",
        "verb": "infer",
        "deps": [
          "map",
          "top_page"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 33,
        "line1": 53
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "brief"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 55,
        "line1": 63
      }
    ],
    "outputs": [
      "brief"
    ],
    "waves": 4
  },
  "t2-support-triage": {
    "tasks": [
      {
        "id": "batch",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:uuid`",
        "flags": [],
        "line0": 19,
        "line1": 22
      },
      {
        "id": "queue",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 24,
        "line1": 27
      },
      {
        "id": "triage",
        "verb": "infer",
        "deps": [
          "queue"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 29,
        "line1": 50
      },
      {
        "id": "urgent",
        "verb": "invoke",
        "deps": [
          "triage"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 52,
        "line1": 59
      },
      {
        "id": "escalate",
        "verb": "invoke",
        "deps": [
          "urgent",
          "batch"
        ],
        "wave": 3,
        "gate": "when",
        "gloss": "call `nika:notify` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 61,
        "line1": 72
      },
      {
        "id": "board",
        "verb": "invoke",
        "deps": [
          "triage",
          "batch"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 74,
        "line1": 82
      }
    ],
    "outputs": [
      "tickets"
    ],
    "waves": 4
  },
  "t2-transcript-shownotes": {
    "tasks": [
      {
        "id": "raw",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 18,
        "line1": 23
      },
      {
        "id": "notes",
        "verb": "infer",
        "deps": [
          "raw"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 24,
        "line1": 54
      },
      {
        "id": "sections",
        "verb": "invoke",
        "deps": [
          "notes"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 55,
        "line1": 66
      },
      {
        "id": "page",
        "verb": "invoke",
        "deps": [
          "notes",
          "sections"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 68,
        "line1": 90
      }
    ],
    "outputs": [
      "notes"
    ],
    "waves": 4
  },
  "t3-competitor-radar": {
    "tasks": [
      {
        "id": "map",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 22,
        "line1": 29
      },
      {
        "id": "pages",
        "verb": "invoke",
        "deps": [
          "map"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "for each item · call `nika:fetch`",
        "flags": [
          "fan-out · ≤4 in flight",
          "collects errors",
          "retry",
          "timeout 30s"
        ],
        "line0": 31,
        "line1": 48
      },
      {
        "id": "digest",
        "verb": "infer",
        "deps": [
          "pages"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 50,
        "line1": 58
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "digest"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 60,
        "line1": 68
      },
      {
        "id": "ping",
        "verb": "invoke",
        "deps": [
          "save"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:notify`",
        "flags": [],
        "line0": 70,
        "line1": 79
      }
    ],
    "outputs": [
      "brief"
    ],
    "waves": 5
  },
  "t3-config-drift-sentinel": {
    "tasks": [
      {
        "id": "live",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [
          "retry"
        ],
        "line0": 24,
        "line1": 33
      },
      {
        "id": "baseline",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 35,
        "line1": 38
      },
      {
        "id": "expected",
        "verb": "invoke",
        "deps": [
          "baseline"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:json_merge_patch`",
        "flags": [],
        "line0": 40,
        "line1": 47
      },
      {
        "id": "drift",
        "verb": "invoke",
        "deps": [
          "expected",
          "live"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:json_diff`",
        "flags": [],
        "line0": 49,
        "line1": 57
      },
      {
        "id": "fingerprint",
        "verb": "invoke",
        "deps": [
          "live"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:hash`",
        "flags": [],
        "line0": 59,
        "line1": 67
      },
      {
        "id": "explain",
        "verb": "infer",
        "deps": [
          "drift"
        ],
        "wave": 3,
        "gate": "when",
        "gloss": "ask the model · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 69,
        "line1": 79
      },
      {
        "id": "alert",
        "verb": "invoke",
        "deps": [
          "drift",
          "explain",
          "fingerprint"
        ],
        "wave": 4,
        "gate": "when",
        "gloss": "call `nika:notify` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 81,
        "line1": 93
      },
      {
        "id": "record",
        "verb": "invoke",
        "deps": [
          "drift",
          "fingerprint"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:emit`",
        "flags": [],
        "line0": 95,
        "line1": 105
      }
    ],
    "outputs": [
      "drift"
    ],
    "waves": 5
  },
  "t3-localization-factory": {
    "tasks": [
      {
        "id": "files",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:glob`",
        "flags": [],
        "line0": 12,
        "line1": 17
      },
      {
        "id": "texts",
        "verb": "invoke",
        "deps": [
          "files"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "for each item · call `nika:read`",
        "flags": [
          "fan-out · ≤8 in flight"
        ],
        "line0": 19,
        "line1": 26
      },
      {
        "id": "pairs",
        "verb": "invoke",
        "deps": [
          "files",
          "texts"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 28,
        "line1": 36
      },
      {
        "id": "translated",
        "verb": "infer",
        "deps": [
          "pairs"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "for each item · ask the model",
        "flags": [
          "fan-out · ≤3 in flight",
          "collects errors"
        ],
        "line0": 38,
        "line1": 50
      },
      {
        "id": "bundle",
        "verb": "invoke",
        "deps": [
          "pairs",
          "translated"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 52,
        "line1": 60
      },
      {
        "id": "mirror",
        "verb": "invoke",
        "deps": [
          "bundle"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "for each item · call `nika:write`",
        "flags": [
          "fan-out · ≤8 in flight"
        ],
        "line0": 62,
        "line1": 72
      }
    ],
    "outputs": [
      "files"
    ],
    "waves": 6
  },
  "t3-pr-review-fanout": {
    "tasks": [
      {
        "id": "changed",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `git`",
        "flags": [],
        "line0": 15,
        "line1": 17
      },
      {
        "id": "files",
        "verb": "invoke",
        "deps": [
          "changed"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 19,
        "line1": 26
      },
      {
        "id": "todo_sweep",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:grep`",
        "flags": [],
        "line0": 28,
        "line1": 33
      },
      {
        "id": "reviews",
        "verb": "agent",
        "deps": [
          "files"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "for each item · run an agent loop · 2 tools granted",
        "flags": [
          "fan-out · ≤4 in flight",
          "collects errors",
          "typed output"
        ],
        "line0": 35,
        "line1": 64
      },
      {
        "id": "merged",
        "verb": "invoke",
        "deps": [
          "reviews"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 66,
        "line1": 75
      },
      {
        "id": "summary",
        "verb": "infer",
        "deps": [
          "merged",
          "todo_sweep"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "ask the model",
        "flags": [],
        "line0": 77,
        "line1": 87
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "summary"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 89,
        "line1": 96
      }
    ],
    "outputs": [
      "findings",
      "review"
    ],
    "waves": 6
  },
  "t3-resume-screener": {
    "tasks": [
      {
        "id": "pool",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:glob`",
        "flags": [],
        "line0": 19,
        "line1": 22
      },
      {
        "id": "cvs",
        "verb": "invoke",
        "deps": [
          "pool"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "for each item · call `nika:read`",
        "flags": [
          "fan-out · ≤8 in flight",
          "collects errors"
        ],
        "line0": 24,
        "line1": 34
      },
      {
        "id": "pairs",
        "verb": "invoke",
        "deps": [
          "pool",
          "cvs"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 36,
        "line1": 44
      },
      {
        "id": "screened",
        "verb": "infer",
        "deps": [
          "pairs"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "for each item · ask the model for typed JSON",
        "flags": [
          "fan-out · ≤2 in flight",
          "collects errors",
          "typed output"
        ],
        "line0": 46,
        "line1": 71
      },
      {
        "id": "ranked",
        "verb": "invoke",
        "deps": [
          "screened"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 73,
        "line1": 80
      },
      {
        "id": "shortlist",
        "verb": "invoke",
        "deps": [
          "ranked"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 82,
        "line1": 89
      },
      {
        "id": "brief",
        "verb": "infer",
        "deps": [
          "shortlist"
        ],
        "wave": 6,
        "gate": "when",
        "gloss": "ask the model · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 91,
        "line1": 100
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "brief"
        ],
        "wave": 7,
        "gate": "when",
        "gloss": "call `nika:write` · only if its condition holds",
        "flags": [
          "conditional"
        ],
        "line0": 102,
        "line1": 111
      }
    ],
    "outputs": [
      "shortlist"
    ],
    "waves": 8
  },
  "t4-ceo-monday-brief": {
    "tasks": [
      {
        "id": "news",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 24,
        "line1": 32
      },
      {
        "id": "pulse",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `git`",
        "flags": [],
        "line0": 33,
        "line1": 37
      },
      {
        "id": "kpi_raw",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 38,
        "line1": 41
      },
      {
        "id": "kpis",
        "verb": "invoke",
        "deps": [
          "kpi_raw"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:convert`",
        "flags": [],
        "line0": 43,
        "line1": 52
      },
      {
        "id": "revenue",
        "verb": "invoke",
        "deps": [
          "kpis"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:jq`",
        "flags": [],
        "line0": 54,
        "line1": 63
      },
      {
        "id": "brief",
        "verb": "infer",
        "deps": [
          "news",
          "pulse",
          "kpis",
          "revenue"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "ask the model · thinking budget",
        "flags": [],
        "line0": 64,
        "line1": 82
      },
      {
        "id": "stamp",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:date`",
        "flags": [],
        "line0": 84,
        "line1": 89
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "stamp",
          "brief"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 91,
        "line1": 102
      },
      {
        "id": "bill",
        "verb": "invoke",
        "deps": [
          "save"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "call `nika:inspect`",
        "flags": [],
        "line0": 103,
        "line1": 108
      },
      {
        "id": "ping",
        "verb": "invoke",
        "deps": [
          "stamp",
          "bill"
        ],
        "wave": 6,
        "gate": "default",
        "gloss": "call `nika:notify`",
        "flags": [
          "cleanup always runs"
        ],
        "line0": 110,
        "line1": 127
      }
    ],
    "outputs": [
      "brief",
      "cost_usd"
    ],
    "waves": 7
  },
  "t4-deep-research-brief": {
    "tasks": [
      {
        "id": "plan",
        "verb": "infer",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 16,
        "line1": 26
      },
      {
        "id": "investigate",
        "verb": "agent",
        "deps": [
          "plan"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "run an agent loop · 3 tools granted",
        "flags": [
          "typed output"
        ],
        "line0": 28,
        "line1": 52
      },
      {
        "id": "brief",
        "verb": "infer",
        "deps": [
          "investigate"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "ask the model · thinking budget",
        "flags": [],
        "line0": 54,
        "line1": 66
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "brief"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 68,
        "line1": 76
      }
    ],
    "outputs": [
      "brief",
      "sources"
    ],
    "waves": 4
  },
  "t4-incident-war-room": {
    "tasks": [
      {
        "id": "logs",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `journalctl`",
        "flags": [],
        "line0": 25,
        "line1": 28
      },
      {
        "id": "status_history",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [
          "retry"
        ],
        "line0": 30,
        "line1": 40
      },
      {
        "id": "runbook",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:read`",
        "flags": [],
        "line0": 42,
        "line1": 47
      },
      {
        "id": "timeline",
        "verb": "infer",
        "deps": [
          "logs",
          "status_history",
          "runbook"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "ask the model for typed JSON",
        "flags": [
          "typed output"
        ],
        "line0": 48,
        "line1": 75
      },
      {
        "id": "settle",
        "verb": "invoke",
        "deps": [
          "timeline"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:wait`",
        "flags": [],
        "line0": 76,
        "line1": 81
      },
      {
        "id": "recheck",
        "verb": "invoke",
        "deps": [
          "settle"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [],
        "line0": 83,
        "line1": 91
      },
      {
        "id": "confirmed",
        "verb": "invoke",
        "deps": [
          "recheck"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:assert`",
        "flags": [],
        "line0": 93,
        "line1": 102
      },
      {
        "id": "postmortem",
        "verb": "infer",
        "deps": [
          "timeline",
          "confirmed"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "ask the model · thinking budget",
        "flags": [],
        "line0": 103,
        "line1": 116
      },
      {
        "id": "save",
        "verb": "invoke",
        "deps": [
          "postmortem"
        ],
        "wave": 6,
        "gate": "default",
        "gloss": "call `nika:write`",
        "flags": [],
        "line0": 118,
        "line1": 131
      },
      {
        "id": "ping",
        "verb": "invoke",
        "deps": [
          "save"
        ],
        "wave": 7,
        "gate": "default",
        "gloss": "call `nika:emit`",
        "flags": [
          "cleanup always runs"
        ],
        "line0": 132,
        "line1": 151
      }
    ],
    "outputs": [
      "events",
      "postmortem"
    ],
    "waves": 8
  },
  "t4-release-train": {
    "tasks": [
      {
        "id": "t0",
        "verb": "invoke",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "call `nika:date`",
        "flags": [],
        "line0": 25,
        "line1": 30
      },
      {
        "id": "tests",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `cargo`",
        "flags": [
          "timeout 15m"
        ],
        "line0": 31,
        "line1": 35
      },
      {
        "id": "lint",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `cargo`",
        "flags": [
          "timeout 10m"
        ],
        "line0": 37,
        "line1": 41
      },
      {
        "id": "audit",
        "verb": "exec",
        "deps": [],
        "wave": 0,
        "gate": "default",
        "gloss": "run `cargo`",
        "flags": [
          "retry",
          "timeout 5m"
        ],
        "line0": 43,
        "line1": 49
      },
      {
        "id": "gates_green",
        "verb": "invoke",
        "deps": [
          "tests",
          "lint",
          "audit"
        ],
        "wave": 1,
        "gate": "default",
        "gloss": "call `nika:assert`",
        "flags": [],
        "line0": 51,
        "line1": 58
      },
      {
        "id": "gate_time",
        "verb": "invoke",
        "deps": [
          "t0",
          "gates_green"
        ],
        "wave": 2,
        "gate": "default",
        "gloss": "call `nika:date`",
        "flags": [],
        "line0": 60,
        "line1": 73
      },
      {
        "id": "conductor",
        "verb": "invoke",
        "deps": [
          "gate_time"
        ],
        "wave": 3,
        "gate": "default",
        "gloss": "call `nika:prompt`",
        "flags": [],
        "line0": 74,
        "line1": 81
      },
      {
        "id": "approved",
        "verb": "invoke",
        "deps": [
          "conductor"
        ],
        "wave": 4,
        "gate": "default",
        "gloss": "call `nika:assert`",
        "flags": [],
        "line0": 83,
        "line1": 92
      },
      {
        "id": "hold",
        "verb": "invoke",
        "deps": [
          "approved"
        ],
        "wave": 5,
        "gate": "default",
        "gloss": "call `nika:wait`",
        "flags": [],
        "line0": 93,
        "line1": 100
      },
      {
        "id": "ship",
        "verb": "exec",
        "deps": [
          "hold"
        ],
        "wave": 6,
        "gate": "default",
        "gloss": "run `./scripts/release.sh`",
        "flags": [
          "timeout 30m"
        ],
        "line0": 102,
        "line1": 108
      },
      {
        "id": "verify",
        "verb": "invoke",
        "deps": [
          "ship"
        ],
        "wave": 7,
        "gate": "default",
        "gloss": "call `nika:fetch`",
        "flags": [
          "retry"
        ],
        "line0": 110,
        "line1": 122
      },
      {
        "id": "live",
        "verb": "invoke",
        "deps": [
          "verify"
        ],
        "wave": 8,
        "gate": "default",
        "gloss": "call `nika:assert`",
        "flags": [],
        "line0": 124,
        "line1": 136
      },
      {
        "id": "record",
        "verb": "invoke",
        "deps": [
          "live"
        ],
        "wave": 9,
        "gate": "default",
        "gloss": "call `nika:emit`",
        "flags": [
          "cleanup always runs"
        ],
        "line0": 137,
        "line1": 156
      }
    ],
    "outputs": [
      "shipped"
    ],
    "waves": 10
  }
}
