// terminal-captures.generated.ts — AUTO-GENERATED by
// scripts/build-terminal-captures.mjs: the living terminal's recorded runs,
// executed against the released binary and captured VERBATIM (NO_COLOR).
// DO NOT EDIT · regenerate: node scripts/build-terminal-captures.mjs
// Gates: src/test/terminal.test.ts (whitelist parity · provenance · json twins).
import type { TermLine } from '../components/TermFrame'

export interface TerminalCapture {
  id: string
  /** the exact command line the visitor can replay */
  command: string
  /** the recorded output, in the CLI's own voice */
  lines: TermLine[]
  /** the machine twin (--format json) where the command has one */
  json?: string
}

/** the engine release every capture was recorded from */
export const TERMINAL_ENGINE = "0.106.1"

export const TERMINAL_CAPTURES: TerminalCapture[] = [
  {
    "id": "version",
    "command": "nika --version",
    "lines": [
      {
        "kind": "out",
        "text": "nika 0.106.1"
      }
    ]
  },
  {
    "id": "check-hello",
    "command": "nika check hello.nika.yaml",
    "lines": [
      {
        "kind": "out",
        "text": "nika check · hello.nika.yaml"
      },
      {
        "kind": "ok",
        "text": " ✔ PLAN     1 wave · 1 task · max parallelism 1"
      },
      {
        "kind": "dim",
        "text": "      wave 1 greet (exec · echo)"
      },
      {
        "kind": "ok",
        "text": " ✔ COST     no inference tasks · $0.00"
      },
      {
        "kind": "ok",
        "text": " ✔ SECRETS  no information-flow escapes"
      },
      {
        "kind": "ok",
        "text": " ✔ TYPES    deep references fit the shapes tasks declare · builtin output has none"
      },
      {
        "kind": "ok",
        "text": " ✔ TOOLS    every nika: tool names a canonical builtin"
      },
      {
        "kind": "ok",
        "text": " ✔ ARGS     every invoke arg key is declared + every required arg is present"
      },
      {
        "kind": "ok",
        "text": " ✔ SCHEMA   every authored schema: is satisfiable"
      },
      {
        "kind": "ok",
        "text": " ✔ GATES    every task is statically reachable · status literals in vocabulary"
      },
      {
        "kind": "ok",
        "text": " ✔ PERMITS  body fits the declared boundary"
      },
      {
        "kind": "ok",
        "text": " ✔ TRIFECTA no lethal trifecta without a dominating human gate"
      },
      {
        "kind": "ok",
        "text": " ✔ audited · 1 task · 1 wave · permits declared · est ≤$0.0000 · 0 hints"
      }
    ]
  },
  {
    "id": "inspect-hello",
    "command": "nika inspect hello.nika.yaml",
    "lines": [
      {
        "kind": "out",
        "text": "hello · 1 task · 1 wave · no inference tasks · $0.00"
      },
      {
        "kind": "dim",
        "text": "  ▷ greet  exec"
      },
      {
        "kind": "dim",
        "text": "  (no orphans · DAG check NIKA-DAG-001 clean)"
      }
    ],
    "json": "{\n \"graph_format\": 2,\n \"workflow\": \"hello\",\n \"nodes\": [\n  {\n   \"id\": \"greet\",\n   \"verb\": \"exec\",\n   \"when\": null,\n   \"fan_out\": null,\n   \"permits\": [\n    \"exec: echo\"\n   ],\n   \"cost_interval\": null\n  }\n ],\n \"edges\": []\n}"
  },
  {
    "id": "explain-parse-019",
    "command": "nika explain NIKA-PARSE-019",
    "lines": [
      {
        "kind": "out",
        "text": "NIKA-PARSE-019 · validation_error · transient: false"
      },
      {
        "kind": "out",
        "text": ""
      },
      {
        "kind": "out",
        "text": "  generic structural validation — wrong YAML shape for a field"
      },
      {
        "kind": "out",
        "text": ""
      },
      {
        "kind": "out",
        "text": "  fix: the field's YAML SHAPE is wrong (a string where a list goes, a list where a map goes) — `tasks:` is a MAP keyed by task id, and the finding names the field whose shape to fix"
      },
      {
        "kind": "out",
        "text": ""
      },
      {
        "kind": "out",
        "text": "full docs: https://nika.sh/errors/NIKA-PARSE-019 — `nika check` catches this before a run ever starts."
      }
    ]
  },
  {
    "id": "explain-dag-003",
    "command": "nika explain NIKA-DAG-003",
    "lines": [
      {
        "kind": "out",
        "text": "NIKA-DAG-003 · retired — never reused"
      },
      {
        "kind": "out",
        "text": ""
      },
      {
        "kind": "out",
        "text": "  « a `tasks.X` reference with no declared edge » became INEXPRESSIBLE in W2 « the flow »: the `with:` binding IS the edge (derived, never restated), and a reference outside the boundary is NIKA-VAR-021 (hoist it into `with:` — `nika check --fix` applies it)"
      },
      {
        "kind": "out",
        "text": ""
      },
      {
        "kind": "out",
        "text": "full docs: https://nika.sh/errors/NIKA-DAG-003 — retired codes keep their page; the successor code carries the live teaching."
      }
    ]
  }
]
