// word-openers.generated.ts — AUTO-GENERATED by scripts/build-word-openers.mjs
// from public/ontology/language.json (the served language twin).
// DO NOT EDIT · regenerate: node scripts/build-word-openers.mjs
// Drift gate: src/test/word-openers.test.ts
//
// The contract's own teaching sentence per declared word, sliced to a card.
// FALLBACK ONLY: plain-words.ts stays first where it has a line, because the
// curated prose is in the anyone register and these are in the spec register.

/** word → the contract's opener, first clause, card-length */
export const WORD_OPENER: Record<string, string> = {
  after: "The CONTROL boundary · {producer-task: predicate}.",
  args: "Arguments passed to the tool · an object whose shape is the TOOL's own schema, not the language's.",
  backoff_max_ms: "Ceiling on the computed delay, in milliseconds · default 60000, one minute.",
  backoff_ms: "Initial delay between attempts, in milliseconds · default 1000. `backoff_strategy` decides how it grows from there.",
  backoff_strategy: "Which curve the delay follows between attempts · `fixed` · `linear` · `exponential` · default `exponential`.",
  because: "The non-empty justification · recorded in the run receipt with the taint path and the value digest.",
  capture: "Which stream becomes the task's output · `stdout` (default) · `stderr` · `combined` · `structured` = `{ stdout, stderr, exit_code }`.",
  command: "argv — the program and its arguments, execve, NO shell.",
  const: "Named constants · `${{ const.X }}` · a fixed value baked into the workflow.",
  cwd: "Working directory for the subprocess · default = the engine's own cwd.",
  decode: "How the captured string becomes a value · `text` (default) · `json` · `jsonl` · `bytes`.",
  env: "OS environment variables for THIS subprocess · a key→value map applied over the composed environment.",
  extract: "Named jq-expression bindings extracted from the verb's raw response · read downstream as `${{ tasks.X.<name> }}`.",
  fail_fast: "Whether the fan-out abandons the batch on the first failure · default true.",
  for_each: "Fan this task out over a collection",
  from: "REQUIRED for law 'taint', forbidden otherwise",
  group: "Fan-in MEMBERSHIP · this task joins the named group, and a consumer folds the whole group with one `${{ group.<name> }}` binding in its `with:`.",
  inputs: "Typed workflow inputs · `${{ inputs.X }}` · the parameters an author declares and a caller supplies.",
  items: "The collection · a `${{ ... }}` reference OR a literal array.",
  jitter: "Randomize the computed delay so tasks retrying the same upstream do not synchronize · default TRUE.",
  law: "WHICH law this entry lifts",
  lift: "The authored doors · each entry lifts exactly ONE named law, with a mandatory reason, check-visible and receipt-recorded.",
  max_attempts: "Total attempts, counting the first try · integer ≥ 1 · the one required field of a `retry:` block.",
  max_parallel: "Cap concurrent iterations · default unbounded · 1 = sequential.",
  max_tokens_total: "Cumulative token budget across every turn of the loop · the SPEND ceiling, where `max_turns` is the step ceiling.",
  model: "Default model · `<provider>/<name>` (e.g. ollama/qwen3.5:9b · anthropic/claude-sonnet-4-6 · mock/echo).",
  nika: "The file's NAME · kebab-case · and the mark that says « this is a nika file ».",
  on_codes: "Retry ONLY on these canonical `NIKA-<NS>-<NNN>` codes · absent, the engine retries anything transient.",
  outputs: "The workflow's return value · symmetric to inputs.",
  permits: "The declared capability boundary · once present every category is default-deny unless listed.",
  recover: "Recovery output · a `${{ }}` ref OR a literal.",
  retry: "Retry policy for this task · `{ max_attempts, backoff_ms, backoff_strategy, backoff_max_ms, jitter, on_codes }`.",
  returns: "The task's output contract · the TYPED door, where a verb-level `schema:` is the out-of-core hatch.",
  run: "The run's entropy and clock declaration · every source of randomness and of time is declared, never ambient.",
  schema: "JSON Schema · the structured-output contract the model's reply must satisfy.",
  secrets: "Vault-backed masked references · `${{ secrets.X }}` · never inline literals.",
  shell: "One shell line, run via /bin/sh -c — the EXPLICIT dangerous door (pipes · redirects · globs).",
  skills: "Agent Skill (SKILL.md) file paths · explicit static paths only, no globs and no templates.",
  skip: "Swallow the error and let the DAG continue · the task produces no output, and the original error stays readable at `tasks.<id>.error`.",
  stdin: "Data written to the command's standard input · may interpolate `${{ }}`.",
  system: "System prompt · the standing instruction, sent ahead of `prompt:` and unchanged by it.",
  tasks: "The task map · the KEY is the task's identity (snake_case · CEL-safe).",
  temperature: "Sampling temperature · 0 is the steadiest the provider offers, 2 the loosest.",
  thinking: "Extended thinking · `{ enabled, budget_tokens }` — reasoning the model may spend before it answers.",
  timeout: "Go-duration string · quoted · e.g. \"30s\" \"5m\" \"1h30m\" \"2.5s\".",
  tool: "Tool reference · nika:<path> (closed v0.1 builtin set) OR mcp:<server>/<tool> (requires the slash).",
  tools: "Whitelist · DEFAULT-DENY (no tools if absent) · gitignore-style globs · `!` negation.",
  vision: "Image inputs for the call · each entry `{ source: file | url, path | url }` · the images `prompt:` is allowed to refer to.",
  when: "LOCAL business condition · false skips the task · evaluated POST-gate over {vars · env · with · item · index}.",
  with: "Task-level scope injection · `${{ with.X }}`.",
  workflow: "Compose another workflow (spec 14) · a STATIC target: a filesystem path OR registry:owner/name@version (pinned).",
}

/** declared words with NO teaching sentence in EITHER source. Writing them is
 *  the spec's job, not this build script's — the gate lets this only shrink. */
export const WORDS_WITHOUT_WORDS: string[] = []
