/* ─── build-errors · public/errors/catalog.json → src/content/errors.generated.ts
   The error registry IS the served catalog (projected from the spec's
   canon.yaml — see that file's $schema/description); the site ships a COMPILED
   projection of it, following the repo's generated-module convention
   (canon.generated.ts · blog.generated.ts): the /errors/:code pages read a
   typed module, never fetch at runtime, and can never drift from the machine
   registry an engine consumer reads (one artifact, two renderings).

   Determinism: same catalog → byte-identical output (codes sorted, no build
   stamps). The vitest drift gate (errors.test.ts) recompiles and diffs.

   Run: node scripts/build-errors.mjs
   Output: src/content/errors.generated.ts (committed) */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'public', 'errors', 'catalog.json')
const OUT = join(ROOT, 'src', 'content', 'errors.generated.ts')

const catalog = JSON.parse(readFileSync(SRC, 'utf8'))

const entries = [...catalog.codes]
  .map((c) => ({
    code: String(c.code),
    category: String(c.category),
    transient: String(c.transient) === 'true',
    failure: String(c.failure),
  }))
  .sort((a, b) => (a.code < b.code ? -1 : a.code > b.code ? 1 : 0))

const ts = `// errors.generated.ts — AUTO-GENERATED by scripts/build-errors.mjs
// from public/errors/catalog.json (itself projected from the spec's
// canon.yaml — the single source of truth). DO NOT EDIT · regenerate:
//   node scripts/build-errors.mjs
// Drift gate: src/test/errors.test.ts recompiles and byte-diffs.

export interface ErrorCodeEntry {
  /** The stable identifier (\`NIKA-<NAMESPACE>-<NNN>\`). */
  code: string
  /** The spec category (\`parse_error\` · \`validation_error\` · …). */
  category: string
  /** Whether a retry might succeed (network · 503 · rate limit). */
  transient: boolean
  /** One line: the failure this code names. */
  failure: string
}

/** Every registered code, sorted. Registry version: ${JSON.stringify(String(catalog.version ?? ''))}. */
export const ERROR_CODES: ErrorCodeEntry[] = ${JSON.stringify(entries, null, 2)}

/** \`NIKA-VAR-001\` → its entry (uppercase-keyed — lookups normalize case). */
export const ERROR_INDEX: Record<string, ErrorCodeEntry> = Object.fromEntries(
  ERROR_CODES.map((e) => [e.code, e]),
)

/** The namespaces present in the registry, sorted (\`NIKA-PARSE\` · …). */
export const ERROR_NAMESPACES: string[] = [...new Set(ERROR_CODES.map((e) => e.code.split('-').slice(0, 2).join('-')))].sort()
`

writeFileSync(OUT, ts)
console.log(`wrote ${OUT.replace(ROOT + '/', '')} (${entries.length} codes)`)
