/* ─── build-errors · public/errors/catalog.json → src/content/errors.generated.ts
   The error registry IS the served catalog (projected from the spec's
   canon.yaml — see that file's $schema/description); the site ships a COMPILED
   projection of it, following the repo's generated-module convention
   (canon.generated.ts · blog.generated.ts): the /errors/:code pages read a
   typed module, never fetch at runtime, and can never drift from the machine
   registry an engine consumer reads (one artifact, two renderings).

   Determinism: same catalog → byte-identical output (codes sorted, no build
   stamps). The vitest drift gate (errors.test.ts) recompiles and diffs.

   Run: node scripts/build-errors.mjs
   Output: src/content/errors.generated.ts (committed) */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'public', 'errors', 'catalog.json')
const OUT = join(ROOT, 'src', 'content', 'errors.generated.ts')

const catalog = JSON.parse(readFileSync(SRC, 'utf8'))

const entries = [...catalog.codes]
  .map((c) => ({
    code: String(c.code),
    category: String(c.category),
    transient: String(c.transient) === 'true',
    failure: String(c.failure),
  }))
  .sort((a, b) => (a.code < b.code ? -1 : a.code > b.code ? 1 : 0))

/* ── the refusal prose leaves the index (the register-diet law) ──────────────
   Each code's `failure` is the sentence /errors and /errors/:code exist to
   show, and those pages are sync-routed for the prerenderer, so the whole
   96-sentence corpus rode the ENTRY chunk for every visitor. Measured
   2026-07-27 by emptying the strings and rebuilding: 4.4 KB gz, and it grows
   with every code the canon mints.

   Same recipe as the language prose: a light index here (code · category ·
   transient — what the counts, the namespace list, /verbs and /boundary all
   read) and the sentences in their own module behind
   src/lib/error-prose-access.ts. */
const prose = Object.fromEntries(entries.map((e) => [e.code, e.failure]))
const lightEntries = entries.map(({ failure: _f, ...rest }) => rest)

writeFileSync(
  join(ROOT, 'src', 'content', 'error-prose.generated.ts'),
  `// error-prose.generated.ts — AUTO-GENERATED by scripts/build-errors.mjs
// from public/errors/catalog.json (projected from the spec's canon.yaml).
// DO NOT EDIT · regenerate: node scripts/build-errors.mjs
// Drift gate: src/test/errors.test.ts recompiles and byte-diffs.
//
// THE HEAVY HALF, DELIBERATELY SEPARATE. These are the canon's own refusal
// sentences. They are NOT in errors.generated.ts because that module is
// entry-resident (sync-routed pages) and this corpus grows with every code the
// canon mints. The door is src/lib/error-prose-access.ts; nothing should import
// this module directly except that door and the build scripts.

/** code → the one line the canon gives its refusal */
export const ERROR_PROSE: Record<string, string> = ${JSON.stringify(prose, null, 2)}
`,
)

const ts = `// errors.generated.ts — AUTO-GENERATED by scripts/build-errors.mjs
// from public/errors/catalog.json (itself projected from the spec's
// canon.yaml — the single source of truth). DO NOT EDIT · regenerate:
//   node scripts/build-errors.mjs
// Drift gate: src/test/errors.test.ts recompiles and byte-diffs.

export interface ErrorCodeEntry {
  /** The stable identifier (\`NIKA-<NAMESPACE>-<NNN>\`). */
  code: string
  /** The spec category (\`parse_error\` · \`validation_error\` · …). */
  category: string
  /** Whether a retry might succeed (network · 503 · rate limit). */
  transient: boolean
}

/** Every registered code, sorted. Registry version: ${JSON.stringify(String(catalog.version ?? ''))}. */
export const ERROR_CODES: ErrorCodeEntry[] = ${JSON.stringify(lightEntries, null, 2)}

/** \`NIKA-VAR-001\` → its entry (uppercase-keyed — lookups normalize case). */
export const ERROR_INDEX: Record<string, ErrorCodeEntry> = Object.fromEntries(
  ERROR_CODES.map((e) => [e.code, e]),
)

/** The namespaces present in the registry, sorted (\`NIKA-PARSE\` · …). */
export const ERROR_NAMESPACES: string[] = [...new Set(ERROR_CODES.map((e) => e.code.split('-').slice(0, 2).join('-')))].sort()
`

writeFileSync(OUT, ts)
console.log(`wrote ${OUT.replace(ROOT + '/', '')} (${entries.length} codes)`)
