/* ─── build-neps · how the standard evolves → a register and its rooms ──────
   governance/ has been in the spec pack the whole time: 18 numbered NEPs,
   158KB, the public process by which the language changes. The site rendered
   none of it, and the specification itself cites them by number — chapter 10
   names NEP-0017 in a normative heading with no address behind it.

   A NEP is citable BY DESIGN. That is what numbering a proposal is for, and
   it is why every one gets a room even though most carry Status: Draft: in a
   standards process the draft IS the artifact you cite, and the room says its
   status in the first line. (The engine's ADRs took the opposite ruling for
   the opposite reason — an ADR is an internal decision, and a proposal
   published as a decision would be read as settled.)

   THE PIN, NOT THE CHECKOUT. Every file is read with
   `git show <spec_commit>:governance/<file>`, so a moving sibling HEAD can
   never leak in. No sibling → the committed catalog stands (build-lessons).

   Run:   node scripts/build-neps.mjs
   Check: node scripts/build-neps.mjs --check   (exit 5 on drift) */
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { lex } from './lib/md-tokens.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CATALOG = join(ROOT, 'public', 'spec', 'neps.json')
const OUT = join(ROOT, 'src', 'content', 'neps.generated.ts')
const OUT_BODY = join(ROOT, 'src', 'content', 'neps-body.generated.ts')
const OUT_IDS = join(ROOT, 'src', 'content', 'nep-ids.generated.ts')
const PIN = JSON.parse(readFileSync(join(ROOT, '.github/nika-spec-pin.json'), 'utf8'))
const SPEC_ROOT = process.env.NIKA_SPEC_ROOT ?? join(ROOT, '..', 'spec', 'repo')

const sha256 = (s) => createHash('sha256').update(s).digest('hex')
const byCp = (a, b) => (a < b ? -1 : a > b ? 1 : 0)

/** the header block every NEP carries · `- **Status**: Draft` and siblings */
function headerField(body, name) {
  const m = body.match(new RegExp(`^-\\s+\\*\\*${name}\\*\\*:\\s*(.+)$`, 'm'))
  return m ? m[1].trim() : null
}

function nepsAtPin() {
  if (!existsSync(join(SPEC_ROOT, '.git'))) return null
  const git = (...args) =>
    execFileSync('git', ['-C', SPEC_ROOT, ...args], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
  try {
    git('cat-file', '-e', PIN.spec_commit)
  } catch {
    return null
  }
  const names = git('ls-tree', '-r', '--name-only', PIN.spec_commit, 'governance/')
    .split('\n')
    .filter(Boolean)
    .map((p) => p.replace(/^governance\//, ''))
    .filter((n) => /^nep-\d{4}-.+\.md$/.test(n))
    .sort(byCp)
  return names.map((file) => {
    const body = git('show', `${PIN.spec_commit}:governance/${file}`)
    const tokens = lex(body, file)
    const n = file.slice(4, 8)
    /* the H1 carries « NEP-0007 · <the one-line thesis> » · the register shows
       the thesis, and the number is already its own field */
    const h1 = body.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? file
    const headline = h1.replace(/^NEP-\d{4}\s*·\s*/, '')
    /* the Abstract's first paragraph, when the document has one */
    const abstract = tokens
      .slice(tokens.findIndex((t) => t.k === 'h' && /abstract/i.test(t.text ?? '')) + 1)
      .find((t) => t.k === 'p')
    return {
      n,
      slug: file.replace(/\.md$/, ''),
      file,
      headline,
      /* the header block, verbatim · the site never decides a NEP's status */
      title: headerField(body, 'Title') ?? headline,
      status: headerField(body, 'Status') ?? 'unstated',
      type: headerField(body, 'Type') ?? 'unstated',
      created: headerField(body, 'Created'),
      author: headerField(body, 'Author'),
      lede: abstract ? (abstract.inline ?? []).map((i) => i.text ?? '').join('').split(/(?<=\.)\s/)[0] : null,
      sections: tokens
        .filter((t) => t.k === 'h' && t.depth === 2)
        .map((t) => ({ title: t.text, anchor: t.id })),
      words: body.split(/\s+/).filter(Boolean).length,
      sha256: sha256(body),
      tokens,
    }
  })
}

const render = (neps) =>
  JSON.stringify(
    { neps_format: 1, spec_commit: PIN.spec_commit, spec_tree: PIN.spec_tree, neps },
    null,
    2,
  ) + '\n'

function project(catalog) {
  const rows = catalog.neps.map(({ tokens, ...rest }) => rest)
  const byStatus = {}
  for (const r of rows) byStatus[r.status] = (byStatus[r.status] ?? 0) + 1
  return `// neps.generated.ts — AUTO-GENERATED by scripts/build-neps.mjs
// from the nika-spec pack's governance/ AT THE PIN (${PIN.spec_commit.slice(0, 12)}),
// read with \`git show <pin>:governance/<file>\` — never from a moving checkout.
// DO NOT EDIT · regenerate: node scripts/build-neps.mjs
// Drift gate: node scripts/build-neps.mjs --check (exit 5) — wired into pnpm check.

/** one Nika Enhancement Proposal · the prose lives in the body module */
export interface Nep {
  /** the four-digit number · 0000 is the process itself */
  n: string
  slug: string
  file: string
  /** the H1's thesis, with the NEP-NNNN figure stripped */
  headline: string
  /** the header block, verbatim — the site never decides a NEP's status */
  title: string
  status: string
  type: string
  created: string | null
  author: string | null
  lede: string | null
  sections: { title: string; anchor: string }[]
  words: number
  sha256: string
}

/** the spec identity these proposals were read at */
export const NEPS_PIN = ${JSON.stringify({ spec_commit: catalog.spec_commit, spec_tree: catalog.spec_tree }, null, 1)} as const

/** every status the process carries, counted · never hand-typed */
export const NEP_STATUS_COUNTS: Record<string, number> = ${JSON.stringify(byStatus, null, 1)}

/** the proposals, in number order */
export const NEPS: Nep[] = ${JSON.stringify(rows, null, 1)}
`
}

/** the CHROME-LEAN half (register-diet law) · slugs only, eager anywhere */
function projectIds(catalog) {
  return `// nep-ids.generated.ts — AUTO-GENERATED by scripts/build-neps.mjs
// The CHROME-LEAN half: the slugs, for the map and the path census. The
// register itself rides src/lib/neps-access.ts (an async chunk).
// DO NOT EDIT · regenerate: node scripts/build-neps.mjs

/** every proposal, in number order */
export const NEP_SLUGS: string[] = ${JSON.stringify(catalog.neps.map((n) => n.slug), null, 1)}
`
}

function projectBody(catalog) {
  const entries = catalog.neps.map((c) => `  ${JSON.stringify(c.slug)}: ${JSON.stringify(c.tokens)},`).join('\n')
  return `// neps-body.generated.ts — AUTO-GENERATED by scripts/build-neps.mjs
// The governance corpus, lexed at the pin. HEAVY: src/** reaches it ONLY
// through src/lib/neps-access.ts (the register-diet law).
// DO NOT EDIT · regenerate: node scripts/build-neps.mjs
import type { BlogToken } from './blog.generated'

export const NEP_TOKENS: Record<string, BlogToken[]> = {
${entries}
}
`
}

const check = process.argv.includes('--check')
const fresh = nepsAtPin()

if (!fresh) {
  if (!existsSync(CATALOG)) {
    console.error('✗ no nika-spec checkout at the pin AND no committed neps catalog — nothing to derive from')
    process.exit(5)
  }
  console.log('○ neps · no reachable spec checkout at the pin · the committed catalog stands')
  if (!check) {
    const c = JSON.parse(readFileSync(CATALOG, 'utf8'))
    writeFileSync(OUT, project(c))
    writeFileSync(OUT_BODY, projectBody(c))
    writeFileSync(OUT_IDS, projectIds(c))
  }
  process.exit(0)
}

const catalogText = render(fresh)
const projected = project(JSON.parse(catalogText))
const projectedBody = projectBody(JSON.parse(catalogText))
const projectedIds = projectIds(JSON.parse(catalogText))

if (check) {
  const drift = []
  if (!existsSync(CATALOG) || readFileSync(CATALOG, 'utf8') !== catalogText) drift.push('public/spec/neps.json')
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== projected) drift.push('src/content/neps.generated.ts')
  if (!existsSync(OUT_BODY) || readFileSync(OUT_BODY, 'utf8') !== projectedBody) drift.push('src/content/neps-body.generated.ts')
  if (!existsSync(OUT_IDS) || readFileSync(OUT_IDS, 'utf8') !== projectedIds) drift.push('src/content/nep-ids.generated.ts')
  if (drift.length) {
    console.error(`✗ neps drift · run node scripts/build-neps.mjs\n  ${drift.join('\n  ')}`)
    process.exit(5)
  }
  console.log(`✓ neps in sync with nika-spec@${PIN.spec_commit.slice(0, 9)} · ${fresh.length} proposals`)
  process.exit(0)
}

mkdirSync(dirname(CATALOG), { recursive: true })
writeFileSync(CATALOG, catalogText)
writeFileSync(OUT, projected)
writeFileSync(OUT_BODY, projectedBody)
writeFileSync(OUT_IDS, projectedIds)
console.log(`wrote ${fresh.length} proposals at nika-spec@${PIN.spec_commit.slice(0, 9)}`)
