/* ─── build-bench · published bench witnesses → a typed projection + the served copy
   The leaderboard law (total-map plan · R7): a measured claim exists ONLY as
   the projection of a PUBLISHED receipt — no receipt, no number. A receipt is
   a directory under content/bench/<id>/ carrying:

     witness.json    the authored machine twin (joinable facts)
     PROVENANCE.md   the human prose (what ran, what it is NOT)
     table.md        the run's own measured output, verbatim
     evidence/       the exported pack (nika trace evidence · chain-checked)

   Two jobs, one convention:

     1 · content/bench/** → public/bench/**  — the served byte-copy (the
         /errors/catalog.json law: machines fetch the receipt itself)
     2 · witness.json files → src/content/bench.generated.ts — the compiled
         projection the catalog rooms read. BENCH_BY_MODEL joins by the seat's
         MODEL id (the part after provider/) so a room shows only measurements
         that name its own model.

   The vitest gate (bench.test.ts) re-derives the join INDEPENDENTLY, holds
   witness.json to table.md row for row, and holds the trace facts to
   evidence/pack.json — the twin can never drift from the run it describes.

   Run:   node scripts/build-bench.mjs
   Check: node scripts/build-bench.mjs --check   (exit 5 on drift) */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'content', 'bench')
const PUB = join(ROOT, 'public', 'bench')
const OUT = join(ROOT, 'src', 'content', 'bench.generated.ts')

/** codepoint order · never localeCompare (ICU varies per machine) */
const byCp = (a, b) => (a < b ? -1 : a > b ? 1 : 0)

const walk = (dir, base = '') =>
  readdirSync(dir).flatMap((name) => {
    const rel = base ? `${base}/${name}` : name
    return statSync(join(dir, name)).isDirectory() ? walk(join(dir, name), rel) : [rel]
  })

function witnesses() {
  if (!existsSync(SRC)) return []
  return readdirSync(SRC)
    .filter((d) => statSync(join(SRC, d)).isDirectory())
    .sort(byCp)
    .map((id) => {
      const w = JSON.parse(readFileSync(join(SRC, id, 'witness.json'), 'utf8'))
      if (w.id !== id) throw new Error(`witness id "${w.id}" ≠ its directory "${id}"`)
      return w
    })
}

function project(rows) {
  /* the join: seat "ollama/llama3.2:3b" → model id "llama3.2:3b" · a model
     can accumulate rows across witnesses (newest witness first) */
  const byModel = {}
  for (const w of [...rows].sort((a, b) => byCp(b.date, a.date))) {
    for (const s of w.seats) {
      const model = s.model.slice(s.model.indexOf('/') + 1)
      ;(byModel[model] ??= []).push({
        witness: w.id,
        date: w.date,
        seat: s.model,
        latency_ms: s.latency_ms,
        chars: s.chars,
        href: `/bench/${w.id}/PROVENANCE.md`,
      })
    }
  }
  return `// bench.generated.ts — AUTO-GENERATED by scripts/build-bench.mjs
// from content/bench/*/witness.json (each the machine twin of a PUBLISHED
// bench receipt · the run's own evidence pack rides beside it, served
// byte-identical under /bench/). DO NOT EDIT · regenerate:
// node scripts/build-bench.mjs · drift gate: src/test/bench.test.ts.

export interface BenchSeatRow {
  /** the witness directory id · also the served receipt's /bench/<id>/ home */
  witness: string
  date: string
  /** the seat as the workflow named it (provider/model) */
  seat: string
  latency_ms: number
  chars: number
  /** the served human receipt this row projects from */
  href: string
}

/** every published witness, whole (small by law: one row per RUN, not per query) */
export const BENCH_WITNESSES = ${JSON.stringify(rows, null, 2)} as const

/** measured rows keyed by MODEL id (the part after provider/) · newest witness first */
export const BENCH_BY_MODEL: Record<string, BenchSeatRow[]> = ${JSON.stringify(byModel, null, 2)}
`
}

function syncPub(write) {
  const drifts = []
  if (!existsSync(SRC)) return drifts
  for (const rel of walk(SRC).sort(byCp)) {
    const src = readFileSync(join(SRC, rel))
    const dst = join(PUB, rel)
    if (!existsSync(dst) || !readFileSync(dst).equals(src)) {
      if (write) {
        mkdirSync(dirname(dst), { recursive: true })
        writeFileSync(dst, src)
      } else drifts.push(`public/bench/${rel}`)
    }
  }
  return drifts
}

const mode = process.argv[2]
const rows = witnesses()
if (mode === '--check') {
  const want = project(rows)
  const have = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  const pubDrift = syncPub(false)
  if (want !== have || pubDrift.length > 0) {
    if (want !== have) console.error('✗ bench projection drift: src/content/bench.generated.ts')
    for (const d of pubDrift) console.error(`✗ served receipt drift: ${d}`)
    console.error('  run node scripts/build-bench.mjs')
    process.exit(5)
  }
  console.log(`✓ bench witnesses in sync (${rows.length} published)`)
} else {
  writeFileSync(OUT, project(rows))
  syncPub(true)
  console.log(`wrote src/content/bench.generated.ts + public/bench/ (${rows.length} witnesses)`)
}
