#!/usr/bin/env node
/* ── build-anatomy.mjs · vendor the engine's own reading of the corpus ───────
   WO-14, first leg: for every showcase room (the SERVED W2 form — the door
   pass the visitor copies) and every library flagship (already W2 on disk),
   run `nika inspect --format json` on the RELEASED binary and vendor the
   graph. The rooms then render the ENGINE's verdict beside the file — the
   anatomy is never re-derived site-side, never hand-typed.

   Vendored-catalog law (build-tools/build-providers precedent): the build
   NEVER probes the binary — refresh is a deliberate manual run:
     node scripts/build-anatomy.mjs
   Binary via NIKA_BIN, else `nika` on PATH. Deterministic emission (stable
   key order · sorted slugs); src/test/anatomy.test.ts recompiles and
   byte-diffs, and pins the slug set against SHOWCASE_DAG + FLAGSHIPS.

   graph_format is vendored verbatim: when the contract ships format 2
   (byte-identical CLI/LSP/MCP · the WO-14 oracle gate), a refresh here is
   the whole upgrade. */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const bin = process.env.NIKA_BIN || 'nika'

const version = execFileSync(bin, ['--version'], { encoding: 'utf8', timeout: 5000 })
  .trim()
  /* the VERSION token · 0.109 prints `nika X.Y.Z (hash)` · the bare semver is the identity */
  .split(/\s+/)[1]

/* corpus 1 · the 26 showcase rooms — one clock (0.106 flag-day): the
   projector emission IS what the room serves, so the engine reads it
   verbatim (the w1-to-w2 door retired with the pin flip) */
const ucSrc = readFileSync(join(ROOT, 'src/sections/usecases-yaml.generated.ts'), 'utf8')
/* lex the template literal with its escapes (\` \$ \\) — a lazy [\s\S]*?
   stops at the first ESCAPED backtick before a comma (`lastmod`, …) and
   truncates the file mid-yaml */
const showcases = [...ucSrc.matchAll(/'([a-z0-9-]+)': `((?:[^`\\]|\\[\s\S])*)`,\n/g)].map((m) => ({
  slug: m[1],
  yaml: m[2].replace(/\\([`$\\])/g, '$1'),
}))

/* corpus 2 · the 7 served flagships (public/library · W105-native + SPDX) */
const flagships = readdirSync(join(ROOT, 'public/library'))
  .filter((f) => f.endsWith('.nika.yaml'))
  .map((f) => ({
    slug: f.replace(/\.nika\.yaml$/, ''),
    yaml: readFileSync(join(ROOT, 'public/library', f), 'utf8'),
  }))

const work = mkdtempSync(join(tmpdir(), 'anatomy-'))
const graphs = {}
/* FLAGSHIPS · the seven recorded public/library files still speak the
   pre-0.109 envelope. `nika inspect` refuses them (PARSE-005). Re-authoring
   without `nika run --json` would make the home film lie, so a dead-grammar
   file reuses the previously vendored graph instead of aborting the
   showcase refresh. */
const prevSrc = readFileSync(join(ROOT, 'src/content/anatomy.generated.ts'), 'utf8')
const prevJson = prevSrc.match(/export const ANATOMY: Record<string, Anatomy> = (\{[\s\S]*\})\n/)
const previous = prevJson ? JSON.parse(prevJson[1]) : {}
const deadGrammar = (yaml) => /^nika:\s*v1\b/m.test(yaml) || /^workflow:/m.test(yaml)
/* the flat spec rename made five slugs live in BOTH corpora (etl-quarantine ·
   meeting-actions · price-watch · social-repurpose · standup-digest — the
   flagship file is a distinct curated variant). The rooms that render this
   map are the /use-cases rooms, and anatomy.test pins task-set parity with
   SHOWCASE_DAG — so on a shared slug the SHOWCASE reading wins (last write). */
for (const { slug, yaml } of [...flagships, ...showcases]) {
  if (deadGrammar(yaml)) {
    if (!previous[slug]) {
      console.error(`build-anatomy: ${slug} is dead-grammar and has no previous graph (FLAGSHIPS)`)
      process.exit(1)
    }
    graphs[slug] = previous[slug]
    continue
  }
  const file = join(work, `${slug}.nika.yaml`)
  writeFileSync(file, yaml)
  const raw = JSON.parse(
    execFileSync(bin, ['inspect', file, '--format', 'json'], { encoding: 'utf8', timeout: 20000 }),
  )
  graphs[slug] = {
    graph_format: raw.graph_format,
    workflow: raw.workflow,
    nodes: raw.nodes.map((n) => ({
      id: n.id,
      verb: n.verb,
      ...(n.tool != null ? { tool: n.tool } : {}),
      ...(n.model != null ? { model: n.model } : {}),
      ...(n.when != null ? { when: n.when } : {}),
      ...(n.fan_out != null ? { fan_out: n.fan_out } : {}),
      permits: n.permits ?? [],
      ...(n.cost_interval != null ? { cost_interval: n.cost_interval } : {}),
    })),
    edges: raw.edges.map((e) => ({ from: e.from, to: e.to, kind: e.kind })),
  }
}
rmSync(work, { recursive: true, force: true })

/* deterministic emission · stable sorted key order */
const anatomy = Object.fromEntries(Object.entries(graphs).sort(([a], [b]) => (a < b ? -1 : 1)))

const ts = `// anatomy.generated.ts — AUTO-GENERATED by scripts/build-anatomy.mjs:
// the ENGINE'S OWN reading (\`nika inspect --format json\` · the released
// binary) of every showcase room (as SERVED · the door's W2 form) and every
// library flagship. DO NOT EDIT · regenerate: node scripts/build-anatomy.mjs
// Drift gates: src/test/anatomy.test.ts (byte-diff · slug parity · node⊆dag).

export interface AnatomyNode {
  id: string
  verb: 'infer' | 'exec' | 'invoke' | 'agent'
  tool?: string
  model?: string
  when?: string
  fan_out?: unknown
  /** the permit rows THIS node needs, in the engine's own words */
  permits: string[]
  cost_interval?: unknown
}
export interface AnatomyEdge {
  from: string
  to: string
  kind: string
}
export interface Anatomy {
  graph_format: number
  workflow: string
  nodes: AnatomyNode[]
  edges: AnatomyEdge[]
}

/** the engine release these graphs were read from (the provenance stamp) */
export const ANATOMY_ENGINE = ${JSON.stringify(version)}

export const ANATOMY: Record<string, Anatomy> = ${JSON.stringify(anatomy, null, 2)}
`
writeFileSync(join(ROOT, 'src/content/anatomy.generated.ts'), ts)
console.log(
  `wrote src/content/anatomy.generated.ts (${Object.keys(anatomy).length} graphs · engine ${version} · format ${Object.values(anatomy)[0]?.graph_format})`,
)
