#!/usr/bin/env node
/* ── build-anatomy.mjs · vendor the engine's own reading of the corpus ───────
   WO-14, first leg: for every showcase room (the SERVED W2 form — the door
   pass the visitor copies) and every library flagship (already W2 on disk),
   run `nika inspect --format json` on the RELEASED binary and vendor the
   graph. The rooms then render the ENGINE's verdict beside the file — the
   anatomy is never re-derived site-side, never hand-typed.

   Vendored-catalog law (build-tools/build-providers precedent): the build
   NEVER probes the binary — refresh is a deliberate manual run:
     node scripts/build-anatomy.mjs
   Binary via NIKA_BIN, else `nika` on PATH. Deterministic emission (stable
   key order · sorted slugs); src/test/anatomy.test.ts recompiles and
   byte-diffs, and pins the slug set against SHOWCASE_DAG + FLAGSHIPS.

   graph_format is vendored verbatim: when the contract ships format 2
   (byte-identical CLI/LSP/MCP · the WO-14 oracle gate), a refresh here is
   the whole upgrade. */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { w1ToW2 } from './lib/w1-to-w2.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const bin = process.env.NIKA_BIN || 'nika'

const version = execFileSync(bin, ['--version'], { encoding: 'utf8', timeout: 5000 })
  .trim()
  .replace(/^nika\s+/, '')

/* corpus 1 · the 26 showcase rooms — the projector emission is the ratified
   clock (W1); the ROOM serves the door output, so the engine reads the
   door output (anything else would vendor the anatomy of a file the
   visitor never sees) */
const ucSrc = readFileSync(join(ROOT, 'src/sections/usecases-yaml.generated.ts'), 'utf8')
const showcases = [...ucSrc.matchAll(/'([a-z0-9-]+)': `([\s\S]*?)`,\n/g)].map((m) => ({
  slug: m[1],
  yaml: w1ToW2(m[2].replace(/\\([`$\\])/g, '$1')),
}))

/* corpus 2 · the 7 served flagships (public/library · already W2 + SPDX) */
const flagships = readdirSync(join(ROOT, 'public/library'))
  .filter((f) => f.endsWith('.nika.yaml'))
  .map((f) => ({
    slug: f.replace(/\.nika\.yaml$/, ''),
    yaml: readFileSync(join(ROOT, 'public/library', f), 'utf8'),
  }))

const work = mkdtempSync(join(tmpdir(), 'anatomy-'))
const anatomy = {}
for (const { slug, yaml } of [...showcases, ...flagships].sort((a, b) => (a.slug < b.slug ? -1 : 1))) {
  const file = join(work, `${slug}.nika.yaml`)
  writeFileSync(file, yaml)
  const raw = JSON.parse(
    execFileSync(bin, ['inspect', file, '--format', 'json'], { encoding: 'utf8', timeout: 20000 }),
  )
  anatomy[slug] = {
    graph_format: raw.graph_format,
    workflow: raw.workflow,
    nodes: raw.nodes.map((n) => ({
      id: n.id,
      verb: n.verb,
      ...(n.tool != null ? { tool: n.tool } : {}),
      ...(n.model != null ? { model: n.model } : {}),
      ...(n.when != null ? { when: n.when } : {}),
      ...(n.fan_out != null ? { fan_out: n.fan_out } : {}),
      permits: n.permits ?? [],
      ...(n.cost_interval != null ? { cost_interval: n.cost_interval } : {}),
    })),
    edges: raw.edges.map((e) => ({ from: e.from, to: e.to, kind: e.kind })),
  }
}
rmSync(work, { recursive: true, force: true })

const ts = `// anatomy.generated.ts — AUTO-GENERATED by scripts/build-anatomy.mjs:
// the ENGINE'S OWN reading (\`nika inspect --format json\` · the released
// binary) of every showcase room (as SERVED · the door's W2 form) and every
// library flagship. DO NOT EDIT · regenerate: node scripts/build-anatomy.mjs
// Drift gates: src/test/anatomy.test.ts (byte-diff · slug parity · node⊆dag).

export interface AnatomyNode {
  id: string
  verb: 'infer' | 'exec' | 'invoke' | 'agent'
  tool?: string
  model?: string
  when?: string
  fan_out?: unknown
  /** the permit rows THIS node needs, in the engine's own words */
  permits: string[]
  cost_interval?: unknown
}
export interface AnatomyEdge {
  from: string
  to: string
  kind: string
}
export interface Anatomy {
  graph_format: number
  workflow: string
  nodes: AnatomyNode[]
  edges: AnatomyEdge[]
}

/** the engine release these graphs were read from (the provenance stamp) */
export const ANATOMY_ENGINE = ${JSON.stringify(version)}

export const ANATOMY: Record<string, Anatomy> = ${JSON.stringify(anatomy, null, 2)}
`
writeFileSync(join(ROOT, 'src/content/anatomy.generated.ts'), ts)
console.log(
  `wrote src/content/anatomy.generated.ts (${Object.keys(anatomy).length} graphs · engine ${version} · format ${Object.values(anatomy)[0]?.graph_format})`,
)
