/* ─── build-adrs · the engine's decision record → a typed projection ─────────
   public/engine/adr/index.json has been vendored at the engine release pin
   and digest-verified since the resync lane shipped: 44KB, 71 entries, every
   one carrying title, status, date and its cross-reference edges. Nothing
   consumed it. It rode every deploy as dead payload, behind an estate
   evidence string that named « the /engineering world » as its consumer — a
   world that does not exist. This generator is the consumer.

   The projection is LEAN by construction (the register-diet law): the page
   renders 71 rows, so it needs the fields a row shows and the edges it
   counts, not the crate lists. The heavy input stays in public/, one fetch
   away for anyone who wants the whole record.

   No new pin, no new vendoring, no network: the input is already on disk and
   already gated by `node scripts/engine-resync.mjs --check`.

   Run:   node scripts/build-adrs.mjs
   Check: node scripts/build-adrs.mjs --check   (exit 5 on drift) */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'public', 'engine', 'adr', 'index.json')
const OUT = join(ROOT, 'src', 'content', 'adrs.generated.ts')
const PIN = JSON.parse(readFileSync(join(ROOT, '.github/nika-engine-pin.json'), 'utf8'))

/** codepoint order · never localeCompare (ICU varies per machine) */
const byCp = (a, b) => (a < b ? -1 : a > b ? 1 : 0)

function project() {
  const raw = JSON.parse(readFileSync(SRC, 'utf8'))
  const rows = [...raw.adrs]
    .sort((a, b) => byCp(a.id, b.id))
    .map((a) => ({
      id: a.id,
      title: a.title,
      status: a.status,
      date: a.date,
      /* the edge COUNT, not the edges: a register row says « this decision is
         cited six times », and the whole graph lives in the machine index */
      cites:
        (a.related?.length ?? 0) +
        (a.requires?.length ?? 0) +
        (a.enables?.length ?? 0) +
        (a.supersedes?.length ?? 0) +
        (a.superseded_by?.length ?? 0),
      supersedes: a.supersedes ?? [],
      superseded_by: a.superseded_by ?? [],
      layers: a.affects_layers ?? [],
      tags: (a.tags ?? []).slice(0, 4),
    }))

  const byStatus = {}
  for (const r of rows) byStatus[r.status] = (byStatus[r.status] ?? 0) + 1

  return `// adrs.generated.ts — AUTO-GENERATED by scripts/build-adrs.mjs
// from public/engine/adr/index.json, itself a byte-copy of docs/adr/index.json
// at the engine release pin (${PIN.release_tag}), digest-verified by
// scripts/engine-resync.mjs. DO NOT EDIT · regenerate: node scripts/build-adrs.mjs
// Drift gate: node scripts/build-adrs.mjs --check (exit 5) — wired into pnpm check.

/** one architecture decision · the row a register shows */
export interface Adr {
  id: string
  title: string
  /** accepted · proposed · superseded · rejected */
  status: string
  date: string
  /** how many other decisions this one names, in either direction */
  cites: number
  supersedes: string[]
  superseded_by: string[]
  /** the engine layers it binds (L0 … L5) */
  layers: string[]
  tags: string[]
}

/** the engine release these decisions were read at */
export const ADRS_PIN = ${JSON.stringify({ release_tag: PIN.release_tag, commit: PIN.engine_commit }, null, 1)} as const

/** every status the record carries, counted · never hand-typed */
export const ADR_STATUS_COUNTS: Record<string, number> = ${JSON.stringify(byStatus, null, 1)}

/** the record, in decision order (ADR-001 first) */
export const ADRS: Adr[] = ${JSON.stringify(rows, null, 1)}
`
}

if (!existsSync(SRC)) {
  console.error(`✗ no vendored ADR index at ${SRC} — run node scripts/engine-resync.mjs --write`)
  process.exit(5)
}

const text = project()
if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== text) {
    console.error('✗ adrs drift · run node scripts/build-adrs.mjs\n  src/content/adrs.generated.ts')
    process.exit(5)
  }
  const n = JSON.parse(readFileSync(SRC, 'utf8')).adrs.length
  console.log(`✓ adrs in sync with the engine pin (${PIN.release_tag}) · ${n} decisions`)
  process.exit(0)
}

writeFileSync(OUT, text)
console.log(
  `wrote ${JSON.parse(readFileSync(SRC, 'utf8')).adrs.length} decisions at ${PIN.release_tag}`,
)
