#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
#
# estate.py — the provenance manifest: every tracked file declares what it IS.
#
# OBSERVATION MODE (E0): estate.yaml declares provenance — authored ·
# generated · pinned-copy · foreign — it enforces nothing. The point is to
# make the repo's derivation topology explicit: which files a human writes,
# which files a tool re-derives (and from what, gated by which CI check),
# so drift between "what we believe" and "what is" becomes observable.
#
# SCHEMA 2 (pattern manifest). This tree tracks ~950 files — a per-file
# manifest (schema 1, the nika-registry shape) would bury the signal. Schema
# 2 adds `patterns:`: homogeneous groups (one glob → one class + shared
# evidence/derivation) carrying a member count and an AGGREGATE sha256
# (sha256 of the sorted "path sha256-of-bytes" lines of the members) — any
# member byte-change OR membership change re-renders differently, so --check
# still catches every drift at file granularity. `files:` lists per-file
# entries: exact-path overrides and evidence-bearing singletons (generated /
# pinned exceptions), which are matched BEFORE patterns.
#
# Classification is EVIDENCE-driven, never assumed:
#   1. scripts/spec-resync.contract.json — the repo's own machine-readable
#      derivation contract (16 sha256-pinned generators · 21 pinned outputs ·
#      the exact nika-spec commit) is read directly; its `runtime: copy`
#      twins land in `pinned-copy`.
#   2. In-file generation markers ("AUTO-GENERATED by <tool>" · "generated
#      by design/build.mjs" · "_generated" keys) are read from the first
#      bytes of each file; the tool AND its declared drift gate are
#      extracted from the marker itself where present.
#   3. Files with no such evidence land in `authored` with
#      `note: unverified-default` — honesty over completeness.
#
# Derived, never authored (the house projection pattern): --write
# regenerates estate.yaml from the tracked tree; --check re-emits and
# byte-compares. On divergence --check exits 5 (the ssot-compiler
# convention — deliberately distinct from the sibling drift gates' exit 1,
# so an estate divergence is distinguishable in CI logs).
#
# Usage:
#   python3 scripts/estate.py --write   # regenerate estate.yaml
#   python3 scripts/estate.py --check   # drift gate (exit 5 on divergence)

import hashlib
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ESTATE = ROOT / "estate.yaml"
ESTATE_SCHEMA = 2
SELF = "scripts/estate.py"

CLASSES = {
    "authored": "a human writes here",
    "generated": "derived by a tool from declared inputs — regenerate, never hand-edit",
    "pinned-copy": "byte-copy pinned to an upstream rev",
    "foreign": "pointer to a third-party sovereign source",
}

GATE_YML = ".github/workflows/gate.yml"
RESYNC_YML = ".github/workflows/spec-resync.yml"
CONTRACT_PATH = "scripts/spec-resync.contract.json"

# ── the repo's own derivation contract (evidence source #1) ────────────────


def load_contract() -> dict:
    return json.loads((ROOT / CONTRACT_PATH).read_text())


def shipped_engine() -> str:
    doc = json.loads((ROOT / "public/spec/shipped/PROVENANCE.json").read_text())
    return doc.get("engine_version", "unknown")


# ── in-file generation markers (evidence source #2) ────────────────────────
# Empirically verified 2026-07-22: this regex over the first 480 bytes hits
# exactly the generated surfaces (126 files) and zero prose/generator files.

MARK = re.compile(
    r'(?:AUTO-)?GENERATED by|generated by design/build\.mjs|"_generated"|"derived_from"'
)
TOOL_IN_MARK = re.compile(r"((?:scripts|design)/[A-Za-z0-9_@./-]+\.(?:mjs|py))")
GATE_IN_MARK = re.compile(r"(?:Drift gates?|Gates?):\s*([^\n]+)")


def head_chunk(body: bytes) -> str:
    return body[:480].decode("utf-8", "replace")


def marker_hit(chunk: str) -> bool:
    return MARK.search(chunk) is not None


def marker_tool(chunk: str) -> str | None:
    m = re.search(r"GENERATED by(.{0,90})", chunk, re.S)
    if m:
        t = TOOL_IN_MARK.search(m.group(1))
        if t:
            return t.group(1)
    if "generated by design/build.mjs" in chunk:
        return "design/build.mjs"
    return None


def marker_gate(chunk: str) -> str | None:
    m = GATE_IN_MARK.search(chunk)
    if not m:
        return None
    return m.group(1).strip().rstrip(",").removesuffix(" and").rstrip(".").strip()


# Known tools → their commit-time drift gate + declared inputs (used when the
# marker itself does not carry a "Drift gate:" line).
ATLAS = "scripts/atlas/build-atlas.mjs"
ATLAS_GATE = (
    "src/test/atlas.test.ts + design-graph.test.ts (+ atlas-census/nav/sets companions) "
    f"recompile + byte-diff — pnpm test in {GATE_YML}"
)
ATLAS_INPUTS = [
    "scripts/atlas/sets.yaml",
    "scripts/atlas/market-vocab.yaml",
    "the gated site sources sets.yaml declares (site facts + the spec spine)",
]
ICONS = "design/build.mjs"
ICONS_GATE = (
    "pnpm check → node design/build.mjs --check (drift + orphan sweep) — "
    f"the {GATE_YML} typecheck step"
)
ICONS_INPUTS = [
    "design/icons.yaml",
    "design/svg/**",
    "src/canon.generated.ts (builtin parity)",
    "src/styles/tokens.css (hue parity)",
]
BLOG = "scripts/build-blog.mjs"
BLOG_GATE = f"src/test/blog.test.ts + src/test/blog-twins.test.ts — pnpm test in {GATE_YML}"

TOOL_GATES = {
    ATLAS: ATLAS_GATE,
    ICONS: ICONS_GATE,
    BLOG: BLOG_GATE,
}
TOOL_INPUTS = {
    ATLAS: ATLAS_INPUTS,
    ICONS: ICONS_INPUTS,
    BLOG: ["content/blog/*.md", "src/canon.generated.ts (canon marker values)"],
    "scripts/build-anatomy.mjs": [
        "the released nika binary (`nika inspect --format json`)",
        "the showcase rooms as SERVED + public/library/*.nika.yaml flagships",
    ],
    "scripts/build-i18n-pages.mjs": ["content/i18n/<locale>/*.yaml (the reviewed L1 corpus)"],
    "scripts/build-terminal-captures.mjs": [
        "the released nika binary (runs captured VERBATIM · NO_COLOR)"
    ],
}
GATE_FALLBACK = (
    "none declared in the marker — regenerate deliberately via the tool "
    "(observation mode records, it does not enforce)"
)


def tracked_files() -> list:
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "-z"], capture_output=True, check=True
    )
    files = {f for f in out.stdout.decode().split("\0") if f}
    # The generator always classifies itself; the manifest never lists
    # itself (its sha256 cannot contain its own hash).
    files.add(SELF)
    files.discard("estate.yaml")
    return sorted(files)


# ── per-file overrides (exact path · matched before patterns) ──────────────


def auth(evidence: str, note: str | None = None) -> dict:
    out = {"class": "authored", "evidence": evidence}
    if note:
        out["note"] = note
    return out


def gen(evidence: str, tool: str, gate: str, inputs: list, note: str | None = None) -> dict:
    out = {
        "class": "generated",
        "evidence": evidence,
        "derivation": {"tool": tool, "gate": gate, "inputs": inputs},
    }
    if note:
        out["note"] = note
    return out


def pin(evidence: str, tool: str, gate: str, inputs: list, note: str | None = None) -> dict:
    out = gen(evidence, tool, gate, inputs, note)
    out["class"] = "pinned-copy"
    return out


def build_overrides(contract: dict, engine: str) -> dict:
    spec = contract["spec"]
    spec_ref = f"{spec['repository']}@{spec['commit'][:12]}"
    shipped_tool = "node scripts/build-shipped-spec.mjs (deliberate manual vendor run — the build NEVER probes the binary)"
    shipped_gate = (
        "src/test/onpage-yaml.test.ts validates the on-page corpus against THIS shipped schema; "
        "/sources renders the ratified↔shipped drift"
    )
    lens_gate = f"pnpm lens:integrity (scripts/verify-lens-ci.mjs) + .github/workflows/lens-gates.yml"
    catalog_law = (
        "vendored-catalog law (build-shipped-spec.mjs header): the build never probes the binary — "
        "refresh is a deliberate manual run against the released engine"
    )
    sync_note = "version strings rewritten by scripts/sync-version.mjs on release heal (.github/workflows/release-heal.yml) — bot-maintained fields inside an authored file"

    return {
        # ── prose · policy · agent context ────────────────────────────────
        "README.md": auth("prose entry surface · no generation marker"),
        "AGENTS.md": auth("hand-written agent entry per the AGENTS.md convention"),
        ".claude/CLAUDE.md": auth("hand-written agent context for this repo"),
        "BRAND.md": auth("prose brand voice doc · no generation marker"),
        "CONTRIBUTING.md": auth("prose contribution policy · no generation marker"),
        "DEPLOY.md": auth("prose deploy runbook · no generation marker"),
        "SECURITY.md": auth("prose security policy · no generation marker"),
        "THIRD_PARTY_NOTICES.md": auth(
            "hand-kept third-party license record (fonts self-hosted · icon system declared house-owned)"
        ),
        # ── root configs ──────────────────────────────────────────────────
        ".gitattributes": auth("hand-kept git attributes"),
        ".gitignore": auth("hand-kept ignore list"),
        ".npmrc": auth("hand-kept npm config"),
        ".nvmrc": auth("hand-kept node version pin"),
        "package.json": auth("hand-kept manifest (scripts + pinned deps + packageManager)"),
        "tsconfig.json": auth("hand-written TS project references root"),
        "tsconfig.app.json": auth("hand-written TS config (app)"),
        "tsconfig.node.json": auth("hand-written TS config (node tooling)"),
        "vite.config.ts": auth("hand-written Vite config"),
        "vitest.config.ts": auth("hand-written Vitest config"),
        "eslint.config.js": auth("hand-written ESLint flat config"),
        "react-ssg.config.ts": auth("hand-written SSG route config"),
        "index.html": auth("hand-written Vite entry shell"),
        "site.config.ts": auth(
            "hand-written site facts",
            note="scripts/atlas/build-atlas.mjs rewrites a derived block in place when sets.yaml changes (build-atlas.mjs:1715) — a bot-maintained region inside an authored file",
        ),
        "pending-error-codes.ts": auth(
            "hand-kept escrow list — its own header: list a code the day the canon mints it, DELETE the entry the day the resync pin advances past the mint"
        ),
        ".do/app.yaml": auth(
            "hand-written DigitalOcean App Platform spec",
            note="byte-pinned by the resync contract's publish_input_contract and the LENS integrity baseline — hand-edits must re-pin",
        ),
        # ── the deploy/CI meta surface ────────────────────────────────────
        ".github/nika-spec-pin.json": auth(
            "the resync INPUT — a deliberately bumped pin carrying the full nika-spec commit AND tree; its $comment narrates the LENS-011 trust model",
            note="scripts/lens/repin-spec-resync-contract.mjs re-derives the resync contract FROM this pin; public/.well-known/nika-spec-pin.json is its byte-identical generated twin",
        ),
        # ── lockfiles (tool-maintained) ───────────────────────────────────
        "pnpm-lock.yaml": gen(
            "pnpm lockfile — tool-maintained, never hand-edited",
            "pnpm install (pnpm pinned via packageManager)",
            f"pnpm install --frozen-lockfile in {GATE_YML} (+ deep-belts · visual.yml · lens-gates.yml)",
            ["package.json"],
        ),
        "scripts/media/package-lock.json": gen(
            "npm lockfile for the media pipeline's own deps — tool-maintained",
            "npm install (scripts/media lane)",
            "none in CI — the media pipeline is a deliberate manual lane (scripts/media/README.md)",
            ["scripts/media/package.json"],
        ),
        "scripts/media/package.json": auth("hand-kept manifest for the media pipeline lane"),
        # ── blog projections without in-file markers ──────────────────────
        "public/rss.xml": gen(
            "row of BLOG_GENERATED_MIRRORS in scripts/build-blog.mjs (OUT_RSS · build-blog.mjs:28)",
            "node scripts/build-blog.mjs",
            BLOG_GATE,
            ["content/blog/*.md"],
        ),
        "public/llms-full.txt": gen(
            "row of BLOG_GENERATED_MIRRORS in scripts/build-blog.mjs; its own header: 'The complete blog, newest first, as raw markdown (source: content/blog in the site repo)'",
            "node scripts/build-blog.mjs",
            f"src/test/llms.test.ts + src/test/blog.test.ts — pnpm test in {GATE_YML}",
            ["content/blog/*.md"],
        ),
        "public/llms.txt": auth(
            "hand-curated llms.txt (llmstxt.org) — NOT in BLOG_GENERATED_MIRRORS",
            note=f"{sync_note}; counts drift-gated by src/test/llms.test.ts + llms-urls.test.ts against the canon projection",
        ),
        # ── atlas projections without in-file markers ─────────────────────
        "public/i18n/untranslatables.json": gen(
            "in-file 'derived_from: build-atlas (the language graph)' key",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/ontology/language.json": gen(
            "written by build-atlas.mjs:1731 (the language-graph twin · language_graph shape)",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/map/constellation.svg": gen(
            "written by build-atlas.mjs:1730 — the served twin of src/assets/constellation.generated.svg",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "src/assets/constellation.generated.svg": gen(
            "written by build-atlas.mjs:1716 (.generated. basename · no textual marker inside the SVG)",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/redirects.json": gen(
            "written by build-atlas.mjs:1736 (redirects_format shape)",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/sitemap/index.html": gen(
            "the atlas redirect stub template (build-atlas.mjs stub() · the redirects.json '/sitemap' row): meta-refresh + canonical, no prose comment",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/design-palette.json": gen(
            "in-file '_generated: scripts/atlas/build-atlas.mjs — DO NOT EDIT' key",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        "public/design-tokens.dtcg.json": gen(
            "in-file $description: 'AUTO-GENERATED by scripts/atlas/build-atlas.mjs from sets.yaml design: + the nika-spec spine'",
            f"node {ATLAS} (pnpm atlas)",
            ATLAS_GATE,
            ATLAS_INPUTS,
        ),
        # ── the released binary's baked surfaces ──────────────────────────
        "public/tools/catalog.json": gen(
            f"version field '{engine}' == the released engine; {catalog_law}",
            "node scripts/build-tools.mjs (NIKA_BIN or `nika` on PATH)",
            f"src/test/tools.test.ts + src/test/version.test.ts — pnpm test in {GATE_YML}",
            [f"nika {engine} (the released binary's own tool catalog)"],
        ),
        "public/providers/catalog.json": gen(
            f"version field '{engine}' == the released engine; {catalog_law}",
            "node scripts/build-providers.mjs (NIKA_BIN or `nika` on PATH)",
            f"src/test/providers.test.ts — pnpm test in {GATE_YML}",
            [f"nika {engine} (the released binary's own provider catalog)"],
        ),
        "public/spec/shipped/canon.yaml": pin(
            f"byte-copy of what the RELEASED binary embeds (`nika spec --canon` · engine {engine} per PROVENANCE.json) — the SHIPPED clock of the two-clocks doctrine (build-shipped-spec.mjs header)",
            shipped_tool,
            shipped_gate,
            [f"nika {engine} (the released binary)"],
        ),
        "public/spec/shipped/workflow.schema.json": pin(
            f"byte-copy of what the RELEASED binary embeds (`nika spec --schema` · engine {engine} per PROVENANCE.json) — the SHIPPED clock of the two-clocks doctrine",
            shipped_tool,
            shipped_gate,
            [f"nika {engine} (the released binary)"],
        ),
        "public/spec/shipped/PROVENANCE.json": gen(
            f"the vendor run's receipt: engine_version {engine} + source 'nika spec --schema / --canon'",
            shipped_tool,
            shipped_gate,
            [f"nika {engine} (the released binary)"],
        ),
        # ── the LENS pin/baseline lane ────────────────────────────────────
        CONTRACT_PATH: gen(
            "the versioned resync contract: sha256-pinned generators + outputs + toolchain + publish-input contract, all derived from the spec pin",
            "node scripts/lens/repin-spec-resync-contract.mjs (deliberate repin)",
            f"pnpm spec-resync:verify (LENS-011 scripts/verify_generated_outputs.mjs) + the spec-resync adversarial suite + {RESYNC_YML}",
            [".github/nika-spec-pin.json", f"{spec_ref} (the pinned spec tree)", "the generator scripts (sha256-pinned in the contract)"],
        ),
        "scripts/lens/contracts/integrity.v1.json": gen(
            "digest baseline of the publish-input artifacts (path + sha256 census)",
            "node scripts/lens/repin-integrity.mjs (deliberate repin)",
            lens_gate,
            ["the tracked publish-input artifacts (digest census)"],
        ),
        "scripts/lens/contracts/carrier-universe.v1.json": gen(
            "the exhaustive carrier census (authority: independent-exhaustive-carrier-universe)",
            "node scripts/lens/repin-carrier-universe.mjs (deliberate repin)",
            lens_gate,
            ["the census roots the contract declares (src/** · content/blog · public/** · scripts/build-*)"],
        ),
        "scripts/lens/contracts/release-attestation.v1.json": gen(
            f"attestation of the pinned spec release closure (release_id spec-{spec['commit'][:12]}…-stable); sha256-bound into .github/nika-spec-pin.json",
            "the repin lane (spec release closure)",
            lens_gate,
            [f"{spec_ref} release identity"],
        ),
        "scripts/lens/fixtures/negative.v1.json": auth(
            "hand-written adversarial negative fixture — the lens gates must FAIL on it"
        ),
        # ── public root singletons ────────────────────────────────────────
        "public/404.html": auth(
            "hand-written static error shell — DigitalOcean's error_document serves it for un-prerendered deep links (pending-error-codes.ts header)"
        ),
        "public/docs/index.html": auth(
            "hand-written courtesy redirect to docs.nika.sh — bespoke prose comment, NOT the atlas stub template"
        ),
        "public/ontology/design/index.html": auth(
            "static ontology landing page — design/build.mjs's output list excludes it and no other writer was found",
            note="unverified-default",
        ),
        "public/robots.txt": auth("hand-kept crawler policy"),
        "public/humans.txt": auth("hand-written humans.txt", note=sync_note),
        "public/install.sh": auth(
            "hand-written installer",
            note="VERSION + VERSION_TRANSCRIPT rewritten by scripts/sync-version.mjs — the transcript is a REAL captured `nika --version` (honesty law: re-capture, never hand-edit)",
        ),
        "public/.well-known/security.txt": auth("hand-kept RFC 9116 security contact"),
        "public/icons.svg": auth(
            "hand-assembled social sprite",
            note="BYTE-FROZEN input: design/build.mjs READS it (build.mjs:87-100 — 'public/icons.svg is BYTE-FROZEN (the visual goldens shoot the footer)') — never regenerated",
        ),
        "public/manifest.webmanifest": auth("hand-written PWA manifest"),
        "public/favicon.ico": auth("studio brand asset — exported artwork, no in-repo generator"),
        "public/favicon.svg": auth("studio brand asset — exported artwork, no in-repo generator"),
        "public/icon-192.png": auth("studio brand asset — exported artwork, no in-repo generator"),
        "public/icon-512.png": auth("studio brand asset — exported artwork, no in-repo generator"),
        "public/icon-mask.png": auth("studio brand asset — exported artwork, no in-repo generator"),
        "public/apple-touch-icon.png": auth(
            "studio brand asset — exported artwork, no in-repo generator"
        ),
        "public/nika.svg": auth("studio brand asset — exported artwork, no in-repo generator"),
        "src/assets/nika.svg": auth("studio brand asset — exported artwork, no in-repo generator"),
        # ── authored files carrying bot-maintained fields ─────────────────
        "src/content.ts": auth(
            "hand-written content constants",
            note="the ENGINE_VERSION constant is bot-healed on engine releases (.github/workflows/release-heal.yml → scripts/sync-version.mjs) — a bot-maintained field inside an authored file",
        ),
        "src/content/learn.ts": auth("hand-written learn-track copy", note=sync_note),
        "src/content/install.ts": auth("hand-written install copy", note=sync_note),
        # ── this manifest's own lane ──────────────────────────────────────
        SELF: auth("hand-written estate projector (this manifest's generator)"),
    }


# ── pattern groups (glob → shared class/evidence/derivation) ───────────────


def glob_to_re(g: str) -> re.Pattern:
    out, i = [], 0
    while i < len(g):
        if g.startswith("**/", i):
            out.append(r"(?:.*/)?")
            i += 3
        elif g.startswith("**", i):
            out.append(r".*")
            i += 2
        elif g[i] == "*":
            out.append(r"[^/]*")
            i += 1
        elif g[i] == "?":
            out.append(r"[^/]")
            i += 1
        else:
            out.append(re.escape(g[i]))
            i += 1
    return re.compile("".join(out) + r"\Z")


def no_marker(rel: str, chunk: str) -> bool:
    return not marker_hit(chunk)


def build_patterns(contract: dict, engine: str) -> list:
    media_gate = "scripts/media/validate-media.sh (the honesty + budget gate)"
    return [
        {
            "glob": "public/brand/icons/*.svg",
            "when": lambda rel, chunk: "generated by design/build.mjs" in chunk,
            "class": "generated",
            "evidence": "every member carries the in-file marker 'generated by design/build.mjs' (the served house icon catalog)",
            "derivation": {"tool": f"node {ICONS} (pnpm icons)", "gate": ICONS_GATE, "inputs": ICONS_INPUTS},
        },
        {
            "glob": "public/brand/*",
            "when": no_marker,
            "class": "authored",
            "evidence": "studio brand artwork exports (logo · mark · tile suite) — no in-repo generator; THIRD_PARTY_NOTICES.md declares the set house-owned",
        },
        {
            "glob": "public/og*.png",
            "class": "generated",
            "evidence": "the OG card set — scripts/build-og-card.mjs shoots scripts/og-card.html per route/post deck (build-og-card.mjs header lists the plates)",
            "derivation": {
                "tool": "node scripts/build-og-card.mjs (headless Chrome shot)",
                "gate": f"src/test/og-cards.test.ts — pnpm test in {GATE_YML}",
                "inputs": ["scripts/og-card.html", "the copy decks in scripts/build-og-card.mjs", "public/fonts/*"],
            },
        },
        {
            "glob": "public/blog/**",
            "class": "generated",
            "evidence": "the markdown twins scripts/build-blog.mjs projects from content/blog/*.md (build-blog.mjs:316 — 'public/blog/<slug>.md' with canon markers applied)",
            "derivation": {
                "tool": "node scripts/build-blog.mjs",
                "gate": BLOG_GATE,
                "inputs": ["content/blog/*.md", "src/canon.generated.ts (canon marker values)"],
            },
        },
        {
            "glob": "public/media/**",
            "class": "generated",
            "evidence": "the run-explains media set — rendered by scripts/media/render-scenes.mjs (headless Chrome frame-stepping + ffmpeg) from real pty captures; 'every terminal pixel traces back to a raw pty capture of the real nika binary' (scripts/media/README.md)",
            "derivation": {
                "tool": "node scripts/media/render-scenes.mjs (deliberate manual lane)",
                "gate": media_gate,
                "inputs": ["scripts/media/scenes/*.html", "scripts/media/raw/*.ansi", "scripts/media/raw/manifest.json"],
            },
        },
        {
            "glob": "public/fonts/*.woff2",
            "class": "pinned-copy",
            "evidence": "third-party fonts self-hosted (Martian Grotesk/Mono · SIL OFL 1.1; Clash Display · Fontshare ITF FFL) per THIRD_PARTY_NOTICES.md",
            "note": "no upstream rev pin — pinned by the vendored bytes only",
        },
        {
            "glob": "public/library/*.nika.yaml",
            "class": "authored",
            "evidence": "hand-crafted example workflows (SPDX headers · © SuperNovae Studio)",
            "note": f"src/test/onpage-yaml.test.ts validates them against the SHIPPED schema (engine {engine})",
        },
        {
            "glob": "tests/visual/golden/**",
            "class": "generated",
            "evidence": "visual-regression goldens — captured from the built site by scripts/visual-regress.mjs --update (pnpm visual:update); re-baked deliberately per platform (darwin/linux)",
            "derivation": {
                "tool": "node scripts/visual-regress.mjs --update (pnpm visual:update)",
                "gate": ".github/workflows/visual.yml → pnpm visual (pixel-compare against the goldens)",
                "inputs": ["the built site (dist) rendered in headless Chrome"],
            },
        },
        {
            "glob": "scripts/media/raw/**",
            "class": "generated",
            "evidence": "raw pty captures of the real released binary — 'raw/*.ansi (bytes, untouched)' + manifest.json (binary · commands · exit codes) per scripts/media/README.md",
            "derivation": {
                "tool": "python3 scripts/media/capture-terminal.py (real pty 100x34 · deliberate manual lane)",
                "gate": media_gate,
                "inputs": ["the released nika binary", "scripts/media/fixtures/** (the workflows the captures ran)"],
            },
            "note": "honesty law: no fake commands, no fake output, no hand-edited transcripts",
        },
        {
            "glob": "scripts/media/scenes/*.html",
            "when": lambda rel, chunk: marker_hit(chunk),
            "class": "generated",
            "evidence": "scene pages built from the raw captures — 'gen-scenes.mjs: raw + manifest → scenes/*.html (GENERATED — never hand-edit)' (scripts/media/README.md) + in-file markers",
            "derivation": {
                "tool": "node scripts/media/gen-scenes.mjs",
                "gate": media_gate,
                "inputs": ["scripts/media/raw/*.ansi", "scripts/media/raw/manifest.json", "scripts/media/ansi2html.mjs (mechanical ANSI→HTML)"],
            },
        },
        {
            "glob": "scripts/media/fixtures/**",
            "class": "authored",
            "evidence": "the runnable fixture workflows + items the captures ran (each dir runnable in place — scripts/media/README.md)",
        },
        {
            "glob": "scripts/lens/contracts/*.v1.json",
            "class": "authored",
            "evidence": "hand-written LENS policy contracts (declarative gate configuration — channels · gates · counts · features · presentation · snippets); the repinned digest baselines are listed individually above",
        },
        {
            "glob": "content/blog/**",
            "class": "authored",
            "evidence": "the authored blog sources — the markdown here is the SSOT the public/blog twins and generated modules mirror (+ the lane README)",
        },
        {
            "glob": "content/i18n/**",
            "class": "authored",
            "evidence": "the reviewed L1 translation corpus — one yaml per locale per page, en = the extraction twin (content/i18n/README.md)",
            "note": "the scripts/i18n/localize-page.nika.yaml lane assists drafts; committed as reviewed source — key parity gated by src/test/i18n.test.ts + i18n-lexicon.test.ts",
        },
        {
            "glob": "content/tool-usage/*.nika.yaml",
            "class": "authored",
            "evidence": "crafted minimal usage workflows (nika-check green) — inputs of scripts/build-tool-usage.mjs (its marker cites them)",
        },
        {
            "glob": "design/**",
            "when": no_marker,
            "class": "authored",
            "evidence": "the icon system's SSOT + projector + artwork sources (design/icons.yaml · design/build.mjs · design/svg glyphs) — THIRD_PARTY_NOTICES.md: house set, no third-party icons",
        },
        {
            "glob": "docs/plans/*.md",
            "class": "authored",
            "evidence": "hand-written design/implementation plans",
        },
        {
            "glob": ".github/workflows/*.yml",
            "class": "authored",
            "evidence": "hand-written CI trust model (comments narrate design decisions); release-heal.yml + spec-resync.yml edit OTHER files, nothing writes these",
        },
        {
            "glob": "src/**/*.generated.*",
            "when": lambda rel, chunk: ATLAS in chunk,
            "class": "generated",
            "evidence": "every member's in-file marker cites scripts/atlas/build-atlas.mjs (from scripts/atlas/sets.yaml — the authored descriptor + the gated sources)",
            "derivation": {"tool": f"node {ATLAS} (pnpm atlas)", "gate": ATLAS_GATE, "inputs": ATLAS_INPUTS},
        },
        {
            "glob": "src/**",
            "when": no_marker,
            "class": "authored",
            "evidence": "hand-written site source (components · pages · sections · styles · lib · tests) — no generation marker",
        },
        {
            "glob": "scripts/**",
            "when": no_marker,
            "class": "authored",
            "evidence": "hand-written build/gate/verify tooling — these ARE the generators and judges (SPDX/design prose headers · no generation marker)",
        },
    ]


# ── the spec-resync contract outputs (evidence source #1) ──────────────────


def contract_entries(contract: dict) -> dict:
    spec = contract["spec"]
    spec_ref = f"{spec['repository']}@{spec['commit'][:12]}"
    resync_gate = (
        f"{RESYNC_YML} + pnpm spec-resync:verify (LENS-011 scripts/verify_generated_outputs.mjs — "
        f"literal path set AND byte digests vs {CONTRACT_PATH})"
    )
    out = {}
    for g in contract["generators"]:
        root = g["root"]
        runtime = g["runtime"]
        for path in g["outputs"]:
            if runtime == "copy":
                src = f"{spec_ref}:{g['path']}" if root == "spec" else g["path"]
                out[path] = {
                    "class": "pinned-copy",
                    "evidence": f"resync contract generator '{g['id']}' (runtime: copy) — byte-copy of {src} at the resync pin",
                    "derivation": {
                        "tool": "node scripts/spec-resync-run.mjs (the pinned resync)",
                        "gate": resync_gate,
                        "inputs": [".github/nika-spec-pin.json", src],
                    },
                }
            else:
                tool_repo = spec_ref if root == "spec" else "supernovae-st/nika.sh"
                out[path] = {
                    "class": "generated",
                    "evidence": f"declared output of resync contract generator '{g['id']}' ({tool_repo} {g['path']} · generator sha256-pinned in the contract)",
                    "derivation": {
                        "tool": f"{g['runtime']} {g['path']} (root: {root} · via node scripts/spec-resync-run.mjs)",
                        "gate": resync_gate,
                        "inputs": [".github/nika-spec-pin.json", f"{spec_ref} (tree {spec['tree'][:12]})"],
                    },
                }
    return out


# ── classification pipeline ────────────────────────────────────────────────


def classify_generic(rel: str, chunk: str) -> dict:
    if marker_hit(chunk):
        tool = marker_tool(chunk)
        if tool:
            gate = marker_gate(chunk) or TOOL_GATES.get(tool, GATE_FALLBACK)
            inputs = TOOL_INPUTS.get(tool, [f"declared in the {tool} header"])
            first = next(
                (l.strip() for l in chunk.splitlines() if MARK.search(l)), ""
            )
            return {
                "class": "generated",
                "evidence": f"in-file marker: {first[:160]}",
                "derivation": {"tool": tool, "gate": gate, "inputs": inputs},
            }
        return {
            "class": "generated",
            "evidence": "in-file generation marker present (tool not mechanically extractable)",
            "derivation": {
                "tool": "unknown — see the file's own header",
                "gate": GATE_FALLBACK,
                "inputs": ["see the file's own header"],
            },
            "note": "marker-without-tool — tighten the extractor or add an override",
        }
    return {
        "class": "authored",
        "evidence": "no generation marker or known role found",
        "note": "unverified-default",
    }


def q(s) -> str:
    """A JSON string is a valid YAML scalar — deterministic quoting for free."""
    return json.dumps(s, ensure_ascii=False)


def render() -> str:
    contract = load_contract()
    engine = shipped_engine()
    spec = contract["spec"]
    overrides = build_overrides(contract, engine)
    contract_rows = contract_entries(contract)
    patterns = build_patterns(contract, engine)
    for p in patterns:
        p["_re"] = glob_to_re(p["glob"])
        p["_members"] = []

    singles = []
    counts = {c: 0 for c in CLASSES}
    unverified = 0

    for rel in tracked_files():
        body = (ROOT / rel).read_bytes()
        sha = hashlib.sha256(body).hexdigest()
        chunk = head_chunk(body)

        row = None
        if rel in overrides:
            row = dict(overrides[rel])
        elif rel in contract_rows:
            row = dict(contract_rows[rel])
        else:
            for p in patterns:
                if p["_re"].match(rel) and ("when" not in p or p["when"](rel, chunk)):
                    p["_members"].append((rel, sha))
                    counts[p["class"]] += 1
                    break
            else:
                row = classify_generic(rel, chunk)

        if row is not None:
            row["path"] = rel
            row["sha256"] = sha
            counts[row["class"]] += 1
            if row.get("note") == "unverified-default":
                unverified += 1
            singles.append(row)

    singles.sort(key=lambda r: r["path"])
    live_patterns = [p for p in patterns if p["_members"]]

    lines = [
        "# GENERATED by scripts/estate.py — do not hand-edit.",
        "# The estate manifest: every tracked file declares its provenance.",
        "# OBSERVATION MODE (E0): this declares what IS — it enforces nothing.",
        "# SCHEMA 2 (pattern manifest — this tree tracks ~950 files):",
        "#   patterns: glob groups sharing one class/evidence/derivation; each",
        "#   carries its member count and an aggregate sha256 (sha256 of the",
        '#   sorted "path sha256" lines of its members) — any member byte-change',
        "#   or membership change diverges the render and --check exits 5.",
        "#   files: per-file entries — exact-path overrides and evidence-bearing",
        "#   singletons — matched BEFORE patterns.",
        "# Re-generate: python3 scripts/estate.py --write",
        "# Check:       python3 scripts/estate.py --check   (re-emits · byte-compares · exit 5 on divergence)",
        f"estate_schema: {ESTATE_SCHEMA}",
        "mode: observation",
        "repo: supernovae-st/nika.sh",
        f"spec_pin: {q(spec['repository'] + '@' + spec['commit'])}",
        f"shipped_engine: {q(engine)}",
        "classes:",
    ]
    for c in CLASSES:
        lines.append(f"  {c}: {q(CLASSES[c])}")
    lines.append("summary:")
    for c in CLASSES:
        lines.append(f"  {c}: {counts[c]}")
    lines.append(f"  unverified-default: {unverified}")
    lines.append(f"  files_listed: {len(singles)}")
    lines.append(f"  patterns: {len(live_patterns)}")
    lines.append(f"  files_total: {len(singles) + sum(len(p['_members']) for p in live_patterns)}")

    lines.append("patterns:")
    for p in live_patterns:
        members = sorted(p["_members"])
        agg = hashlib.sha256(
            ("".join(f"{rel} {sha}\n" for rel, sha in members)).encode()
        ).hexdigest()
        lines.append(f"- glob: {q(p['glob'])}")
        lines.append(f"  class: {p['class']}")
        lines.append(f"  count: {len(members)}")
        lines.append(f"  sha256: {agg}")
        lines.append(f"  evidence: {q(p['evidence'])}")
        if "derivation" in p:
            d = p["derivation"]
            lines.append("  derivation:")
            lines.append(f"    tool: {q(d['tool'])}")
            lines.append(f"    gate: {q(d['gate'])}")
            lines.append("    inputs:")
            for i in d["inputs"]:
                lines.append(f"    - {q(i)}")
        if p.get("note"):
            lines.append(f"  note: {q(p['note'])}")

    lines.append("files:")
    for row in singles:
        lines.append(f"- path: {q(row['path'])}")
        lines.append(f"  class: {row['class']}")
        lines.append(f"  sha256: {row['sha256']}")
        lines.append(f"  evidence: {q(row['evidence'])}")
        if "derivation" in row:
            d = row["derivation"]
            lines.append("  derivation:")
            lines.append(f"    tool: {q(d['tool'])}")
            lines.append(f"    gate: {q(d['gate'])}")
            lines.append("    inputs:")
            for i in d["inputs"]:
                lines.append(f"    - {q(i)}")
        if "note" in row:
            lines.append(f"  note: {q(row['note'])}")
    return "\n".join(lines) + "\n"


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--write", "--check"):
        print(f"estate.py: unknown mode {mode!r} (--write | --check)", file=sys.stderr)
        return 2
    rendered = render()
    if mode == "--write":
        ESTATE.write_text(rendered)
        n_f = rendered.count("\n- path: ")
        n_p = rendered.count("\n- glob: ")
        print(f"✓ estate.yaml · {n_f} files listed + {n_p} patterns")
        return 0
    if not ESTATE.is_file() or ESTATE.read_text() != rendered:
        print(
            "✗ estate drift · estate.yaml diverges from the tracked tree — run scripts/estate.py --write",
            file=sys.stderr,
        )
        return 5
    print("✓ estate.yaml in sync with the tracked tree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
